/** Canonical PTW type definitions (checklists, colours, extra fields). */
export const PERMIT_TYPES = {
  hot_work: {
    label: "Hot work permit",
    color: "#E24B4A", bg: "#FCEBEB",
    icon: "M12 2c-4 6-4 10 0 14 2-3 2-5 0-7 1 5 5 7 5 10a5 5 0 01-10 0c0-5 5-9 5-17z",
    description: "Welding, grinding, cutting, brazing, soldering — any work producing heat or sparks",
    checklist: [
      "Area cleared of all combustible materials within 10 metres",
      "2 × 9kg fire extinguishers and fire blanket in position",
      "Hot works equipment inspected and in good condition",
      "Fire alarm isolated in work area (with supervisor approval)",
      "Sprinkler heads protected where applicable",
      "Fire watch person nominated and briefed",
      "All drains, ducts and openings sealed against spark entry",
      "Work area wetted down where appropriate",
      "Permit duration agreed — maximum 8 hours",
      "Post-work inspection after minimum 1 hour agreed",
    ],
    extraFields: [
      { key:"equipment", label:"Equipment to be used", type:"text" },
      { key:"fireWatcher", label:"Fire watcher name", type:"text" },
      { key:"postInspectionTime", label:"Post-work inspection time", type:"datetime-local" },
    ],
  },
  electrical: {
    label: "Electrical isolation permit",
    color: "#185FA5", bg: "#E6F1FB",
    icon: "M13 2L3 14h9l-1 8 10-12h-9l1-8z",
    description: "Safe isolation of electrical circuits, LOTO, live electrical work",
    checklist: [
      "Isolation point identified and confirmed",
      "Isolation carried out by authorised person",
      "Lock-off device applied and padlock secured",
      "Warning notice posted at isolation point",
      "Voltage indicator tested on known live source",
      "System proved dead with voltage indicator (GS38 compliant)",
      "Voltage indicator re-tested on known live source after proving dead",
      "All connected equipment confirmed de-energised",
      "Permit held by the person performing the work",
    ],
    extraFields: [
      { key:"circuitRef", label:"Circuit / board reference", type:"text" },
      { key:"lockoutRef", label:"Lock-out padlock number", type:"text" },
      { key:"authorisedPerson", label:"Authorised person (isolation)", type:"text" },
    ],
  },
  work_at_height: {
    label: "Work at height permit",
    color: "#854F0B", bg: "#FAEEDA",
    icon: "M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z",
    description: "Scaffold, MEWP, ladders, rope access — any work above 2m",
    checklist: [
      "Access equipment inspected and signed off before use",
      "Scaffold: handover certificate reviewed and current",
      "MEWP: daily pre-use check completed; operator holds IPAF card",
      "Edge protection confirmed in place at all open edges",
      "Harness and lanyard inspected; attached to anchor point",
      "Exclusion zone established below work area",
      "Weather conditions assessed — not commenced in high winds or ice",
      "Rescue plan in place for MEWP/rope access operations",
      "Overhead hazards identified and communicated",
    ],
    extraFields: [
      { key:"accessEquipment", label:"Access equipment type / ref", type:"text" },
      { key:"maxHeight", label:"Maximum working height (m)", type:"number" },
      { key:"rescuePlan", label:"Rescue plan reference", type:"text" },
    ],
  },
  confined_space: {
    label: "Confined space entry permit",
    color: "#791F1F", bg: "#FCEBEB",
    icon: "M12 2a10 10 0 100 20A10 10 0 0012 2zm0 4a6 6 0 110 12A6 6 0 0112 6z",
    description: "Entry into tanks, vessels, sewers, voids — any confined space",
    checklist: [
      "Confined space risk assessment reviewed and current",
      "Atmospheric test completed: O₂ (19.5–23.5%), CO (<20ppm), H₂S (<1ppm), LEL (<10%)",
      "Continuous monitoring in use during occupation",
      "Mechanical ventilation provided and confirmed operational",
      "Stand-by person briefed and in position outside space",
      "Rescue equipment (tripod, winch, harness) rigged and ready",
      "Emergency rescue plan confirmed with stand-by person",
      "All energy sources isolated (LOTO) before entry",
      "Communication system tested between entrant and stand-by",
      "Maximum occupancy and time in space agreed",
    ],
    extraFields: [
      { key:"spaceDescription", label:"Space description / location", type:"text" },
      { key:"standByPerson", label:"Stand-by person name", type:"text" },
      { key:"atmosphericReadings", label:"Initial atmospheric readings", type:"text" },
    ],
  },
  excavation: {
    label: "Permit to dig / excavation",
    color: "#3B6D11", bg: "#EAF3DE",
    icon: "M2 20h20M5 20V8l7-6 7 6v12",
    description: "Any excavation, ground disturbance, core drilling — utility strike prevention",
    checklist: [
      "Utility drawings obtained from all relevant authorities",
      "CAT scan (Cable Avoidance Tool) survey completed",
      "Survey results marked out on ground before breaking",
      "Hand dig zone (0.5m either side of marked service) confirmed",
      "Excavation supervisor nominated and briefed",
      "Shoring / trench support confirmed if depth exceeds 1.2m",
      "Safe means of access and egress provided",
      "Spoil stored minimum 0.5m from excavation edge",
      "Barriers and covers in place over open excavation",
      "Adjacent structures assessed for undermining risk",
    ],
    extraFields: [
      { key:"catScanBy", label:"CAT scan carried out by", type:"text" },
      { key:"knownServices", label:"Known services in area", type:"text" },
      { key:"excavationDepth", label:"Maximum excavation depth (m)", type:"number" },
    ],
  },
  lifting: {
    label: "Lifting operations permit",
    color: "#3C3489", bg: "#EEEDFE",
    icon: "M18 8h1a4 4 0 010 8h-1M2 8h16v9a4 4 0 01-4 4H6a4 4 0 01-4-4V8zM6 1v3M10 1v3M14 1v3",
    description: "Crane lifts, MEWP lifts, pallet truck lifts — all LOLER operations",
    checklist: [
      "Lifting plan prepared by competent person",
      "All lifting equipment within current LOLER thorough examination",
      "Appointed Person (AP) present for crane lifts",
      "Rigging plan reviewed — correct sling type, rating and angle",
      "Load weight confirmed — does not exceed SWL of any component",
      "Exclusion zone established below and around lift",
      "Banksman / slinger in position with agreed signal system",
      "Ground conditions checked — stable, level, adequate bearing capacity",
      "Overhead hazards (power lines, structures) confirmed clear",
      "Weather / wind speed assessed and within limits",
    ],
    extraFields: [
      { key:"liftingEquipment", label:"Lifting equipment / crane ID", type:"text" },
      { key:"swl", label:"SWL of equipment (tonnes)", type:"number" },
      { key:"appointedPerson", label:"Appointed Person name", type:"text" },
    ],
  },
  cold_work: {
    label: "Cold work permit",
    color: "#0C447C", bg: "#E6F1FB",
    icon: "M12 2v20M2 12h20M4.93 4.93l14.14 14.14M19.07 4.93L4.93 19.07",
    description: "Maintenance on live plant without hot works — LOTO, mechanical isolation",
    checklist: [
      "All energy sources identified (electrical, pneumatic, hydraulic, gravity, stored pressure)",
      "Full LOTO applied to all energy isolation points",
      "System depressurised and confirmed pressure-free",
      "Stored energy (springs, counterweights) safely discharged",
      "Permit holder has sole control of all padlocks",
      "Try-out: attempt to start/operate equipment — confirmed no movement",
      "Adjacent equipment not affected by isolation confirmed or separately isolated",
      "Waste / drainage provisions in place for fluid release",
    ],
    extraFields: [
      { key:"equipmentTag", label:"Equipment tag / ID", type:"text" },
      { key:"isolationPoints", label:"Number of isolation points", type:"number" },
      { key:"lotoKeyHolder", label:"LOTO key holder name", type:"text" },
    ],
  },
  line_break: {
    label: "Line break permit",
    color: "#712B13", bg: "#FAECE7",
    icon: "M12 2v4m0 12v4M4.93 4.93l2.83 2.83m8.48 8.48l2.83 2.83M2 12h4m12 0h4M4.93 19.07l2.83-2.83m8.48-8.48l2.83-2.83",
    description: "Opening any pressurised pipe, vessel or system containing fluid, gas or chemical",
    checklist: [
      "System isolated, depressurised and confirmed at atmospheric pressure",
      "Contents identified — COSHH assessment reviewed for any chemical release",
      "Drain / bleed point confirmed fully open before breaking joint",
      "PPE specified for contents (chemical resistant, face shield, etc.) in use",
      "Drip trays or containment in place for residual fluids",
      "Adjacent systems confirmed isolated — no inadvertent pressurisation possible",
      "Permit holder holds all isolation certificates",
      "First break carried out slowly; standby for unexpected pressure release",
      "Spill kit and emergency wash available at point of work",
    ],
    extraFields: [
      { key:"pipeContents", label:"Pipe contents", type:"text" },
      { key:"workingPressure", label:"Normal working pressure (bar)", type:"number" },
      { key:"temperature", label:"Contents temperature (°C)", type:"number" },
    ],
  },
  roof_access: {
    label: "Roof access permit",
    color: "#633806", bg: "#FAEEDA",
    icon: "M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z",
    description: "Any access to roof — flat, pitched, fragile or otherwise",
    checklist: [
      "Pre-access roof condition survey completed",
      "Fragile materials (rooflights, AC cement) identified and marked",
      "Edge protection confirmed in place at all leading edges",
      "Access route agreed — no walking on fragile surfaces",
      "Crawling boards available for any fragile surface crossing",
      "Weather assessed — not accessed in ice, snow or wind above 15 m/s",
      "Maximum persons on roof agreed and not exceeded",
      "Materials secured against wind displacement",
      "No materials or tools left at roof edge unattended",
      "Post-work roof inspection before closing permit",
    ],
    extraFields: [
      { key:"roofType", label:"Roof type (flat/pitched/fragile)", type:"text" },
      { key:"accessMethod", label:"Access method (ladder/scaffold/hatch)", type:"text" },
      { key:"maxPersons", label:"Maximum persons on roof", type:"number" },
    ],
  },
  night_works: {
    label: "Night / out-of-hours permit",
    color: "#26215C", bg: "#EEEDFE",
    icon: "M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z",
    description: "Works outside normal operating hours — night, weekend, holiday",
    checklist: [
      "Site manager / client representative notified and approved out-of-hours working",
      "Emergency contact for site owner confirmed and available",
      "Security arrangements reviewed — site access and alarm procedures confirmed",
      "Lone working risk assessment completed if applicable",
      "First aider available or first aid arrangements confirmed adequate",
      "All workers briefed on emergency procedures for out-of-hours",
      "Adequate lighting confirmed before works commence",
      "Noise restrictions for out-of-hours work identified and communicated",
      "Check-in / check-out system in place",
    ],
    extraFields: [
      { key:"siteContact", label:"Out-of-hours site contact / phone", type:"text" },
      { key:"securityCode", label:"Security / alarm arrangements", type:"text" },
      { key:"loneworkingArrangement", label:"Lone working check-in interval", type:"text" },
    ],
  },
  valve_isolation: {
    label: "Valve isolation permit",
    color: "#085041", bg: "#E1F5EE",
    icon: "M12 2a10 10 0 100 20 10 10 0 000-20zm0 4v8m0 4h.01",
    description: "Planned operation of process valves — food, pharma, chemical, water",
    checklist: [
      "P&ID reviewed — all valves to be operated identified",
      "Upstream and downstream system status confirmed",
      "Consequence of valve operation reviewed (product loss, pressure build, backflow)",
      "All downstream operatives notified before valve operation",
      "Valve position indicator / position confirmed before and after operation",
      "Isolation confirmed by zero-flow check where applicable",
      "Pressure differential across isolation confirmed safe",
      "Blind flange / spade confirmation where positive isolation required",
      "Valve closure documented in site log",
    ],
    extraFields: [
      { key:"valveTag", label:"Valve tag number(s)", type:"text" },
      { key:"systemContents", label:"System contents", type:"text" },
      { key:"authorisedOperator", label:"Authorised valve operator", type:"text" },
    ],
  },
  visitor_access: {
    label: "Visitor / contractor access permit",
    color: "#444441", bg: "#F1EFE8",
    icon: "M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2M9 11a4 4 0 100-8 4 4 0 000 8zM23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75",
    description: "Authorised access for visitors, auditors, clients, new subcontractors",
    checklist: [
      "Visitor identity confirmed and signed in at reception",
      "Site induction completed or confirmed current",
      "PPE requirements communicated and confirmed compliance",
      "Visitor escort assigned for duration of visit",
      "Restricted areas identified — visitor not to enter without escort",
      "Emergency procedure explained to visitor",
      "Visitor contact details recorded",
      "Purpose of visit recorded",
      "Sign-out confirmed on departure",
    ],
    extraFields: [
      { key:"visitorCompany", label:"Visitor company", type:"text" },
      { key:"purposeOfVisit", label:"Purpose of visit", type:"text" },
      { key:"escortName", label:"Escort / host name", type:"text" },
    ],
  },
  radiography: {
    label: "Radiography permit",
    color: "#791F1F", bg: "#FCEBEB",
    icon: "M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41",
    description: "Gamma-ray or X-ray NDT inspection — ionising radiation source use",
    checklist: [
      "Radiation Protection Supervisor (RPS) authorised the work in writing",
      "Radiation Protection Adviser (RPA) consulted for non-routine operations",
      "Controlled area barriers and warning signs in place (minimum 2m from source)",
      "All persons in vicinity briefed — controlled area must remain clear",
      "Dose rate survey completed; boundaries confirmed adequate",
      "Dosimeters issued to all classified workers",
      "Source transport container inspected; integrity confirmed",
      "Emergency procedures confirmed with all personnel",
      "Post-exposure survey completed; source confirmed returned to container",
      "Dose records updated on completion",
    ],
    extraFields: [
      { key:"sourceType", label:"Radiation source type (Ir-192, X-ray, etc.)", type:"text" },
      { key:"rps", label:"Radiation Protection Supervisor name", type:"text" },
      { key:"controlledAreaRadius", label:"Controlled area radius (m)", type:"number" },
    ],
  },
  ground_disturbance: {
    label: "Ground disturbance permit",
    color: "#27500A", bg: "#EAF3DE",
    icon: "M3 20h18M5 20V8l7-6 7 6v12M9 20v-6h6v6",
    description: "Piling, ground anchors, driven posts, any disturbance beyond CAT scan depth",
    checklist: [
      "Ground investigation report reviewed — soil type, contamination, voids, buried structures",
      "All utility records obtained; CAT scan completed",
      "Archaeological or heritage desk-based assessment completed where required",
      "UXO (unexploded ordnance) risk assessed — clearance certificate if applicable",
      "Ground disturbance method approved by geotechnical engineer",
      "Vibration monitoring on adjacent structures — alert thresholds set",
      "Pre-work condition survey of all adjacent structures completed and photographed",
      "Groundwater monitoring in place if dewatering required",
      "Environmental protection: no ground disturbance adjacent to watercourse without EA consent",
    ],
    extraFields: [
      { key:"groundType", label:"Ground type / geology", type:"text" },
      { key:"disturbanceMethod", label:"Method of disturbance", type:"text" },
      { key:"maxDepth", label:"Maximum disturbance depth (m)", type:"number" },
    ],
  },
  general: {
    label: "General permit to work",
    color: "#5F5E5A", bg: "#F1EFE8",
    icon: "M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4",
    icon2: true,
    description: "General works not covered by a specific permit type",
    checklist: [
      "Work scope clearly defined and communicated to all operatives",
      "Hazards identified and controls in place",
      "Appropriate PPE issued and worn",
      "Emergency procedures communicated",
      "First aid arrangements confirmed",
      "Permit area identified and access controlled",
    ],
    extraFields: [],
  },
};
export function checklistStringsForType(t) {
  return PERMIT_TYPES[t]?.checklist || [];
}
