import { useMemo, useState } from "react";
import { getOrgSettings } from "../components/OrgSettings";
import { pushAudit } from "../utils/auditLog";

const getOrgId = () => localStorage.getItem("mysafeops_orgId") || "default";
const sk = (k) => `${k}_${getOrgId()}`;
const load = (k, fb) => {
  try {
    return JSON.parse(localStorage.getItem(sk(k)) || JSON.stringify(fb));
  } catch {
    return fb;
  }
};

function printMonthlyReport(monthLabel) {
  const org = getOrgSettings();
  const workers = load("mysafeops_workers", []);
  const projects = load("mysafeops_projects", []);
  const permits = load("permits_v2", []);
  const incidents = load("mysafeops_incidents", []);
  const snags = load("snags", []);
  const rams = load("rams_builder_docs", []);
  const now = new Date();
  const expiredCerts = workers.flatMap((w) =>
    (w.certifications || []).filter((c) => c.expiryDate && new Date(c.expiryDate) < now)
  );
  const expiring = workers.flatMap((w) =>
    (w.certifications || []).filter((c) => c.expiryDate).map((c) => ({ ...c, workerName: w.name }))
  );
  const in30 = expiring.filter((c) => {
    const d = Math.ceil((new Date(c.expiryDate) - now) / 86400000);
    return d >= 0 && d <= 30;
  });

  let score = 100;
  if (expiredCerts.length) score -= Math.min(20, expiredCerts.length * 4);
  const overdueSnags = snags.filter((s) => s.dueDate && s.status === "open" && new Date(s.dueDate) < now);
  if (overdueSnags.length) score -= Math.min(15, overdueSnags.length * 3);
  const expiredPermits = permits.filter((p) => p.expiryDate && new Date(p.expiryDate) < now && p.status === "active");
  if (expiredPermits.length) score -= Math.min(20, expiredPermits.length * 5);
  score = Math.max(0, score);

  const win = window.open("", "_blank");
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Monthly H&S summary — ${monthLabel}</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 12px; color: #000; margin: 0; padding: 20px; }
    h1 { background: ${org.primaryColor || "#0d9488"}; color: #fff; padding: 8px 12px; font-size: 15px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
    th { background: #f4f4f4; }
    @media print { h1 { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style></head><body>
  <div style="display:flex;align-items:center;gap:16px;border-bottom:2px solid ${org.primaryColor || "#0d9488"};padding-bottom:10px;margin-bottom:14px">
    ${org.logo ? `<img src="${org.logo}" style="height:44px;max-width:120px;object-fit:contain"/>` : ""}
    <div>
      <div style="font-weight:bold;font-size:14px">${org.name || "MySafeOps"}</div>
      ${org.pdfHeader ? `<div style="font-size:11px;color:#666">${org.pdfHeader}</div>` : ""}
    </div>
  </div>
  <h1>Monthly health & safety summary — ${monthLabel}</h1>
  <p>Generated ${now.toLocaleString("en-GB")}</p>
  <h2>Snapshot</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Compliance score (estimate)</td><td>${score}%</td></tr>
    <tr><td>Active projects</td><td>${projects.length}</td></tr>
    <tr><td>Workers on record</td><td>${workers.length}</td></tr>
    <tr><td>RAMS documents</td><td>${rams.length}</td></tr>
    <tr><td>Permits (all statuses)</td><td>${permits.length}</td></tr>
    <tr><td>Open snags</td><td>${snags.filter((s) => s.status === "open").length}</td></tr>
    <tr><td>Incidents / near misses (total)</td><td>${incidents.length}</td></tr>
    <tr><td>Certificates expiring in 30 days</td><td>${in30.length}</td></tr>
    <tr><td>Expired certificates (action required)</td><td>${expiredCerts.length}</td></tr>
  </table>
  <h2>Notes</h2>
  <p>This report is generated locally from MySafeOps data. It does not replace legal reporting (e.g. RIDDOR to HSE).</p>
  <p style="font-size:10px;color:#999;margin-top:16px">${org.pdfFooter || "Generated by MySafeOps"}</p>
  </body></html>`);
  win.document.close();
  win.print();
  pushAudit({ action: "monthly_report_print", entity: "report", detail: monthLabel });
}

const ss = {
  btnP: { padding: "7px 14px", borderRadius: 6, border: "0.5px solid #085041", background: "#0d9488", color: "#E1F5EE", fontSize: 13, cursor: "pointer", fontFamily: "DM Sans,sans-serif" },
  card: { background: "var(--color-background-primary,#fff)", border: "0.5px solid var(--color-border-tertiary,#e5e5e5)", borderRadius: 12, padding: "1.25rem" },
  inp: { padding: "7px 10px", borderRadius: 6, border: "0.5px solid #ccc", fontSize: 13, fontFamily: "DM Sans,sans-serif" },
};

export default function MonthlyReport() {
  const [ym, setYm] = useState(() => {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
  });

  const label = useMemo(() => {
    const [y, m] = ym.split("-").map(Number);
    return new Date(y, m - 1, 1).toLocaleDateString("en-GB", { month: "long", year: "numeric" });
  }, [ym]);

  return (
    <div style={{ fontFamily: "DM Sans,system-ui,sans-serif", padding: "1.25rem 0", fontSize: 14 }}>
      <h2 style={{ fontWeight: 500, fontSize: 20, margin: "0 0 8px" }}>Monthly H&S report</h2>
      <p style={{ fontSize: 12, color: "var(--color-text-secondary)", marginBottom: 20 }}>
        Branded print summary: compliance estimate, project/worker counts, RAMS, permits, snags, incidents, certificate horizon.
      </p>
      <div style={{ ...ss.card, maxWidth: 420 }}>
        <label style={{ display: "block", fontSize: 12, fontWeight: 500, marginBottom: 6 }}>Report period (label)</label>
        <input type="month" value={ym} onChange={(e) => setYm(e.target.value)} style={{ ...ss.inp, width: "100%", marginBottom: 14 }} />
        <button type="button" style={ss.btnP} onClick={() => printMonthlyReport(label)}>
          Print / save as PDF
        </button>
      </div>
    </div>
  );
}
