/**
 * Construction-sector hazard library extension — fills gaps from CONSTRUCTION.txt taxonomy.
 * Each row: { id, sector, category, activity, hazard, initialRisk, controlMeasures, revisedRisk, ppeRequired, regs }
 */

export const CONSTRUCTION_CATEGORIES = [
  "Site Setup & Welfare",
  "Utilities — Water & Sewer",
  "Utilities — Gas & Electric",
  "Utilities — Telecoms",
  "Plant & Machinery",
  "Highways & Streetworks",
  "Interiors & Fit-Out",
  "Energy & Renewables",
  "Marine & Aviation",
  "Environmental & Ecology",
];

const CONSTRUCTION_LIBRARY = [
  {
    id: "cst_site_001",
    sector: "construction",
    category: "Site Setup & Welfare",
    activity: "Site setup — hoarding, welfare and compound",
    hazard: "Falls from height during hoarding; manual handling injuries; trip hazards from cables; vehicle/pedestrian interface at compound entrance",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Hoarding erected by competent persons; edge protection where working at height",
      "Welfare facilities comply with CDM Schedule 2; fire points marked",
      "Cables routed overhead or protected with covers; PAT on temporary electrics",
      "Segregated pedestrian/vehicle routes; banksman for deliveries",
      "Wheel wash and dust suppression where required by local authority",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves"],
    regs: ["CDM 2015", "HASAWA 1974", "Electricity at Work Regs 1989", "Workplace (Health, Safety and Welfare) Regs 1992"],
  },
  {
    id: "cst_site_002",
    sector: "construction",
    category: "Site Setup & Welfare",
    activity: "Working in occupied / live premises",
    hazard: "Injury to occupants or public; dust and noise affecting sensitive areas; unauthorised access to work zones",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Work areas segregated with hoarding/barriers from occupied zones",
      "Agreed access routes and working hours with client/building manager",
      "Dust extraction and noise controls; negative pressure where required",
      "Daily client liaison; signage at interface points",
      "Hot work and intrusive works only with permit and client notification",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "FFP3 where dust-generating"],
    regs: ["CDM 2015", "Control of Noise Regs 2005", "COSHH 2002"],
  },
  {
    id: "cst_site_003",
    sector: "construction",
    category: "Site Setup & Welfare",
    activity: "Public interface and pedestrian management",
    hazard: "Collision with public; aggression; children entering site; falling objects onto public areas",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pedestrian routes maintained and signed; barriers prevent entry to work area",
      "Toolbox briefing on public interface; stop work if crowd gathers unsafely",
      "Toe boards and debris netting where work overhead of public routes",
      "Security or steward present during high-footfall periods if required",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear"],
    regs: ["HASAWA 1974", "CDM 2015", "Management of Health & Safety at Work Regs 1999"],
  },
  {
    id: "util_w001",
    sector: "utilities",
    category: "Utilities — Water & Sewer",
    activity: "Water main installation and pressure testing",
    hazard: "Excavation collapse; service strike; water hammer / pressure release; chlorination chemical exposure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Permit to dig; CAT/Genny and records check before excavation",
      "Pipe pressure testing to written procedure; exclusion zone during test",
      "Chlorination by trained operative; COSHH assessment for disinfectants",
      "Emergency isolation valves identified; spill kit for test water",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves", "Safety glasses"],
    regs: ["Water Supply (Water Fittings) Regs 1999", "HSG47", "COSHH 2002", "CDM 2015"],
  },
  {
    id: "util_w002",
    sector: "utilities",
    category: "Utilities — Water & Sewer",
    activity: "Sewer jetting, CCTV survey and manhole works",
    hazard: "Confined space; biological hazards; high-pressure injection injury; traffic at chamber; hydrogen sulphide",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Confined space permit where entry required; atmosphere testing before entry",
      "HPWJ pressures set to procedure; hose inspection and exclusion zone",
      "Traffic management (Chapter 8) at carriageway chambers",
      "Welfare/hygiene controls after sewage contact; vaccinations per company policy",
      "Standby person and rescue plan for any chamber entry",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves (nitrile)", "Face shield", "RPE if H2S risk"],
    regs: ["Confined Spaces Regs 1997", "COSHH 2002", "HSG185", "Chapter 8 / NRSWA"],
  },
  {
    id: "util_g001",
    sector: "utilities",
    category: "Utilities — Gas & Electric",
    activity: "Gas main installation, purging and pressure testing",
    hazard: "Fire/explosion from gas release; excavation collapse; strike on live services",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Gas Safe registered engineer for live gas work; isolation and purge procedure",
      "No hot works during purge; gas detector continuous monitoring",
      "Excavation under permit-to-dig with utility records",
      "Emergency services and network operator contacts displayed",
    ],
    revisedRisk: { L: 1, S: 6, RF: 6 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Anti-static footwear where required", "Gloves"],
    regs: ["Gas Safety (Installation & Use) Regs 1998", "HSG47", "DSEAR 2002", "CDM 2015"],
  },
  {
    id: "util_e001",
    sector: "utilities",
    category: "Utilities — Gas & Electric",
    activity: "HV cable jointing and substation works",
    hazard: "Electrocution; arc flash; fire; manual handling of heavy cables",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Authorised person / SAP scheme compliance for HV work",
      "Arc flash boundary assessed; appropriate PPE (HRC rated where required)",
      "Underground cable identification and proving dead before work",
      "Exclusion zone; only competent jointers on HV terminations",
    ],
    revisedRisk: { L: 1, S: 6, RF: 6 },
    ppeRequired: ["Hard hat", "Arc-rated clothing where assessed", "Insulated gloves", "Safety footwear"],
    regs: ["Electricity at Work Regs 1989", "HSG85", "HSG47", "CDM 2015"],
  },
  {
    id: "util_e002",
    sector: "utilities",
    category: "Utilities — Gas & Electric",
    activity: "Overhead power lines and proximity works",
    hazard: "Electrocution from contact or flashover; plant boom encroachment; falling cables",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Minimum approach distances per HSE GS6; lookout/banksman for plant",
      "Network operator notified; lines identified on site induction",
      "Goal posts or barriers where working beneath OHPL",
      "No plant boom within exclusion zone without written authority and supervision",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Insulated gloves where applicable"],
    regs: ["Electricity at Work Regs 1989", "HSE GS6 (Avoidance of danger from OHPL)", "HASAWA 1974"],
  },
  {
    id: "util_t001",
    sector: "utilities",
    category: "Utilities — Telecoms",
    activity: "Fibre blowing, splicing and chamber installation",
    hazard: "Confined chamber; traffic at roadside chambers; fibre dust; manual handling drums",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Chamber entry under confined space assessment; forced ventilation where needed",
      "Chapter 8 TM at roadside works; signing and lighting",
      "Fibre off-cuts disposed in sharps containers; no skin contact with uncured resin",
      "Drum handling aids; two-person lift over 25 kg",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves", "Safety glasses"],
    regs: ["Confined Spaces Regs 1997", "NRSWA / Chapter 8", "Manual Handling Ops Regs 1992"],
  },
  {
    id: "plant_001",
    sector: "construction",
    category: "Plant & Machinery",
    activity: "Excavator / 360° tracked plant operation",
    hazard: "Strike on buried services; rollover on slopes; pedestrian collision; falling load from bucket",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "CPCS/NPORS card verified; daily plant checks recorded",
      "Permit to dig and utility marks before digging bucket work",
      "Exclusion zone around slewing plant; banksman when pedestrians present",
      "Seat belt worn; no passengers; no lifting persons in bucket unless designed",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Hearing protection"],
    regs: ["PUWER 1998", "HSG47", "CDM 2015", "HASAWA 1974"],
  },
  {
    id: "plant_002",
    sector: "construction",
    category: "Plant & Machinery",
    activity: "Telehandler / forklift / FLT operation",
    hazard: "Pedestrian strike; load falling; tip-over; visibility blind spots",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Operator trained (ITSSAR/CPCS/NPORS); daily inspection checklist",
      "Segregated pedestrian routes; speed limits in compound",
      "Loads secured and within SWL; no elevated travel with raised load unless allowed",
      "Banksman used when reversing with restricted visibility",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "High-visibility vest"],
    regs: ["PUWER 1998", "LOLER 1998 (lifting attachments)", "HASAWA 1974"],
  },
  {
    id: "plant_003",
    sector: "construction",
    category: "Plant & Machinery",
    activity: "Banksman / vehicle marshaller duties",
    hazard: "Struck by reversing vehicle; miscommunication signals; standing in crush zone",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Banksman trained and authorised; agreed hand signals or radio protocol",
      "Banksman visible (hi-vis) and positioned to see driver and hazard area",
      "Never stand between vehicle and fixed object; maintain escape route",
      "One banksman per vehicle movement unless agreed procedure for complex lifts",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis (Class 3)", "Safety footwear", "Gloves"],
    regs: ["HASAWA 1974", "HSG150", "CDM 2015"],
  },
  {
    id: "plant_004",
    sector: "construction",
    category: "Plant & Machinery",
    activity: "Fuel storage and refuelling on site",
    hazard: "Fire/explosion; environmental spill; slip on diesel; static ignition",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Bunded storage; no smoking within 10 m; spill kit at fuel point",
      "Static earth bonding during transfer; fire extinguisher suitable for Class B",
      "Drip trays under plant during refuel; absorbent available",
      "COSHH/SDS for diesel; report spills per environmental procedure",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Safety footwear", "Gloves (fuel-resistant)", "Hi-vis"],
    regs: ["DSEAR 2002", "COSHH 2002", "Environmental Protection Act 1990", "CDM 2015"],
  },
  {
    id: "hwy_001",
    sector: "highways",
    category: "Highways & Streetworks",
    activity: "Lane closure and temporary traffic management",
    hazard: "Worker struck by live traffic; public entering closure; inadequate signing",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "TM plan designed per Chapter 8; NRSWA notice where required",
      "Only trained operatives (NHSS12A/B or equivalent) deploy signing",
      "Minimum PPE: hi-vis Class 2/3 per speed limit; recovery area defined",
      "Works vehicle coning and lighting; TM checked after setup and hourly",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear", "Gloves"],
    regs: ["NRSWA 1991", "Chapter 8 Traffic Signs Manual", "Safety at Street Works CoP", "CDM 2015"],
  },
  {
    id: "hwy_002",
    sector: "highways",
    category: "Highways & Streetworks",
    activity: "Surfacing / tarmac / hot materials",
    hazard: "Burns from hot bitumen; fume inhalation; struck by roller or paver; fire",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "PPE: long sleeves, gauntlets, safety boots; face shield when handling hot material",
      "Fume exposure minimised; RPE where occupational hygiene requires",
      "Exclusion zones around paver and roller; banksman for reversing plant",
      "Fire extinguisher at laydown; no smoking in fume zone",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Heat-resistant gauntlets", "Safety boots", "Safety glasses"],
    regs: ["COSHH 2002", "Control of Substances Hazardous to Health (asphalt fumes)", "PUWER 1998"],
  },
  {
    id: "int_001",
    sector: "construction",
    category: "Interiors & Fit-Out",
    activity: "Drylining, partitions and ceiling grid",
    hazard: "Manual handling of boards; dust (silica/gypsum); work at height on steps; cuts from sharp edges",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Mechanical aids for board delivery; team lift over 25 kg",
      "Dust extraction on cutting; vacuum or wet cut where practicable",
      "Podium/tower scaffold for ceiling work — not standing on top rung of ladder",
      "Cut-resistant gloves; safety knives with retractable blades",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Gloves", "Safety glasses", "FFP3 when cutting"],
    regs: ["COSHH 2002", "Work at Height Regs 2005", "Manual Handling Ops Regs 1992"],
  },
  {
    id: "int_002",
    sector: "construction",
    category: "Interiors & Fit-Out",
    activity: "Kitchen / washroom installation",
    hazard: "Manual handling of units; silica from tile cutting; water slip hazards; lone working",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Two-person lift for heavy units; trolley for appliances",
      "Wet cutting or extraction for tiles; RPE FFP3 for silica tasks",
      "Electrical isolation before connection; gas work by Gas Safe only",
      "Check-in procedure if lone working in occupied building",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Gloves", "FFP3 for cutting", "Knee pads"],
    regs: ["Manual Handling Ops Regs 1992", "COSHH 2002", "Electricity at Work Regs 1989"],
  },
  {
    id: "enr_001",
    sector: "energy",
    category: "Energy & Renewables",
    activity: "Solar PV installation (roof and ground-mount)",
    hazard: "Falls from roof; manual handling of panels; DC electrical shock; weather exposure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Roof access via MEWP or scaffold with edge protection; harness where residual fall risk",
      "MCS/NICEIC competent installer; DC isolators and lock-off before work",
      "Panels transported with mechanical aids; no carry up ladder",
      "Works stopped in high wind/lightning per procedure",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Harness and lanyard (where required)", "Safety footwear", "Insulated gloves", "Hi-vis"],
    regs: ["Work at Height Regs 2005", "Electricity at Work Regs 1989", "MCS standards", "CDM 2015"],
  },
  {
    id: "enr_002",
    sector: "energy",
    category: "Energy & Renewables",
    activity: "Battery energy storage (BESS) installation",
    hazard: "Electrical shock; thermal runaway/fire; heavy module handling; confined container",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Manufacturer install procedure followed; isolation and lock-off",
      "Fire detection/suppression per design; no hot works in container",
      "Lifting plan for modules; exclusion zone during crane ops",
      "Emergency response plan for battery incident communicated to team",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Insulated gloves", "Safety glasses"],
    regs: ["Electricity at Work Regs 1989", "DSEAR 2002", "LOLER 1998", "CDM 2015"],
  },
  {
    id: "env_001",
    sector: "environmental",
    category: "Environmental & Ecology",
    activity: "Arboriculture / tree surgery and vegetation clearance",
    hazard: "Falling branches; chainsaw cuts; contact with overhead lines; public beneath work area",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "LANTRA/NPTC qualified chainsaw operative; climbing kit inspected",
      "Exclusion zone beneath drop zone; road closure if needed",
      "OHPL identified before work; network operator consulted",
      "Wildlife/ecology survey completed where legally required before clearance",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Chainsaw helmet with visor and ear defenders", "Chainsaw trousers", "Safety boots", "Gloves"],
    regs: ["HASAWA 1974", "HSE GS6", "Wildlife & Countryside Act 1981 (where applicable)"],
  },
  {
    id: "env_002",
    sector: "environmental",
    category: "Environmental & Ecology",
    activity: "Contaminated land / soil sampling / boreholes",
    hazard: "Chemical/biological exposure; manual handling; plant strike; vapour inhalation",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Desk study and site investigation report reviewed before intrusive works",
      "RPE and gloves matched to contaminant; dermal protection plan",
      "Decontamination unit where required; waste classified and consigned",
      "Permit to dig; monitoring for vapours in hot weather",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Chemical gloves", "RPE per COSHH"],
    regs: ["COSHH 2002", "Environmental Protection Act 1990", "HSG248 (Contaminated Land)", "CDM 2015"],
  },
  {
    id: "cst_mar_001",
    sector: "marine",
    category: "Marine & Aviation",
    activity: "Marine / quayside civils and diving interface",
    hazard: "Falling into water; drowning; tidal movement; diving operations interface; manual handling",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Life jacket/PFD where working over water; rescue boat/cover agreed",
      "Diving operations under HSE ACOP; no surface work over active dive zone",
      "Tide and weather limits in method statement; slip hazard controls",
      "Marine-specific induction from harbour authority",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Life jacket/PFD", "Gloves"],
    regs: ["Diving at Work Regs 1997", "HASAWA 1974", "CDM 2015", "Port safety rules"],
  },
  {
    id: "cst_avi_001",
    sector: "aviation",
    category: "Marine & Aviation",
    activity: "Airside construction and maintenance",
    hazard: "Aircraft movement; jet blast; FOD; restricted area breach; work at height on masts",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Airside pass and induction; escort where required",
      "FOD checks before and after shift; tools tethered at height",
      "Works coordinated with ATC/airport ops; no unauthorised entry to movement area",
      "Permit to work airside; fire-rated PPE where fuel zone",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis (airport standard)", "Safety footwear", "Hearing protection"],
    regs: ["HASAWA 1974", "Aviation Security Regs", "Airport authority safety rules", "CDM 2015"],
  },
  {
    id: "ind_001",
    sector: "industrial",
    category: "Plant & Machinery",
    activity: "Factory shutdown — isolation and dismantling",
    hazard: "Unexpected energisation; residual pressure; confined space; simultaneous operations",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Shutdown plan with isolation register; LOTO on all energy sources",
      "SIMOPS review before parallel tasks; permit coordination",
      "Zero-energy verification before dismantling; depressurise and drain",
      "Competent supervisor present throughout shutdown window",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves", "Safety glasses"],
    regs: ["HASAWA 1974", "PUWER 1998", "Confined Spaces Regs 1997", "CDM 2015"],
  },
  {
    id: "ind_002",
    sector: "industrial",
    category: "Plant & Machinery",
    activity: "Crane lift / critical lift planning",
    hazard: "Load drop; crane overturn; struck by load; contact with overhead obstacles",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Lift plan by appointed person; LOLER thorough examination in date",
      "Exclusion zone under load; tag lines to control swing",
      "Ground conditions assessed; outriggers fully deployed on pads",
      "Slinger/signaller CPCS/NPORS verified; radio communication agreed",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves"],
    regs: ["LOLER 1998", "BS 7121 (Safe Use of Cranes)", "CDM 2015", "HASAWA 1974"],
  },
];

export default CONSTRUCTION_LIBRARY;
