/**
 * Site-context hazard rows for surveying RAMS overlays
 * (treatment works, substation/HV, rail, highway TM, brownfield).
 */

export const SITE_CONTEXT_CATEGORIES = [
  "Site context — Treatment works",
  "Site context — Substation / HV",
  "Site context — Rail corridor",
  "Site context — Highway / TM",
  "Site context — Brownfield",
];

const SITE_CONTEXT_LIBRARY = [
  {
    id: "site_ctx_001",
    sector: "surveying",
    category: "Site context — Treatment works",
    activity: "Survey within WWTW / treatment works / pumping station",
    hazard: "H₂S, chlorine or methane exposure; slip into open channels; contact with process chemicals; live plant SIMOPS",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Pre-start: client induction and escort; confirm process isolation / no-go zones",
      "During: personal gas monitor (H₂S / O₂ / LEL) worn and bump-tested; alarm = evacuate upwind",
      "Hold point: no wet-well or deep chamber entry without confined-space permit and rescue plan",
      "Stay clear of open channels, weirs and chemical dosing; barriers where covers lifted",
      "Close-out: hygiene wash-down; report odours or alarms to client controller",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Gas monitor", "Eye protection"],
    regs: ["HASAWA 1974", "COSHH 2002", "Confined Spaces Regs 1997", "CDM 2015"],
    permitTypes: ["confined_space", "general"],
    requiredCerts: ["Client site induction", "Gas monitor competence", "Confined space awareness"],
  },
  {
    id: "site_ctx_002",
    sector: "surveying",
    category: "Site context — Treatment works",
    activity: "Chamber / wet-well interface at treatment works",
    hazard: "Atmosphere change on cover lift; biological contamination; unsupervised open cover",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: cordon chamber; monitor atmosphere at cover before and during opening",
      "During: one person lifts; second person banks; cover never left open unsupervised",
      "Hold point: stop if alarm or unusual odour; reinstate cover",
      "Hygiene: avoid hand-to-face; wash after chamber work",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Gas monitor"],
    regs: ["HASAWA 1974", "COSHH 2002", "Confined Spaces Regs 1997"],
    permitTypes: ["confined_space"],
    requiredCerts: ["Confined space awareness"],
  },
  {
    id: "site_ctx_003",
    sector: "surveying",
    category: "Site context — Substation / HV",
    activity: "Survey inside substation / HV compound",
    hazard: "Contact with live HV apparatus; induced voltage; unauthorised zone entry; arc flash proximity",
    initialRisk: { L: 3, S: 6, RF: 18 },
    controlMeasures: [
      "Pre-start: authorised person / electrical escort briefing; stay on marked safe routes only",
      "During: no climbing fences, apparatus or structures; no metallic poles near live plant without AP approval",
      "Hold point: AP confirms work zone before first setup",
      "Emergency: know compound muster and electrical emergency contacts",
    ],
    revisedRisk: { L: 1, S: 6, RF: 6 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Eye protection"],
    regs: ["HASAWA 1974", "EAWR 1989", "CDM 2015"],
    permitTypes: ["electrical_isolation", "general"],
    requiredCerts: ["Substation / HV induction", "Electrical safety awareness"],
  },
  {
    id: "site_ctx_004",
    sector: "surveying",
    category: "Site context — Substation / HV",
    activity: "GNSS / UAV / EML near live HV plant",
    hazard: "EMI degrading GNSS / UAV control / EML signals; loss of positioning accuracy; unexpected flight behaviour",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: plan alternate control (total station) if GNSS unreliable near HV",
      "During: UAV only with AP agreement and EMI contingency; visual observer mandatory",
      "Hold point: abort UAV if control link unstable; land immediately in safe zone",
      "Document residual uncertainty where EMI affects utility detect confidence",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear"],
    regs: ["HASAWA 1974", "CAA UAS regulations", "CDM 2015"],
    permitTypes: ["aerial_survey_coordination", "general"],
    requiredCerts: ["CAA A2 CofC or GVC (UAV)", "Substation induction"],
  },
  {
    id: "site_ctx_005",
    sector: "surveying",
    category: "Site context — Rail corridor",
    activity: "Trackside / rail corridor survey under SSOW",
    hazard: "Train strike; red-zone encroachment; possession overrun; lone working trackside",
    initialRisk: { L: 3, S: 6, RF: 18 },
    controlMeasures: [
      "Pre-start: PTS cards checked; COSS / SWL briefing; possession or SSOW window confirmed",
      "During: stay in authorised green zone / separated area; obey lookout / warning systems",
      "Hold point: no work if SSOW not in place or radio fails",
      "Close-out: handback complete; all kit and persons clear of running line",
    ],
    revisedRisk: { L: 1, S: 6, RF: 6 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3 (orange)", "Safety footwear", "Gloves"],
    regs: ["HASAWA 1974", "Railway safety rules", "CDM 2015"],
    permitTypes: ["rail_corridor_access"],
    requiredCerts: ["PTS", "COSS / SWL briefing"],
  },
  {
    id: "site_ctx_006",
    sector: "surveying",
    category: "Site context — Rail corridor",
    activity: "Survey equipment setup trackside",
    hazard: "Tripod / GPR / cables fouling running line or walkway; manual handling in restricted width",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Pre-start: kit layout planned inside authorised zone only",
      "During: no cables across running line or walkways; spotter when moving kit",
      "Hold point: COSS confirms setup position before first observation",
      "Secure kit against vibration / wake; never leave kit unattended trackside",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear", "Gloves"],
    regs: ["HASAWA 1974", "Manual Handling Regs 1992", "Railway safety rules"],
    permitTypes: ["rail_corridor_access"],
    requiredCerts: ["PTS"],
  },
  {
    id: "site_ctx_007",
    sector: "surveying",
    category: "Site context — Highway / TM",
    activity: "Survey / GPR / topo on live carriageway or verge",
    hazard: "Struck by vehicle; public collision; working outside TM layout; tripod in live lane",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Pre-start: Chapter 8 TM layout approved and erected before work starts",
      "During: face traffic; hi-vis Class 3; banksman for vehicle-mounted arrays and lane edge setups",
      "Hold point: no work if TM incomplete or weather reduces visibility below safe limits",
      "Close-out: remove TM; reopen carriageway; leave no kit or cones behind",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear", "Gloves"],
    regs: ["HASAWA 1974", "Traffic Signs Manual Chapter 8", "CDM 2015"],
    permitTypes: ["temporary_traffic_management", "night_works"],
    requiredCerts: ["Chapter 8 / TM awareness", "Banksman awareness"],
  },
  {
    id: "site_ctx_008",
    sector: "surveying",
    category: "Site context — Highway / TM",
    activity: "Pedestrian interface during highway survey",
    hazard: "Pedestrian diverted into live traffic; trip on survey kit; public access to open chambers",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: maintain or divert pedestrian routes with clear signing",
      "During: barriers around open chambers and tripods; spotter at busy interfaces",
      "Hold point: reinstate covers before leaving position",
      "Brief public interface stop-work if crowding or aggression",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear"],
    regs: ["HASAWA 1974", "Traffic Signs Manual Chapter 8"],
    permitTypes: ["temporary_traffic_management"],
    requiredCerts: ["Chapter 8 / TM awareness"],
  },
  {
    id: "site_ctx_009",
    sector: "surveying",
    category: "Site context — Brownfield",
    activity: "Survey on brownfield / contaminated / made ground",
    hazard: "Contact with contaminated soils; asbestos in made ground; VOC / ground gas; unexpected UXO indicators",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Pre-start: desk study briefing — contamination status, asbestos and UXO caveats",
      "During: minimise soil contact; gloves; no eating/drinking in work zone; RPE as assessed",
      "Hold point: stop-work on unexpected odour, sheen, ACM-suspect material or UXO indicators — escalate to client",
      "Close-out: decontaminate boots and kit; bag waste separately",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "RPE as assessed", "Eye protection"],
    regs: ["HASAWA 1974", "COSHH 2002", "CAR 2012", "CDM 2015"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Asbestos awareness (where indicated)", "Contamination hygiene briefing"],
  },
  {
    id: "site_ctx_010",
    sector: "surveying",
    category: "Site context — Brownfield",
    activity: "Intrusive verification / trial hole on brownfield",
    hazard: "Service strike in contaminated ground; exposure pathway via spoil; cross-contamination off site",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Pre-start: permit-to-dig and utility clearance marks verified",
      "During: hand-dig / NDD in tolerance zones; contain spoil; no uncontrolled stockpiles",
      "Hold point: photo evidence of exposed services before backfill",
      "Close-out: reinstate; decontaminate tools; chain-of-custody for samples if taken",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Eye protection"],
    regs: ["HASAWA 1974", "COSHH 2002", "CDM 2015"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Permit-to-dig competence", "Contamination hygiene briefing"],
  },
];

export default SITE_CONTEXT_LIBRARY;
