/**
 * RAMS hazard library supplement — Tier A/B gaps (plant, confined space, timber, night works, FESS line clearance).
 * Merged in ramsAllHazards.js after construction extension.
 */

export const SUPPLEMENT_CATEGORIES = [
  "Night Works",
  "Confined Space & Tank Entry",
  "Timber Frame & Carpentry",
  "Insulation & Passive Fire",
  "Food Line Clearance",
  "Wind Energy Service",
];

const SUPPLEMENT_LIBRARY = [
  {
    id: "cst_night_001",
    sector: "construction",
    category: "Night Works",
    activity: "Night working — general construction (non-highway)",
    hazard: "Reduced visibility; fatigue; lone working; inadequate lighting; public entering work zone",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Pre-start: site lighting plan; emergency lighting at access routes; TM/signage illuminated",
      "During: Class 3 hi-vis; supervisor on site; lone working prohibited unless agreed procedure",
      "Hold point: lighting check signed before work starts",
      "Fatigue management — max consecutive night shifts per Working Time Regs",
      "Close-out: barriers and lighting left safe for public until handback",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Class 3 hi-vis", "Hard hat", "Safety footwear", "Gloves (reflective)", "Head torch"],
    regs: ["HASAWA 1974", "Working Time Regs 1998", "HSG191", "CDM 2015"],
    permitTypes: ["work_at_height", "hot_work", "excavation"],
    requiredCerts: ["Supervisor competence", "First aid cover on site"],
  },
  {
    id: "cst_conf_002",
    sector: "construction",
    category: "Confined Space & Tank Entry",
    activity: "Tank / vessel cleaning and industrial confined entry",
    hazard: "Toxic atmosphere; engulfment; oxygen deficiency; rescue delay; chemical residue",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Pre-start: confined space entry permit; isolation and purge; rescue team briefed",
      "During: continuous gas monitoring (O2, LEL, H2S, CO); top-man never leaves post",
      "Hold point: atmospheric test recorded before entry — no entry if fail",
      "No lone entry; communication maintained with top-man",
      "Close-out: permit closed; area secured; waste disposed per COSHH",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Breathing apparatus (as per assessment)", "Chemical-resistant suit", "Harness", "Gas monitor"],
    regs: ["Confined Spaces Regs 1997", "L101 ACOP", "COSHH 2002", "CDM 2015"],
    permitTypes: ["confined_space"],
    requiredCerts: ["Confined space entry", "Gas monitor competence", "Rescue standby competence"],
  },
  {
    id: "plant_005",
    sector: "construction",
    category: "Plant & Machinery",
    activity: "Dumper, roller and compaction plant",
    hazard: "Rollover on slopes; pedestrian strike; edge collapse; reversing incidents",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Operator CPCS/NPORS; seat belt worn; no passengers",
      "Banksman for reversing near pedestrians; exclusion zones marked",
      "Edge protection near trenches; no tipping into unsupported edges",
      "Daily plant checks; rollover protection in place",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear", "Hearing protection"],
    regs: ["PUWER 1998", "HSG150", "CDM 2015"],
    permitTypes: ["excavation"],
    requiredCerts: ["CPCS/NPORS plant operator", "Banksman training"],
  },
  {
    id: "cst_timber_001",
    sector: "construction",
    category: "Timber Frame & Carpentry",
    activity: "Timber frame panel erection and bracing",
    hazard: "Falls from height; crush during lift; unstable frame before bracing; wind loading",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Lift plan for panel erection; exclusion zone under load",
      "Temporary bracing installed per manufacturer sequence before releasing crane",
      "Work suspended when wind exceeds manufacturer limit (typically 10–15 m/s)",
      "Edge protection and harness where fall risk remains",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Harness (where required)", "Safety footwear", "Hi-vis", "Gloves"],
    regs: ["CDM 2015", "Work at Height Regs 2005", "LOLER 1998", "BS 8100 (temporary bracing)"],
    permitTypes: ["work_at_height", "lifting_ops"],
    requiredCerts: ["CPCS slinger/signaller", "Timber frame erection training"],
  },
  {
    id: "cst_timber_002",
    sector: "construction",
    category: "Timber Frame & Carpentry",
    activity: "Nail gun / carpentry fix-out and silica-generating cuts",
    hazard: "Nail gun misfire injury; silica dust from cutting; manual handling; WAH on ladders",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Sequential trigger nail guns only; tool training and daily inspection",
      "On-tool extraction or wet cutting for silica; FFP3 where required",
      "Ladders for short duration light work only; prefer tower/MEWP",
      "Finger guards and safe trigger discipline — no bump firing",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "FFP3 (silica tasks)", "Safety footwear", "Eye protection", "Hearing protection"],
    regs: ["COSHH 2002", "HSG150", "Work at Height Regs 2005", "HASAWA 1974"],
    permitTypes: ["work_at_height"],
    requiredCerts: ["CSCS carpentry", "Nail gun training"],
  },
  {
    id: "cst_insul_001",
    sector: "construction",
    category: "Insulation & Passive Fire",
    activity: "Spray foam / cavity insulation application",
    hazard: "Isocyanate exposure; off-gas in enclosed spaces; fire during curing; WAH in lofts",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "COSHH assessment for isocyanates; RPE with appropriate filters",
      "Ventilation during and after application; occupancy restrictions until cured",
      "No hot works until clearance time elapsed",
      "Loft work: boards to prevent fall through ceiling; lighting and buddy system",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Full-face RPE (isocyanate)", "Disposable coveralls", "Gloves", "Safety footwear"],
    regs: ["COSHH 2002", "EH40 WEL (isocyanates)", "Work at Height Regs 2005"],
    permitTypes: ["work_at_height", "hot_work"],
    requiredCerts: ["Spray foam installer certification", "COSHH awareness"],
  },
  {
    id: "cst_wind_001",
    sector: "energy",
    category: "Wind Energy Service",
    activity: "Wind turbine tower climbing and nacelle service",
    hazard: "Fall from height; dropped objects; arc flash in nacelle; lone working; weather",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "GWO BST modules current; rescue from height plan in place",
      "Works stopped above Beaufort/wind limits per OEM",
      "Tool tethering; exclusion zone at tower base",
      "Electrical isolation and LOTO before nacelle work",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Harness and twin lanyards", "Hard hat", "Safety footwear", "Hi-vis", "Rescue harness"],
    regs: ["Work at Height Regs 2005", "Electricity at Work Regs 1989", "HASAWA 1974", "GWO standards"],
    permitTypes: ["work_at_height", "electrical_isolation"],
    requiredCerts: ["GWO Working at Heights", "GWO First Aid", "GWO Manual Handling"],
  },
  {
    id: "cst_food_lc_001",
    sector: "food_pharma",
    category: "Food Line Clearance",
    activity: "Production line clearance and allergen isolation",
    hazard: "Cross-contamination; product left in line; wrong restart; foreign body from tools",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Line clearance checklist signed by production and maintenance",
      "Physical isolation or lock-off of product flow; allergen zone briefing",
      "Magnetic sweep and visual inspection before restart",
      "Hold point: QA/production sign-off before re-energise",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Zone-specific hygiene PPE", "Gloves"],
    regs: ["Food Safety Act 1990", "BRCGS / SALSA (where applicable)", "HASAWA 1974", "CDM 2015"],
    permitTypes: ["line_clearance"],
    requiredCerts: ["Food hygiene induction", "Allergen awareness"],
  },
  {
    id: "cst_food_cip_001",
    sector: "food_pharma",
    category: "Food Line Clearance",
    activity: "CIP chemical clean and hygiene shutdown",
    hazard: "Chemical burn from caustic/acid; slip on wet floors; confined vessel entry; pressure release",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "COSHH/SDS for CIP chemicals; chemical-resistant PPE",
      "Pressure released before opening vessels; LOTO on pumps",
      "Confined space assessment if vessel entry required",
      "Slip controls and drainage during wet cleaning",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Chemical apron", "Face shield", "Chemical gloves", "Safety footwear (slip-resistant)"],
    regs: ["COSHH 2002", "Food Hygiene Regs", "Confined Spaces Regs 1997"],
    permitTypes: ["confined_space", "line_clearance"],
    requiredCerts: ["CIP operator training", "Food hygiene"],
  },
  {
    id: "cst_pil_002",
    sector: "construction",
    category: "Piling & Ground Improvement",
    activity: "Post-tensioning and stressing operations",
    hazard: "Sudden release of stored energy; strand snap; struck by jack; manual handling",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Only PTIA-competent operatives; exclusion zone during stressing",
      "Equipment inspected; gauge calibration in date",
      "Stressing sequence per engineer's design; hold points recorded",
      "Never stand in line of strand/jack during tensioning",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Eye protection", "Hi-vis", "Gloves"],
    regs: ["CDM 2015", "HASAWA 1974", "PTIA guidance", "BS EN 1992 (concrete structures)"],
    permitTypes: ["excavation"],
    requiredCerts: ["PT stressing competence", "Supervisor briefing"],
  },
];

export default SUPPLEMENT_LIBRARY;
