/**
 * Geospatial hazard library — aerial, hydrographic, laser scan, tunnel, mining, AS5488.
 */

export const GEOSPATIAL_CATEGORIES = [
  "Aerial Survey & LiDAR",
  "Hydrographic & Marine Survey",
  "Laser Scanning & Digital Twin",
  "Tunnel & Mobile Mapping",
  "Mining & Resources Survey",
  "Structural & Dam Monitoring",
  "AS5488 Utility Intelligence",
];

const GEOSPATIAL_LIBRARY = [
  {
    id: "geo_aerial_001",
    sector: "surveying",
    category: "Aerial Survey & LiDAR",
    activity: "Helicopter / fixed-wing aerial imagery and LiDAR capture",
    hazard: "Low-level flight interface; rotor downwash; public overflight; fuel handling; crew WAH on aircraft",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-start: flight plan, NOTAM/CAA coordination and landowner notifications complete",
      "During: exclusion zone under flight path; banksman for ground crew",
      "Hold point: pilot + survey lead sign-off before first pass",
      "Fuel and battery ops per COSHH/DSEAR; fire extinguisher at landing site",
      "Close-out: equipment secured; public realm re-opened",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Hearing protection", "Safety footwear", "Eye protection"],
    regs: ["HASAWA 1974", "CAA regulations", "COSHH 2002", "CDM 2015"],
    permitTypes: ["aerial_survey_coordination", "night_works"],
    requiredCerts: ["Aerial survey crew induction", "Fuel handling awareness"],
  },
  {
    id: "geo_aerial_002",
    sector: "surveying",
    category: "Aerial Survey & LiDAR",
    activity: "UAV / drone survey (topo, corridor, asset inspection)",
    hazard: "Public strike; loss of control; OHPL proximity; battery fire; privacy/data breach",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: CAA operator ID, fly zone assessment, weather limits",
      "During: visual observer; max 120m AGL unless authorised; no overflight of crowds",
      "Hold point: pre-flight checklist and airspace clearance",
      "Emergency landing area identified; battery fire kit available",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear"],
    regs: ["CAA CAP722 / UAS regulations", "HASAWA 1974", "GDPR (imagery)"],
    permitTypes: ["aerial_survey_coordination"],
    requiredCerts: ["CAA A2 CofC or GVC", "PfCO legacy where applicable"],
  },
  {
    id: "geo_hydro_001",
    sector: "surveying",
    category: "Hydrographic & Marine Survey",
    activity: "Hydrographic / bathymetric survey from vessel or RHIB",
    hazard: "Man overboard; collision; tidal/current; hypothermia; equipment overboard; lone working",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-start: marine risk assessment; MOB drill; life jacket/PFD mandatory on deck",
      "During: competent coxswain; weather/tide limits in method statement",
      "Hold point: harbour/master notification where required",
      "Rescue plan and shore contact; no lone person on deck during mobilisation",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["PFD/life jacket", "Hard hat", "Safety footwear (non-slip)", "Hi-vis", "Thermal layer"],
    regs: ["HASAWA 1974", "Merchant Shipping Act", "Port safety rules", "CDM 2015"],
    permitTypes: ["marine_hydrographic"],
    requiredCerts: ["Boat master competency", "MOB training"],
  },
  {
    id: "geo_scan_001",
    sector: "surveying",
    category: "Laser Scanning & Digital Twin",
    activity: "Terrestrial laser scanning (TLS) / static scan station setup",
    hazard: "Laser strike to eyes; tripod on traffic route; WAH at scan positions; manual handling of kit",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: scan exclusion zone cordoned; Class 1/2 laser briefing",
      "During: warning signage; no unauthorised entry during active scan",
      "Hold point: control network verified before scan session",
      "Trip hazard management for cables; secure scanner on slopes",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Eye protection"],
    regs: ["HASAWA 1974", "IEC 60825 (laser safety)", "Work at Height Regs 2005"],
    permitTypes: ["work_at_height", "night_works"],
    requiredCerts: ["Laser scanning operator training", "Total station/TLS competency"],
  },
  {
    id: "geo_scan_002",
    sector: "surveying",
    category: "Laser Scanning & Digital Twin",
    activity: "Mobile mapping / SLAM lidar (vehicle or backpack)",
    hazard: "Traffic interface; pedestrian strike; driver distraction; uneven ground; data capture near live plant",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: route risk assessment; TM plan if on public highway",
      "During: banksman when reversing; max speed limits for capture quality and safety",
      "Hold point: calibration and boresight check before corridor run",
      "No mobile mapping in active rail corridor without possession",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear"],
    regs: ["Chapter 8", "HASAWA 1974", "CDM 2015"],
    permitTypes: ["night_works"],
    requiredCerts: ["Mobile mapping system training"],
  },
  {
    id: "geo_tunnel_001",
    sector: "surveying",
    category: "Tunnel & Mobile Mapping",
    activity: "Tunnel condition scan / mobile mapping in confined corridor",
    hazard: "Confined atmosphere; rail strike; poor ventilation; trip hazards; lone working; moving plant",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Pre-start: confined space/rail access permit; gas test where required",
      "During: comms with control room; exclusion of rail traffic unless possession",
      "Hold point: ventilation and lighting verified",
      "Escape route walk-through before scan; no lone working",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Harness (where fall risk)", "Respirator (dust)", "Safety footwear"],
    regs: ["Confined Spaces Regs 1997", "RISQS / rail safety", "HASAWA 1974"],
    permitTypes: ["confined_space", "rail_corridor_access"],
    requiredCerts: ["PTS (rail)", "Confined space awareness", "Tunnel scan system training"],
  },
  {
    id: "geo_util_as5488_001",
    sector: "surveying",
    category: "AS5488 Utility Intelligence",
    activity: "AS5488 / PAS128 subsurface utility mapping with GPR, EM and NDD verification",
    hazard: "Utility strike during verification; chamber entry; traffic; incorrect QL assignment; data mis-issue",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-start: utility records search; permit-to-dig for NDD/trial holes",
      "During: EM + GPR cross-check; hand-dig within tolerance zones",
      "Hold point: QL assignment peer review before issue",
      "Deliverables include residual uncertainty and safe dig rules",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Harness (chamber)"],
    regs: ["PAS 128:2022", "AS 5488 (AU)", "HSG47", "Confined Spaces Regs 1997"],
    permitTypes: ["excavation", "confined_space"],
    requiredCerts: ["CAT/Genny competence", "GPR operator", "NDD/vacuum excavation awareness"],
  },
  {
    id: "geo_pave_001",
    sector: "surveying",
    category: "AS5488 Utility Intelligence",
    activity: "3D GPR pavement / asphalt utility scan",
    hazard: "Traffic interface; moving plant; public interface; heat stress on carriageway",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: Chapter 8 TM or lane closure; scan vehicle banksman",
      "During: exclusion behind scan vehicle; max scan speed per spec",
      "Hold point: calibration plate check before corridor run",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Class 3 hi-vis", "Hard hat", "Safety footwear", "Sun protection"],
    regs: ["Chapter 8", "PAS 128:2022", "HASAWA 1974"],
    permitTypes: ["excavation"],
    requiredCerts: ["3D GPR pavement system training", "NHSS12 TM awareness"],
  },
  {
    id: "geo_mine_001",
    sector: "surveying",
    category: "Mining & Resources Survey",
    activity: "Open-pit / mine site survey and volumetrics",
    hazard: "Vehicle/plant interaction; bench edge collapse; blast window interface; dust; remote comms failure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-start: mine site induction; blast clearance protocol",
      "During: stay behind berms; radio check-in; no work under suspended loads",
      "Hold point: supervisor authorisation before entering active pit",
      "Lone working prohibited; GPS/instrument security on benches",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Dust mask", "Safety footwear", "Eye protection"],
    regs: ["Mines Regs 2014 (UK)", "HASAWA 1974", "Quarries Regs 1999"],
    permitTypes: ["visitor_access", "ground_disturbance"],
    requiredCerts: ["Mine/quarry site induction", "4WD awareness"],
  },
  {
    id: "geo_dam_001",
    sector: "surveying",
    category: "Structural & Dam Monitoring",
    activity: "Dam / structure deformation monitoring survey",
    hazard: "Working at height on dam crest; water release; remote site lone working; unstable access tracks",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-start: reservoir operating plan reviewed; client emergency contacts",
      "During: fall protection at crest edges; weather limits for access track",
      "Hold point: control network stability check before epoch",
      "Check-in/check-out for remote sites",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Harness", "Hi-vis", "Safety footwear"],
    regs: ["Reservoirs Act 1975", "Work at Height Regs 2005", "HASAWA 1974"],
    permitTypes: ["work_at_height"],
    requiredCerts: ["Monitoring survey competency", "First aid (remote)"],
  },
  {
    id: "geo_cad_001",
    sector: "surveying",
    category: "Laser Scanning & Digital Twin",
    activity: "Cadastral / boundary survey (residential & commercial lots)",
    hazard: "Public interface; dog attack; traffic on highway verge; lone working in remote lots",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: client/property access confirmed; dog/landowner notification",
      "During: hi-vis on verge; parking position risk assessed",
      "Hold point: boundary conflict flagged to client before pegging",
      "Lone worker check-in for remote parcels",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hi-vis", "Hard hat", "Safety footwear", "Dog bite awareness"],
    regs: ["HASAWA 1974", "Highways Act (verge work)", "RICS / RICS-aligned practice"],
    permitTypes: ["visitor_access"],
    requiredCerts: ["Cadastral survey competency", "Total station/GNSS"],
  },
  {
    id: "geo_dim_001",
    sector: "surveying",
    category: "Laser Scanning & Digital Twin",
    activity: "Dimensional control / deformation monitoring (3B Survey — plant, shipping, oil & gas)",
    hazard: "Working adjacent to live plant; hot surfaces; pinch points; night shift fatigue",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pre-start: client SIMOPS/PTW interface; exclusion zones from live equipment",
      "During: instrument stability; repeat measurements per control procedure",
      "Hold point: baseline epoch approved before trend analysis issued",
      "Fatigue management for night campaigns",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Eye protection", "Gloves"],
    regs: ["HASAWA 1974", "PUWER 1998", "CDM 2015"],
    permitTypes: ["cold_work", "night_works", "visitor_access"],
    requiredCerts: ["Dimensional control survey", "Client site induction"],
  },
];

export default GEOSPATIAL_LIBRARY;
