// MySafeOps — RAMS Hazard Library Extension
// Adds 12 new trade categories to ramsHazardLibrary.js
// Import alongside base library:
//   import HAZARD_LIBRARY from "./ramsHazardLibrary";
//   import EXTENDED_LIBRARY from "./ramsHazardLibraryExtended";
//   const ALL_HAZARDS = [...HAZARD_LIBRARY, ...EXTENDED_LIBRARY];

export const EXTENDED_CATEGORIES = [
  "Groundworks & Excavation",
  "Asbestos & Hazardous Materials",
  "Gas & HVAC",
  "Roofing & Waterproofing",
  "Structural Steel",
  "Demolition & Strip-out",
  "Painting, Decorating & Flooring",
  "Plumbing & Drainage",
  "Fire Protection",
  "Solar PV & EV Charging",
  "Rail & Trackside",
  "Warehousing & Logistics",
  "Traffic Management (TMP)",
  "Temporary Works Advanced",
  "Facade & Glazing",
  "Contaminated Land & Remediation",
  "Marine & Water Proximity",
  "Battery & Energy Storage",
];

const EXTENDED_LIBRARY = [

  // ── GROUNDWORKS & EXCAVATION ────────────────────────────────────────────────

  {
    id: "gnd_001",
    category: "Groundworks & Excavation",
    activity: "Excavation and trenching",
    hazard: "Collapse of excavation sides; persons falling in; services strike; spoil heap instability",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Excavation design by competent person; suitable battering, benching or shoring used",
      "Daily inspection of excavation sides by competent person; records kept",
      "Barriers and covers provided at all open excavations; edge protection minimum 1m",
      "Spoil and materials stored minimum 0.5m from excavation edge",
      "Safe means of access and egress provided (ladder every 25m max)",
      "Permit to Dig issued before any ground is broken",
      "All underground services located using CAT/Genny and service drawings before excavation",
      "Hand digging within 0.5m of identified services",
      "Rescue plan in place; emergency equipment available at excavation",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear (steel midsole)", "Hi-vis", "Gloves", "Safety glasses"],
    regs: ["Construction (Design & Management) Regs 2015", "HASAWA 1974", "HSG185 (Health & Safety in Excavations)", "PAS 128 (utility surveys)"],
  },

  {
    id: "gnd_002",
    category: "Groundworks & Excavation",
    activity: "Underground services detection and safe dig",
    hazard: "Strike on live gas, electric, water or telecoms services; electrocution; explosion; flooding",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Obtain up-to-date utility records from all relevant authorities before any excavation",
      "CAT (Cable Avoidance Tool) and Signal Generator (Genny) survey carried out; operator trained",
      "Survey results marked out on ground with paint/stakes before excavation begins",
      "Permit to Dig issued and displayed at point of work",
      "Hand dig or vacuum excavation within 0.5m of marked services",
      "Operatives trained in service strike procedures and emergency response",
      "Emergency contacts for all utility companies posted on site",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Insulated gloves (electrical strike)"],
    regs: ["HSG47 (Avoiding Danger from Underground Services)", "PAS 128:2022", "NJUG Guidelines"],
  },

  {
    id: "gnd_003",
    category: "Groundworks & Excavation",
    activity: "Piling operations",
    hazard: "Ground vibration damage to adjacent structures; noise; collision with piling rig; buried obstructions",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Vibration monitoring installed on adjacent structures before piling commences",
      "Pre-piling condition surveys of all neighbouring properties completed and recorded",
      "Exclusion zone established around piling rig; radius equal to pile depth minimum",
      "Piling rig daily pre-use checks completed by competent operator",
      "Ground investigation and UXO (unexploded ordnance) survey completed where required",
      "Noise monitoring and agreed working hours with local authority where applicable",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Hearing protection", "Safety glasses"],
    regs: ["BS EN 1997 (Eurocode 7)", "BS 5228 (Noise & Vibration from Construction)", "Control of Noise Regs 2005"],
  },

  {
    id: "gnd_004",
    category: "Groundworks & Excavation",
    activity: "Dewatering and groundwater pumping",
    hazard: "Electrical equipment near water; pump failure causing flooding; ground subsidence from over-pumping",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Only 110V or pneumatic pumping equipment used in wet excavations",
      "All electrical connections above flood level; RCD protection fitted",
      "Pump capacity matched to inflow rate; overflow contingency plan in place",
      "Dewatering design by geotechnical engineer for large-scale operations",
      "Discharge water tested and disposed of in accordance with environmental permit",
      "Excavation inspected after every pump operation for signs of instability",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Waterproof boots", "Hi-vis", "Hard hat", "Insulated gloves"],
    regs: ["Electricity at Work Regs 1989", "Environment Agency discharge consents", "BS 8004"],
  },

  // ── ASBESTOS & HAZARDOUS MATERIALS ─────────────────────────────────────────

  {
    id: "asb_001",
    category: "Asbestos & Hazardous Materials",
    activity: "Asbestos survey and inspection",
    hazard: "Inadvertent disturbance of asbestos-containing materials (ACMs); fibre release; inhalation",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Only P402-qualified surveyor (management survey) or P403/P405 (refurbishment/demolition) to conduct survey",
      "Asbestos register and management plan reviewed before any intrusive work",
      "All suspected ACMs treated as confirmed asbestos until tested",
      "No disturbance of suspected ACMs without written asbestos management plan",
      "Samples taken by licensed sampler only; analysed by UKAS-accredited laboratory",
      "Asbestos register updated and communicated to all trades on site",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["FFP3 respirator", "Disposable coveralls (Type 5/6)", "Nitrile gloves", "Safety footwear"],
    regs: ["Control of Asbestos Regs 2012 (CAR 2012)", "L143 ACOP", "HSG264", "RIDDOR 2013"],
  },

  {
    id: "asb_002",
    category: "Asbestos & Hazardous Materials",
    activity: "Non-licensed asbestos work (NNLW / SWNL)",
    hazard: "Asbestos fibre release during minor disturbance; inhalation; secondary contamination of clothing",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Work classified as non-licensed by competent person before commencement",
      "Notification to HSE required for sporadic low intensity (SWNL) work — 14 days prior",
      "Area sealed off with sheeting; negative pressure unit used for SWNL",
      "Wetting techniques used to suppress fibre release where possible",
      "All waste double-bagged in UN-approved asbestos waste sacks and labelled",
      "Decontamination unit (DCU) used; coveralls and PPE disposed as asbestos waste",
      "Health surveillance and medical records maintained for all exposed workers",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["FFP3 respirator", "Disposable coveralls (Type 5)", "Nitrile gloves", "Safety goggles"],
    regs: ["Control of Asbestos Regs 2012", "L143 ACOP", "EH10", "HSG210"],
  },

  {
    id: "asb_003",
    category: "Asbestos & Hazardous Materials",
    activity: "Lead paint disturbance and removal",
    hazard: "Lead dust and fume inhalation; skin contamination; contamination of food and water",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Survey for lead paint completed before any sanding, burning or abrasive work",
      "Where lead paint confirmed, COSHH assessment and specialist contractor engaged",
      "Containment sheeting used to prevent spread of dust",
      "Vacuum sanding equipment with HEPA filters used in preference to dry sanding",
      "No eating, drinking or smoking in lead paint work areas",
      "Hand and face washing facilities available and used before breaks and after work",
      "Air monitoring and biological monitoring where significant exposure expected",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["P3 half-face mask", "Nitrile gloves", "Coveralls", "Safety glasses"],
    regs: ["COSHH 2002", "EH40 WEL (lead: 0.15 mg/m³ TWA)", "Control of Lead at Work Regs 2002"],
  },

  {
    id: "asb_004",
    category: "Asbestos & Hazardous Materials",
    activity: "Mould remediation and biological hazard control",
    hazard: "Fungal spore inhalation; skin irritation; Legionella risk in water systems; cross-contamination",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "COSHH assessment completed; area tested for mould species before remediation",
      "Containment barriers erected; negative pressure ventilation used during removal",
      "Mould-affected materials bagged and removed in sealed bags",
      "Biocidal treatment applied by trained operative in accordance with product label",
      "All water systems at risk of Legionella risk-assessed to L8 ACOP requirements",
      "Water temperature monitoring implemented; records kept",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["FFP2/FFP3 mask", "Nitrile gloves", "Safety glasses", "Coveralls"],
    regs: ["COSHH 2002", "L8 ACOP (Legionella)", "HSG274", "Biocidal Products Regulation"],
  },

  // ── GAS & HVAC ──────────────────────────────────────────────────────────────

  {
    id: "gas_001",
    category: "Gas & HVAC",
    activity: "Gas pipe installation and purging",
    hazard: "Gas leak; explosion; CO poisoning; ignition from naked flames or sparks",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Only Gas Safe registered operatives to work on gas pipework and appliances",
      "Gas Safe registration card checked before work commences",
      "All ignition sources removed from the area during purging",
      "Gas detector (combustible gas meter) used before and during work",
      "Purging carried out to IGE/UP/1A procedures; purge volume calculated",
      "All pipework tested for soundness to BS 6891 / IGEM/UP/2 before commissioning",
      "Work area ventilated throughout; never work in a sealed space with gas",
      "Emergency isolation procedure known and communicated to all on site",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Gas-rated safety footwear", "Hi-vis", "Safety glasses", "Gloves"],
    regs: ["Gas Safety (Installation & Use) Regs 1998", "Gas Safe Register", "IGE/UP/1A", "BS 6891"],
  },

  {
    id: "gas_002",
    category: "Gas & HVAC",
    activity: "Boiler and plant room commissioning",
    hazard: "CO poisoning; explosion from gas accumulation; burns from high temperature surfaces; pressure system failure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Plant room ventilation confirmed adequate before ignition",
      "CO detector installed and functioning before commissioning",
      "All pipework, valves and fittings pressure tested before gas admission",
      "Safety valves set and tested; records made",
      "Commissioning carried out by Gas Safe registered and manufacturer-trained engineer",
      "First fire-up attended by minimum two persons",
      "High temperature surfaces lagged or guarded before handover",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Safety footwear", "Heat-resistant gloves", "Safety glasses", "Hi-vis"],
    regs: ["Gas Safety (Installation & Use) Regs 1998", "PSSR 2000", "L56 ACOP", "BS EN 12828"],
  },

  {
    id: "gas_003",
    category: "Gas & HVAC",
    activity: "Ductwork installation and cleaning",
    hazard: "Grease fire risk in kitchen ductwork; Legionella in AHU; confined space entry; falls from height",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Hot work permit issued before any work near kitchen extract ductwork",
      "Ductwork degreased before hot works in kitchen environments",
      "AHU water trays and drain pans cleaned and treated against Legionella growth",
      "Confined space entry permit for entry into large ductwork sections",
      "MEWP or scaffold used for ductwork at height; IPAF/PASMA qualifications verified",
      "Noise assessment for workers using powered duct cutting equipment",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Safety footwear", "Safety glasses", "Hearing protection", "Dust mask", "Harness (MEWP)"],
    regs: ["Work at Height Regs 2005", "Confined Spaces Regs 1997", "COSHH 2002", "L8 ACOP"],
  },

  {
    id: "gas_004",
    category: "Gas & HVAC",
    activity: "Refrigerant handling and F-Gas works",
    hazard: "Refrigerant release; asphyxiation in enclosed spaces; burns from cryogenic refrigerants; environmental pollution",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Only F-Gas certified engineers (Cat 1 minimum) to handle refrigerants",
      "F-Gas certification cards checked before work commences",
      "Refrigerant leak detector in use throughout; area ventilated",
      "Refrigerant recovery equipment used; no venting to atmosphere",
      "Cryogenic-rated gloves and face shield worn when handling low-temperature refrigerants",
      "Leak test completed after any repair; results recorded in equipment logbook",
      "Refrigerant purchases and quantities logged in F-Gas register",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Cryogenic gloves", "Face shield", "Safety footwear", "Safety glasses"],
    regs: ["F-Gas Regulation (EU) 517/2014 (UK retained)", "COSHH 2002", "EH40 WEL"],
  },

  // ── ROOFING & WATERPROOFING ─────────────────────────────────────────────────

  {
    id: "roof_001",
    category: "Roofing & Waterproofing",
    activity: "Flat roof works — leading edge and roof edge",
    hazard: "Falls from leading edge; falls through fragile surfaces; materials falling to lower levels",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Hierarchy of controls applied: collective edge protection preferred over harness",
      "Permanent or temporary edge protection (guard rails, barriers) installed before work commences",
      "Working platforms constructed by competent scaffolders; handover certificate issued",
      "No materials or tools left unattended within 2m of roof edge",
      "All operatives briefed on emergency rescue procedure before first day on roof",
      "Roof access restricted to those with roof-specific induction",
      "Safe load limits of roof structure confirmed with structural engineer before mobilisation",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Harness and lanyard (where collective protection not possible)"],
    regs: ["Work at Height Regs 2005", "HSG33 (Health & Safety in Roofwork)", "BS EN 13374 (edge protection)"],
  },

  {
    id: "roof_002",
    category: "Roofing & Waterproofing",
    activity: "Working on or near fragile roof materials",
    hazard: "Falls through fragile surfaces (rooflights, AC cement, corroded metal decking); collapse without warning",
    initialRisk: { L: 6, S: 6, RF: 36 },
    controlMeasures: [
      "Full pre-work survey to identify all fragile materials before any roof access",
      "Crawling boards or roof ladders used at all times on fragile surfaces",
      "Fragile areas marked and barriers erected to prevent accidental approach",
      "Safety nets installed below fragile areas where work cannot be avoided",
      "Fall arrest system used as last resort where nets impractical",
      "Only minimum operatives on roof at any time; bystander exclusion below",
      "Work to be avoided in wet, icy or high wind conditions",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Full harness with short lanyard"],
    regs: ["Work at Height Regs 2005", "HSG33", "GS29 (Roof Work)"],
  },

  {
    id: "roof_003",
    category: "Roofing & Waterproofing",
    activity: "Bitumen torch-on membrane application",
    hazard: "Fire from naked flame torch; burns; explosion from gas cylinder; fire spread to building structure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Hot works permit issued before any torching commences",
      "Gas cylinders stored upright in secure cage; not left unattended when connected",
      "Flash-back arrestors fitted to all regulators",
      "Minimum 2 × 9kg dry powder extinguishers on roof at all times",
      "Fire watch maintained during work and minimum 1 hour after completion",
      "Bitumen mop applied where torch cannot be used near combustible substrates",
      "Adjacent combustibles removed or protected with fire blanket",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Face shield", "Leather gloves", "Safety footwear", "Hi-vis", "Cotton overalls (no synthetic fibres)"],
    regs: ["Hot Works Permit", "DSEAR 2002", "LPS 1214 (hot work)", "COSHH 2002 (bitumen fumes)"],
  },

  {
    id: "roof_004",
    category: "Roofing & Waterproofing",
    activity: "Roof cladding and facade panel installation",
    hazard: "Manual handling of large panels at height; wind loading; falls; cut edges on metal cladding",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Wind speed monitored; work suspended when wind exceeds 15m/s (manufacturer guidance)",
      "Vacuum lifting equipment used for large panels wherever practicable",
      "Panel sizes limited to what two operatives can safely handle",
      "Edge protection and fall arrest in place before any panel installation at height",
      "Cut edges of metal cladding de-burred immediately; off-cuts removed",
      "Rigging and banksman used for all crane-assisted panel lifts",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Cut-resistant gloves (Level C)", "Safety footwear", "Hi-vis", "Safety glasses"],
    regs: ["Work at Height Regs 2005", "Manual Handling Ops Regs 1992", "LOLER 1998"],
  },

  // ── STRUCTURAL STEEL ────────────────────────────────────────────────────────

  {
    id: "steel_001",
    category: "Structural Steel",
    activity: "Steel erection and structural beam placement",
    hazard: "Falls from height during erection; struck by swinging steelwork; premature structural collapse; connection failure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Erection sequence designed by structural engineer; temporary stability considered at each stage",
      "Erection plan prepared by competent person; pre-erection check completed",
      "Operatives use personal fall arrest systems until permanent connections and flooring installed",
      "Exclusion zone below erection area; banksman controls crane movements",
      "Temporary bracing and guys used to maintain stability during erection",
      "Minimum connections specified before crane releases each member",
      "Weather conditions monitored; work suspended in high winds or lightning risk",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear (anti-static)", "Hi-vis", "Full harness with fall arrest", "Gloves"],
    regs: ["Work at Height Regs 2005", "BS 5950 / BS EN 1090", "SCI P374 (Steel Construction)", "LOLER 1998"],
  },

  {
    id: "steel_002",
    category: "Structural Steel",
    activity: "High-strength bolting and structural connections at height",
    hazard: "Falls; dropped tools and bolts onto workers below; over/under torquing causing connection failure",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "All tools tethered when working at height; bolt bags used",
      "Exclusion zone maintained below all bolting activities",
      "Torque settings specified by structural engineer; calibrated torque wrenches used",
      "Torqued connections inspected and marked with paint pen; snug-tight and final torque recorded",
      "Operatives trained in HSFG bolt installation and torque verification",
      "Access platforms or MEWP used; no working from ladders for bolting",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Full harness", "Gloves"],
    regs: ["Work at Height Regs 2005", "BS EN 14399 (HSFG bolts)", "NCHRP Report 107"],
  },

  {
    id: "steel_003",
    category: "Structural Steel",
    activity: "Metal decking installation and temporary works",
    hazard: "Falls through deck voids; cut edges; premature loading of unpropped decking; fire risk from welding on deck",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Decking installation sequence follows structural engineer's temporary works design",
      "Void covers or safety nets placed immediately as deck is laid",
      "No stacking of materials on unpropped decking beyond design load",
      "Edge protection fitted at all open deck edges and stairwell openings",
      "Cut edges of metal decking removed promptly; operatives wear cut-resistant gloves",
      "Hot work permit required before any welding on or through metal decking",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Cut-resistant gloves (Level C)", "Safety footwear", "Hi-vis", "Safety glasses"],
    regs: ["Work at Height Regs 2005", "Steel Deck Institute Design Manual", "CDM 2015 (temporary works)"],
  },

  {
    id: "steel_004",
    category: "Structural Steel",
    activity: "On-site fabrication, grinding and cutting of steel",
    hazard: "Metal dust and swarf; sparks causing fire; disc failure on angle grinder; HAVS from disc cutter",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Correct disc type and size used for material being cut; disc condition checked before fitting",
      "Guard in place and secure; never remove guards",
      "Fire extinguisher adjacent to cutting area; hot work permit issued",
      "Anti-vibration tools used where prolonged disc cutting required; HAVs exposure monitored",
      "Hearing protection, safety goggles and face shield worn",
      "Sparks directed away from combustibles, workers and flammable materials",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Face shield", "Cut-resistant gloves", "Safety footwear", "Hearing protection", "Dust mask (FFP2)"],
    regs: ["PUWER 1998", "COSHH 2002", "Control of Vibration at Work Regs 2005", "Hot Works Permit"],
  },

  // ── DEMOLITION & STRIP-OUT ──────────────────────────────────────────────────

  {
    id: "dem_001",
    category: "Demolition & Strip-out",
    activity: "Structural demolition",
    hazard: "Unplanned collapse; falling debris; adjacent structure damage; buried services; dust",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pre-demolition structural survey by competent engineer; demolition method statement produced",
      "Demolition sequence designed to maintain stability throughout; propping plan followed",
      "Exclusion zone established equal to height of structure being demolished",
      "All services (gas, electric, water) confirmed isolated and disconnected before demolition",
      "Asbestos survey completed and all ACMs removed before structural demolition",
      "Dust suppression by water spraying; operatives in RPE",
      "Adjacent structures monitored for movement during demolition",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Safety glasses", "Dust mask (FFP3)", "Gloves"],
    regs: ["CDM 2015", "BS 6187 (Code of Practice for Demolition)", "HASAWA 1974", "Control of Asbestos Regs 2012"],
  },

  {
    id: "dem_002",
    category: "Demolition & Strip-out",
    activity: "Mechanical breaking and breaker use",
    hazard: "Hand-arm vibration syndrome (HAVS); dust; noise; manual handling; eye injury from fragments",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "HAVs exposure calculated for each tool; daily trigger time limits enforced",
      "Anti-vibration handles and low-vibration tools selected where possible",
      "Regular tool rotation between operatives to limit individual exposure",
      "Hearing protection worn; noise levels monitored",
      "Silica dust suppression by water or LEV; RPE worn for silica-generating tasks",
      "Health surveillance for workers regularly exposed to hand-arm vibration",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Safety goggles", "Hearing protection", "Anti-vibration gloves", "Dust mask (FFP3 for silica)"],
    regs: ["Control of Vibration at Work Regs 2005", "Control of Noise Regs 2005", "COSHH 2002", "EH44 (silica)"],
  },

  {
    id: "dem_003",
    category: "Demolition & Strip-out",
    activity: "Soft strip — partitions, suspended ceilings and raised floors",
    hazard: "Asbestos disturbance; unexpectedly live services; manual handling; falls from access equipment",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Asbestos management survey completed and register reviewed before any strip begins",
      "All services surveyed and confirmed isolated before strip commences",
      "Pilot holes drilled to check void conditions before removing panels",
      "Access equipment (steps, podium, hop-up) used for ceiling work; no working from chairs",
      "Materials lowered safely; not thrown or dropped",
      "Waste removed to skip regularly; no accumulation that creates trip hazards",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Safety glasses", "Gloves", "Dust mask"],
    regs: ["Control of Asbestos Regs 2012", "Manual Handling Ops Regs 1992", "Work at Height Regs 2005"],
  },

  {
    id: "dem_004",
    category: "Demolition & Strip-out",
    activity: "Waste segregation and skip loading",
    hazard: "Manual handling injuries; cuts from sharp materials; hazardous waste contamination; skip overloading",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Waste streams segregated on site: inert, non-hazardous, hazardous clearly labelled",
      "Hazardous waste (asbestos, lead, WEEE) disposed via licensed waste carrier only",
      "Waste transfer notes retained for minimum 3 years (duty of care)",
      "Skip not overloaded beyond manufacturer's rated capacity",
      "No pushing material off height into skip; controlled loading only",
      "Gloves and eye protection worn when handling contaminated materials",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Safety footwear", "Heavy-duty gloves", "Safety glasses", "Hi-vis"],
    regs: ["Environmental Protection Act 1990", "Waste (England & Wales) Regs 2011", "Hazardous Waste Regs 2005"],
  },

  // ── PAINTING, DECORATING & FLOORING ────────────────────────────────────────

  {
    id: "dec_001",
    category: "Painting, Decorating & Flooring",
    activity: "Spray painting and airless spraying",
    hazard: "VOC inhalation; fire and explosion from solvent vapours; skin absorption; ignition of spray mist",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "COSHH assessment for paint product completed; SDS reviewed before use",
      "Respiratory Protective Equipment (RPE) — half-face mask with A2P3 filter minimum",
      "All ignition sources removed from spraying area; no smoking, naked flame, sparks",
      "Adequate mechanical ventilation provided to maintain vapour below 10% LEL",
      "Skin protection — coveralls, nitrile gloves, safety glasses",
      "Fire extinguisher (CO2 or dry powder) adjacent to work area",
      "Hot work permit if any heat source within spray area",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Half-face respirator (A2P3)", "Nitrile gloves", "Coveralls", "Safety goggles", "Safety footwear"],
    regs: ["COSHH 2002", "DSEAR 2002", "EH40 WEL", "HSG178 (Spray Finishing)"],
  },

  {
    id: "dec_002",
    category: "Painting, Decorating & Flooring",
    activity: "Resin and epoxy floor installation",
    hazard: "Skin sensitisation and contact dermatitis from epoxy resin; respiratory sensitisation; slips on wet resin",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "COSHH assessment completed; SDS for resin and hardener reviewed",
      "Gloves changed frequently — nitrile minimum; barrier cream used before and after",
      "No bare skin contact with uncured resin; coveralls worn",
      "Adequate ventilation provided; RPE (A1P2 filter) worn if ventilation cannot meet WEL",
      "Wet resin floor area barriered and signed to prevent slips by other trades",
      "Waste resin and containers disposed as hazardous waste",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Nitrile gloves (change regularly)", "Coveralls", "Safety footwear", "Safety glasses", "Half-face mask (A1P2)"],
    regs: ["COSHH 2002", "EH40 WEL", "HSG205 (resin hazards)"],
  },

  {
    id: "dec_003",
    category: "Painting, Decorating & Flooring",
    activity: "Surface preparation — shot blasting and scarifying",
    hazard: "Silica dust from concrete scarification; metal dust from shot blasting; projectile rebound; HAVS",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Enclosed shot blast equipment with dust collection used in preference to open blasting",
      "Silica dust control plan: wet methods or LEV; no dry sweeping of blast debris",
      "RPE: TH3 powered hood or minimum FFP3 disposable for silica dust",
      "Exclusion zone for shot blast rebound; full face protection",
      "Operatives' silica exposure monitored; health surveillance programme in place",
      "Blast media (spent shot) collected and disposed as controlled waste",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["TH3 powered hood or FFP3 mask", "Full face shield", "Coveralls", "Safety footwear", "Hearing protection"],
    regs: ["COSHH 2002", "EH40 WEL (silica: 0.1 mg/m³ TWA)", "Control of Vibration at Work Regs 2005"],
  },

  // ── PLUMBING & DRAINAGE ─────────────────────────────────────────────────────

  {
    id: "plmb_001",
    category: "Plumbing & Drainage",
    activity: "Working in sewers and drainage systems",
    hazard: "Toxic gases (H2S, CO, methane); oxygen deficiency; flooding; biological contamination; confined space",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Confined space entry permit issued; competent stand-by person stationed above",
      "Atmospheric testing for O2, CO, H2S, LEL before entry and continuously during",
      "Gas-tight emergency escape BA set available at entry point",
      "Upstream flow controlled or diverted before entry where possible",
      "Waterproof lighting; all equipment rated for wet environments",
      "Decontamination facilities provided; Hepatitis A and Tetanus vaccinations recommended",
      "Rescue plan and equipment (tripod, winch) in place before entry",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["SCBA", "Chemical resistant waders", "Coveralls", "Nitrile gloves", "Hard hat", "Head torch"],
    regs: ["Confined Spaces Regs 1997", "L101 ACOP", "Water Industry Act 1991", "COSHH 2002"],
  },

  {
    id: "plmb_002",
    category: "Plumbing & Drainage",
    activity: "Legionella risk — water system maintenance and commissioning",
    hazard: "Legionella bacteria growth and dispersal; inhalation of contaminated aerosols; fatal Legionnaires' disease",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Legionella risk assessment completed by competent person to L8 ACOP requirements",
      "Water system schematic up to date; all dead legs removed or flushed weekly",
      "Cold water stored below 20°C; hot water delivered at minimum 50°C at outlets",
      "Sentinel taps flushed and temperature recorded monthly",
      "Shower heads cleaned and disinfected quarterly",
      "Written scheme of control in place; water treatment contract reviewed annually",
      "Biocide dosing programme maintained; records kept",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Nitrile gloves", "Safety glasses", "RPE (FFP3 when disturbing biofilm)"],
    regs: ["L8 ACOP (Legionella)", "HSG274 Parts 1/2/3", "HTM 04-01 (healthcare water)"],
  },

  {
    id: "plmb_003",
    category: "Plumbing & Drainage",
    activity: "MDPE, copper and press-fit pipe installation",
    hazard: "Solder flux fume inhalation; burns from soldering; leak on pressurised system; manual handling",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Water-soluble flux used in preference to corrosive flux; used sparingly",
      "Ventilation provided when soldering; RPE worn in poorly ventilated areas",
      "All pipework pressure tested before concealment; test pressure and duration recorded",
      "Press-fit tool calibrated and in date; connections visually checked post-press",
      "Isolation points provided at intervals; valves accessible and labelled",
      "Plastic pipe cut square; deburring tool used on all cut ends",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Safety glasses", "Gloves (heat-resistant for soldering)", "Safety footwear"],
    regs: ["COSHH 2002 (solder flux fume)", "PSSR 2000", "Water Supply (Water Fittings) Regs 1999"],
  },

  // ── FIRE PROTECTION ─────────────────────────────────────────────────────────

  {
    id: "fire_001",
    category: "Fire Protection",
    activity: "Fire stopping and passive fire compartmentation",
    hazard: "Breach of fire compartment during works creating fire spread risk; intumescent product fume; WAH",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Hot works permit issued before any work on compartment walls or floors",
      "Temporary fire stopping installed at end of each working day where permanent seal incomplete",
      "COSHH assessment for intumescent sealants and collars; adequate ventilation",
      "All penetrations photographed before and after sealing; records kept",
      "Third-party inspection and certification of fire stopping on completion",
      "Building control notified of all compartment penetrations on notifiable projects",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Safety glasses", "Nitrile gloves", "Dust mask", "Safety footwear", "Hard hat"],
    regs: ["Building Regs 2010 Approved Doc B", "BS 9999", "COSHH 2002", "CDM 2015"],
  },

  {
    id: "fire_002",
    category: "Fire Protection",
    activity: "Sprinkler system installation and pressure testing",
    hazard: "Inadvertent activation flooding building; high-pressure water injury; WAH for overhead pipework; falling objects",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "System installation to LPC/LPCB rules or BS EN 12845; competent installer",
      "Main stop valve isolated during installation; notice posted",
      "Pressure test carried out before sprinkler heads fitted; test pressure 1.5× working pressure",
      "Building management notified before any system activation or test",
      "MEWP or scaffold used for overhead pipework; IPAF certification verified",
      "Sprinkler heads protected during other trades' activities; written procedure in place",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Safety glasses", "Hi-vis", "Harness (MEWP)"],
    regs: ["BS EN 12845", "LPC Rules for Sprinkler Installations", "PSSR 2000", "Work at Height Regs 2005"],
  },

  {
    id: "fire_003",
    category: "Fire Protection",
    activity: "Dry riser and wet riser installation",
    hazard: "Pressure system failure; working at height in stairwells; heavy pipework manual handling",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pressure test to 12 bar (dry riser) or 10 bar (wet riser) before commissioning; records made",
      "Safety valves set and tested; pressure gauges calibrated",
      "Stairwell working platform erected and signed off; PASMA cert required",
      "Pipe sections restrained before connections released; crush injury prevention",
      "Fire brigade inlet and outlet positions agreed with Authority Having Jurisdiction (AHJ)",
      "Commissioning test witnessed by fire brigade or appointed inspector on completion",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Safety glasses", "Gloves", "Hi-vis"],
    regs: ["BS 9990 (dry risers)", "BS 9251 (wet risers)", "PSSR 2000", "Work at Height Regs 2005"],
  },

  // ── SOLAR PV & EV CHARGING ──────────────────────────────────────────────────

  {
    id: "solar_001",
    category: "Solar PV & EV Charging",
    activity: "Solar PV panel installation on roofs",
    hazard: "DC arc flash (panels always live in daylight); falls from roof; electrical shock; structural overloading",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "DC strings covered with opaque sheeting during installation to prevent generation",
      "All DC work carried out by MCS-certified/competent PV installer",
      "Insulated tools rated for DC voltage used for all string connections",
      "Roof access: full collective edge protection or harness fall arrest",
      "Structural survey confirms roof load capacity before panel installation",
      "Temporary DC string labels applied before permanents; never work on unmarked DC circuits",
      "Emergency isolation procedure documented and communicated before work starts",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Insulated gloves (Class 00 min DC)", "Safety glasses", "Safety footwear", "Hard hat", "Harness (roof work)"],
    regs: ["Electricity at Work Regs 1989", "BS 7671 (722 PV systems)", "Work at Height Regs 2005", "MCS Standards"],
  },

  {
    id: "solar_002",
    category: "Solar PV & EV Charging",
    activity: "DC cable runs and inverter wiring",
    hazard: "Live DC circuits cannot be isolated by switching (panels generate in any light); arc flash; shock",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "String circuits covered with opaque film before any DC cable work",
      "Working voltage confirmed with calibrated DC meter before touching conductors",
      "All DC connectors compatible (MC4 or equivalent); no mixed brand connections",
      "Fuse and disconnects installed at each string before cable run to inverter",
      "Only one string connected at a time during commissioning",
      "Minimum two persons present during all live DC commissioning",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Class 1 insulated gloves", "Face shield (arc-rated)", "Safety footwear (anti-static)", "Safety glasses"],
    regs: ["Electricity at Work Regs 1989", "BS 7671 Chapter 712", "IET Wiring Regulations"],
  },

  {
    id: "solar_003",
    category: "Solar PV & EV Charging",
    activity: "EV charge point installation",
    hazard: "LV electrical work; cable trenching in car park; bollard/post fixings; vehicle movements near operatives",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Isolation of LV supply by qualified electrician before connection works",
      "Traffic management in car park — cones, barriers and signage before excavation",
      "CAT scan before any ground works in car park surface",
      "Charge point foundation designed for imposed loads; fixings to manufacturer specification",
      "Cable containment to BS 7671 wiring regulations; appropriate IP rating for external installation",
      "OLEV/OZEV grant conditions and documentation completed where applicable",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Safety footwear", "Hi-vis", "Hard hat", "Safety glasses", "Insulated gloves (LV work)"],
    regs: ["Electricity at Work Regs 1989", "BS 7671 (722 EV)", "PAS 1899:2022 (EV charge points)", "CDM 2015"],
  },

  {
    id: "solar_004",
    category: "Solar PV & EV Charging",
    activity: "Battery energy storage system (BESS) installation",
    hazard: "Thermal runaway / fire; toxic gas release from Li-ion cells; electrocution; heavy module lifting",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "BESS installation by manufacturer-trained and certified engineers only",
      "Fire suppression system designed for Li-ion fire class specified in installation area",
      "Thermal runaway emergency procedure posted and communicated to all on site",
      "Battery modules never short-circuited; insulating covers fitted during transit",
      "Class D or specialist Li-ion extinguishers available throughout installation",
      "Ventilation to battery enclosure checked against manufacturer specification",
      "Structural survey for floor loading; fork truck used with certified slings for modules",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Insulated gloves (Class 1)", "Face shield", "Anti-static footwear", "Chemical splash goggles"],
    regs: ["BS EN IEC 62619 (Li-ion safety)", "DSEAR 2002", "Electricity at Work Regs 1989", "LOLER 1998"],
  },

  // ── RAIL & TRACKSIDE ────────────────────────────────────────────────────────

  {
    id: "rail_001",
    category: "Rail & Trackside",
    activity: "Line blockage and possession working",
    hazard: "Struck by train during possession; failure of protection arrangements; working outside booked possession limits",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Possession obtained and confirmed by PICOP (Person in Charge of Possession) before any track access",
      "COSS (Controller of Site Safety) appointed and briefed on all workers present",
      "Safe system of work briefed to all before track access; no one on track without COSS authority",
      "Lookout system in place where required; lookout trained and equipped with horn/flag",
      "OTP (Outline Track Protection) map reviewed; possession limits displayed",
      "All workers hold valid PTS (Personal Track Safety) certificate",
      "Emergency call-off arrangements tested; emergency contacts posted",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Orange hi-vis (NR approved)", "Hard hat", "Safety footwear (steel toe & midsole)", "Gloves"],
    regs: ["NR/L2/OHS/019 (PTS)", "Railway Group Standards", "ROGS 2006", "HASAWA 1974"],
  },

  {
    id: "rail_002",
    category: "Rail & Trackside",
    activity: "Working near overhead line equipment (OLE)",
    hazard: "Electrocution from 25kV OLE; flashover without contact; working on energised OLE",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "OLE isolated and earthed (OLEC) by authorised person before any work within 600mm",
      "Line clear obtained from signaller/OLEC before any work in OLE exclusion zone",
      "Minimum approach distances clearly marked and enforced: 600mm live OLE boundary",
      "No metallic objects or tools raised above working height near live OLE without isolating",
      "DCCR (DC Current Return) bonding requirements verified with infrastructure manager",
      "All workers hold relevant OLE competency cards",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Orange hi-vis", "Hard hat", "Safety footwear", "Insulated tools only near OLE"],
    regs: ["Network Rail Standard NR/L2/RMVP/0151", "Electricity at Work Regs 1989", "GS6 (electrical safety)"],
  },

  {
    id: "rail_003",
    category: "Rail & Trackside",
    activity: "Trackbed and ballast maintenance works",
    hazard: "Silica dust from ballast; whole-body vibration from on-track plant; manual handling of sleepers; train approach",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Silica dust control plan: water suppression on all ballast disturbance; FFP3 RPE worn",
      "WBV (whole-body vibration) exposure calculated for tamper/stoneblower operators; daily limits enforced",
      "Machine operators trained and competent on specific on-track plant",
      "Manual sleeper lifting: team lifting; no individual to lift standard sleeper alone (>80kg)",
      "Possession protection in place before any trackbed work commences",
      "Silica health surveillance programme for regularly exposed workers",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["FFP3 mask (silica)", "Orange hi-vis", "Hard hat", "Safety footwear", "Hearing protection", "Anti-vibration gloves"],
    regs: ["Control of Vibration at Work Regs 2005", "COSHH 2002 (silica)", "Manual Handling Ops Regs 1992", "Network Rail standards"],
  },

  // ── WAREHOUSING & LOGISTICS ─────────────────────────────────────────────────

  {
    id: "wh_001",
    category: "Warehousing & Logistics",
    activity: "Racking installation and SEMA inspection",
    hazard: "Racking collapse during erection; overloading; impact damage creating latent failure; falls during erection",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Racking designed and certified by SEMA-approved engineer; load notices displayed on all aisles",
      "Installation by SEMA-accredited installer; completion certificate issued",
      "Floor loadings checked against specification before installation",
      "Annual inspection by SEMA-trained rack inspector; traffic light system for damage reporting",
      "Rack guard barriers installed at ends of all aisles",
      "No rack component modified or removed without engineer's approval",
      "Exclusion zone during erection; racking not loaded until completion certificate issued",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Safety glasses", "Gloves"],
    regs: ["SEMA Code of Practice for Storage Racking", "BS EN 15512 & 15620", "PUWER 1998", "Work at Height Regs 2005"],
  },

  {
    id: "wh_002",
    category: "Warehousing & Logistics",
    activity: "Mezzanine floor design, installation and handover",
    hazard: "Premature loading causing structural failure; falls from open mezzanine edges; fire escape compliance",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Structural design by registered engineer with full calculations; building control approval obtained",
      "Erection sequence follows engineer's temporary stability notes",
      "No storage or equipment placed on mezzanine until completion certificate issued",
      "Open edges: permanent edge protection (1.1m guard rail + 100mm kick board) before any deck access",
      "Fire escape route from mezzanine agreed with fire authority; smoke detection installed",
      "Safe working load notices permanently displayed on mezzanine",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Harness (during erection before edge protection)"],
    regs: ["Building Regs 2010", "BS EN 1090 (steel)", "Work at Height Regs 2005", "CDM 2015"],
  },

  {
    id: "wh_003",
    category: "Warehousing & Logistics",
    activity: "Conveyor and sortation system installation",
    hazard: "Entanglement in nip points during commissioning; persons trapped by live conveyor; falling components at height; electrical",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "All guards fitted and checked before any system power-on",
      "Lock-out/tag-out (LOTO) procedure applied for all maintenance and commissioning work",
      "E-stop buttons tested and confirmed functional before loading any conveyor",
      "Pre-commissioning walkthrough to confirm all tools and personnel clear",
      "Access platforms with safety gates installed at all elevated conveyor maintenance points",
      "No body parts inside conveyor envelope unless full LOTO applied",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Safety glasses", "Gloves (no loose-fitting)"],
    regs: ["PUWER 1998", "Machinery Directive 2006/42/EC (UK retained)", "Electricity at Work Regs 1989", "BS EN ISO 4254"],
  },

  {
    id: "wh_004",
    category: "Warehousing & Logistics",
    activity: "Working alongside LGVs, HGVs and FLTs in warehouse",
    hazard: "Pedestrian struck by moving vehicle; blind spots around large vehicles; loading bay falls",
    initialRisk: { L: 6, S: 6, RF: 36 },
    controlMeasures: [
      "Segregated pedestrian and vehicle routes clearly marked and enforced",
      "Pedestrian crossing points have mirrors and give-way markings",
      "All vehicles fitted with reversing alarms and proximity sensors",
      "Banksman system in place for all reversing HGVs in delivery areas",
      "Loading bay: barriers to prevent falls; dock levellers in safe position when not in use",
      "Speed limit of 10mph (or lower) enforced in all internal logistics areas",
      "High-visibility clothing worn by all persons in vehicle operating areas",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hi-vis (Class 2 minimum)", "Safety footwear", "Hard hat in loading bay areas"],
    regs: ["HASAWA 1974", "Workplace (Health Safety & Welfare) Regs 1992", "HSG136 (Workplace Transport)", "PUWER 1998"],
  },

  // ── TRAFFIC MANAGEMENT (TMP) ───────────────────────────────────────────────

  {
    id: "tmp_001",
    category: "Traffic Management (TMP)",
    activity: "Temporary traffic management on public highway (lane closures, contraflow)",
    hazard: "Vehicle incursion into work area; worker struck by traffic; public confusion at transitions",
    initialRisk: { L: 6, S: 6, RF: 36 },
    controlMeasures: [
      "Chapter 8-compliant signing, lighting and guarding to design approved by competent TMP designer",
      "TTRO / permit in place before works start; advance warning signs erected in correct sequence",
      "Safety zones and working space clearly defined; no work outside agreed limits",
      "Brief all operatives on emergency vehicle access and diversion routes",
      "Mobile plant movements coordinated; banksman where reversing near live traffic",
      "Night working: enhanced lighting and retroreflective signing checked before each shift",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hi-vis (Class 3 for highway)", "Safety footwear", "Hard hat", "Gloves"],
    regs: ["Safety at Street Works (NRSWA)", "Traffic Signs Regs & TSRGD", "CDM 2015", "HASAWA 1974"],
  },

  {
    id: "tmp_002",
    category: "Traffic Management (TMP)",
    activity: "Road crossing and cable pull under traffic management",
    hazard: "Operatives exposed to live lanes; trip on cables; communication failure with lookout",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Stop/go or portable signals used where agreed in TMP; no ad-hoc crossings",
      "Minimum number of crossings; timed to low-flow windows where possible",
      "Lookout / banksman in radio contact with team; emergency stop procedure rehearsed",
      "Cables laid in channels or protected ramps; no trailing leads across carriageway",
      "All persons briefed on safe refuge points and muster",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hi-vis Class 3", "Safety footwear", "Hard hat"],
    regs: ["HASAWA 1974", "HSG150 (Construction Information)", "NRSWA Code of Practice"],
  },

  {
    id: "tmp_003",
    category: "Traffic Management (TMP)",
    activity: "Mobile lane closure with impact protection vehicle (IPV)",
    hazard: "Rear-end shunt into IPV or workforce; equipment strike; driver fatigue",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "IPV positioned per design; chevron markings and lighting operational",
      "Driver rotation and fatigue management; pre-drive vehicle checks",
      "Buffer vehicle spacing maintained; no standing between IPV and live lane except brief tasks",
      "Recovery plan for breakdown of IPV; spare vehicle identified",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hi-vis", "Safety footwear"],
    regs: ["Traffic Signs Regs", "Construction (Head Protection) Regs 1989", "PUWER 1998"],
  },

  {
    id: "dem_004",
    category: "Demolition & Strip-out",
    activity: "Structural demolition and progressive collapse control",
    hazard: "Unplanned collapse; falling debris; dust and vibration affecting neighbours",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Demolition sequence defined by structural engineer; method statement reviewed before start",
      "Exclusion zones and hard barriers; no personnel inside drop zone",
      "Water suppression for dust; noise and vibration monitoring where required",
      "Utilities isolated and verified dead before breaking structure",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "RPE (dust)", "Safety glasses"],
    regs: ["CDM 2015", "HSG150", "Control of Noise at Work Regs 2005", "COSHH 2002"],
  },

  {
    id: "pv_004",
    category: "Solar PV & EV Charging",
    activity: "Roof-mounted PV string commissioning and inverter energisation",
    hazard: "DC shock / arc flash during string testing; falls from roof edge; tools left on glass",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "DC isolators lockable; strings energised only when all terminations inspected",
      "No metal tools on live connectors; insulated tools only",
      "Edge protection and harness rescue plan for roof work",
      "Inverter AC energisation only after DC tests signed off by competent electrician",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Harness where edge protection incomplete", "Insulated gloves (DC work)", "Safety glasses", "Hi-vis"],
    regs: ["Electricity at Work Regs 1989", "BS 7671", "Work at Height Regs 2005"],
  },

  // ── TEMPORARY WORKS ADVANCED ────────────────────────────────────────────────

  {
    id: "twx_001",
    category: "Temporary Works Advanced",
    activity: "Falsework and formwork erection",
    hazard: "Collapse from incorrect sequencing or overloading; worker falls; struck by dropped components",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Design and checks completed by competent TWD with TWC approval before erection",
      "Erection sequence briefed at start of each shift; no deviation without engineering sign-off",
      "Load limits posted on all decks and monitored during pours and material storage",
      "Independent inspection and hold-point sign-off before concrete pour",
      "Edge protection and access controls maintained at all times",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves", "Harness (where required)"],
    regs: ["CDM 2015", "BS 5975 (Temporary Works)", "Work at Height Regs 2005"],
  },
  {
    id: "twx_002",
    category: "Temporary Works Advanced",
    activity: "Propping and needle support to existing structure",
    hazard: "Uncontrolled structural movement; collapse during load transfer; crushing injuries",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Pre-works condition survey and load path assessment by structural engineer",
      "Install props to approved drawing with verified bearing conditions",
      "Load transfer sequence controlled by appointed competent supervisor",
      "Movement monitoring (tell-tales/laser) in place during transfer operations",
      "Exclusion zones and no-go beneath loaded members enforced",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Gloves"],
    regs: ["CDM 2015", "BS 5975", "HASAWA 1974"],
  },

  // ── FACADE & GLAZING ────────────────────────────────────────────────────────

  {
    id: "fcd_001",
    category: "Facade & Glazing",
    activity: "Curtain wall panel installation with vacuum lifter",
    hazard: "Panel drop from loss of suction; wind destabilisation; crush injuries at interface",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Vacuum lifter pre-use checks with alarm and battery backup verified",
      "Wind speed limits set and monitored; cease lifts above manufacturer threshold",
      "Tag lines and banksman used to control panel movement into final position",
      "Exclusion zone below and around drop path maintained",
      "Lift plan includes emergency recovery for partial panel release",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Safety footwear", "Hi-vis", "Cut-resistant gloves", "Safety glasses"],
    regs: ["LOLER 1998", "BS 7121", "Work at Height Regs 2005"],
  },
  {
    id: "fcd_002",
    category: "Facade & Glazing",
    activity: "Glass replacement over public interface",
    hazard: "Falling objects to public realm; glass breakage and laceration; uncontrolled access",
    initialRisk: { L: 5, S: 6, RF: 30 },
    controlMeasures: [
      "Public exclusion and hard segregation installed before any removal starts",
      "Catch decks/netting or equivalent secondary retention in place",
      "Fragmentation and removal method agreed before first cut",
      "Spotters at all public approach routes during active works",
      "Emergency breakage response kit and clean-up process briefed",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Cut-resistant gloves", "Safety glasses/face shield", "Safety footwear", "Hi-vis"],
    regs: ["Work at Height Regs 2005", "Management of H&S at Work Regs 1999"],
  },

  // ── CONTAMINATED LAND & REMEDIATION ────────────────────────────────────────

  {
    id: "clr_001",
    category: "Contaminated Land & Remediation",
    activity: "Excavation in contaminated soils",
    hazard: "Dermal and inhalation exposure to hydrocarbons/heavy metals; cross-site contamination",
    initialRisk: { L: 5, S: 5, RF: 25 },
    controlMeasures: [
      "Contaminated land risk assessment and zoning completed before excavation",
      "Dedicated clean/dirty routes and wheel wash implemented",
      "Dust suppression and RPE controls used during soil disturbance",
      "Decontamination, hygiene and welfare controls enforced at zone exits",
      "Waste classification and disposal records retained for all loads",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Chemical-resistant gloves", "Coveralls", "Safety footwear", "RPE (FFP3 where required)"],
    regs: ["COSHH 2002", "Environmental Protection Act 1990", "CL:AIRE guidance"],
  },
  {
    id: "clr_002",
    category: "Contaminated Land & Remediation",
    activity: "Ground gas monitoring and entry controls",
    hazard: "Asphyxiation/explosion from methane and CO2 accumulation in excavations/voids",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Gas monitoring plan with action thresholds and escalation triggers in place",
      "Continuous monitoring for CH4, CO2, O2 and LEL at workface and low points",
      "Forced ventilation and stop-work trigger when thresholds exceeded",
      "Permit controls for enclosed/partially enclosed spaces",
      "Emergency evacuation and rescue arrangements tested",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Gas detector", "Safety footwear", "Hi-vis", "RPE as assessed"],
    regs: ["Confined Spaces Regs 1997", "DSEAR 2002", "COSHH 2002"],
  },

  // ── MARINE & WATER PROXIMITY ────────────────────────────────────────────────

  {
    id: "mar_001",
    category: "Marine & Water Proximity",
    activity: "Work on quay edge / near open water",
    hazard: "Drowning from slips/trips at edge; rescue delay; cold-water shock",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Edge controls, anti-slip routes and exclusion zones installed before start",
      "Lifejackets and throw lines mandatory within defined red zone",
      "Dedicated rescue kit and trained responders available at all times",
      "Buddy system and welfare checks enforced during near-water tasks",
      "Weather and tide windows reviewed in daily briefing",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Automatic lifejacket", "Safety footwear", "Hi-vis", "Helmet (as task requires)"],
    regs: ["HASAWA 1974", "Work at Height Regs 2005", "Port marine safety guidance"],
  },
  {
    id: "mar_002",
    category: "Marine & Water Proximity",
    activity: "Temporary pontoon / floating platform operations",
    hazard: "Instability, slips, overboard events and trapped fingers during mooring movements",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Platform certification, load checks and mooring integrity confirmed before use",
      "Access gangway angle and handrails maintained within safe limits",
      "No overloading of platform with plant/materials beyond marked limits",
      "Deck housekeeping and anti-slip controls maintained throughout shift",
      "Mooring adjustments controlled by trained personnel only",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Lifejacket", "Gloves", "Safety footwear", "Hi-vis"],
    regs: ["HASAWA 1974", "PUWER 1998", "Local marine authority requirements"],
  },

  // ── BATTERY & ENERGY STORAGE ────────────────────────────────────────────────

  {
    id: "bes_001",
    category: "Battery & Energy Storage",
    activity: "Lithium battery cabinet install and energisation",
    hazard: "Thermal runaway initiation, arc flash, toxic off-gassing during fault conditions",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Install by manufacturer-certified technicians to approved layout and clearances",
      "Commissioning checklist includes BMS alarms, isolation, and ventilation interlocks",
      "Fire strategy includes lithium-specific response and no-water zones where specified",
      "Segregate energized and non-energized work zones with permit controls",
      "Emergency isolation and escalation procedure posted and rehearsed",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Insulated gloves", "Arc-rated face shield", "Safety footwear", "Safety glasses"],
    regs: ["Electricity at Work Regs 1989", "DSEAR 2002", "BS EN IEC 62933 guidance"],
  },
  {
    id: "bes_002",
    category: "Battery & Energy Storage",
    activity: "Battery storage, transport and temporary laydown",
    hazard: "Cell damage, short-circuit, fire escalation from poor segregation or impact",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Store batteries in designated zones with temperature monitoring and impact protection",
      "Terminals protected and packaged to prevent short-circuit during handling",
      "No mixed damaged and healthy packs in same laydown area",
      "Damaged/defective battery quarantine process with clear labeling",
      "Transport and lifting methods follow manufacturer instructions and load limits",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Gloves", "Safety footwear", "Hi-vis", "Safety glasses"],
    regs: ["ADR (where applicable)", "PUWER 1998", "Manufacturer safety data and handling guidance"],
  },

];

export default EXTENDED_LIBRARY;

// ─── Combined export for convenience ─────────────────────────────────────────
// In your app, merge both libraries:
//
//   import BASE from "./ramsHazardLibrary";
//   import EXT from "./ramsHazardLibraryExtended";
//
//   export const ALL_HAZARDS = [...BASE, ...EXT];
//
//   export const ALL_CATEGORIES = [
//     ...BASE_CATEGORIES,
//     ...EXTENDED_CATEGORIES,
//   ];
