/**
 * Reference libraries for RAMS builder — PPE, plant, qualifications (CONSTRUCTION.txt scope).
 */

export const PPE_REFERENCE_LIBRARY = [
  "Hard hat",
  "Safety boots / footwear (steel toe cap, midsole)",
  "Hi-vis vest (Class 2)",
  "Hi-vis jacket (Class 3)",
  "Safety gloves — general",
  "Cut-resistant gloves",
  "Chemical / nitrile gloves",
  "Safety goggles",
  "Safety glasses (BS EN166)",
  "Face shield",
  "Welding mask / auto-darkening hood",
  "Hearing protection (ear defenders / plugs)",
  "FFP2 respirator",
  "FFP3 respirator (face-fit tested)",
  "Half-face respirator with A/P filters",
  "Full-face respirator",
  "Harness and fall-arrest lanyard",
  "Work positioning lanyard",
  "Life jacket / PFD",
  "Waterproof / foul weather clothing",
  "Disposable coveralls (Type 5/6)",
  "Arc-flash rated clothing (HRC assessed)",
  "Insulated gloves (electrical)",
  "Chainsaw helmet with visor and ear defenders",
  "Chainsaw protective trousers (Type C)",
  "Knee pads",
  "UV / sun protection",
  "Anti-vibration gloves",
  "Heat-resistant gauntlets",
  "Cleanroom coverall",
  "Hair/beard net (food hygiene)",
];

export const PLANT_EQUIPMENT_LIBRARY = [
  "360° excavator",
  "Mini excavator",
  "Dumper / articulated dump truck",
  "Roller / compactor",
  "Telehandler",
  "Forklift / FLT",
  "Mobile crane",
  "MEWP / cherry picker",
  "Scissor lift",
  "Tower scaffold / system scaffold",
  "Mobile scaffold tower (PASMA)",
  "Concrete pump",
  "Plate compactor",
  "Vacuum excavator (suction)",
  "CAT & Genny (EML)",
  "GPR cart / array",
  "Total station / GNSS rover",
  "Laser scanner / mobile mapping",
  "UAV / drone",
  "CCTV survey crawler",
  "HPWJ / jetting unit",
  "Generator",
  "Compressor",
  "Welding set",
  "Angle grinder / disc cutter",
  "Demolition hammer / breaker",
  "Piling rig",
  "Road planer / paver",
  "Traffic management vehicle (impact protection)",
];

export const EMERGENCY_PROCEDURE_TOPICS = [
  "First aid and appointed persons",
  "Fire evacuation and muster points",
  "Confined space rescue",
  "Service strike — gas",
  "Service strike — electricity",
  "Service strike — water",
  "Spill response — fuel/oil",
  "Spill response — chemical (COSHH)",
  "Overhead power line contact",
  "Person fall from height",
  "Excavation collapse",
  "Lone worker overdue check-in",
  "Adverse weather / lightning",
  "Security / trespasser",
  "Environmental pollution notification",
];

/** Maps catalog activity tokens to suggested document types (cross-link hints). */
export const RAMS_SUPPORTING_DOCUMENTS = [
  "Risk Assessment (this RAMS)",
  "Method Statement",
  "COSHH Assessment",
  "Toolbox Talk record",
  "Lift Plan (LOLER)",
  "Permit to Dig",
  "Permit to Work",
  "Hot Work Permit",
  "Confined Space Permit",
  "Electrical Isolation / LOTO certificate",
  "Traffic Management Plan",
  "Emergency Rescue Plan",
  "Site Induction record",
  "Competency / training matrix",
  "Plant inspection (PUWER)",
  "LOLER thorough examination",
  "Dynamic Risk Assessment (field)",
  "Legislation register entry",
  "Glass & hard plastic (G&HP) log",
  "Line clearance / product isolation permit",
  "Allergen changeover record",
];
