/**
 * Site investigation & geotechnics hazard library — DCP, probing, CPT, coring, augers, piezometers.
 */

export const SITE_INVESTIGATION_CATEGORIES = ["Site Investigation & Geotechnics"];

const SITE_INVESTIGATION_LIBRARY = [
  {
    id: "si_001",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Window sampling / windowless sampler (tracked rig)",
    hazard: "Plant strike; buried services; collapse of sampling hole; manual handling of samples; contamination exposure",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Desk study and utility records; CAT/Genny before intrusive works",
      "Permit-to-dig and exclusion zone around sampler tracks",
      "Competent operator; sample chain of custody and labelling at point of sampling",
      "Shoring or stepping back where hole depth exceeds safe angle of repose",
      "RPE/gloves per contamination assessment; decon plan for hot samples",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "RPE as COSHH assessment"],
    regs: ["CDM 2015", "HSG47", "COSHH 2002", "HSG248 (Contaminated Land)"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Window sampling operator competence", "CAT/Genny competence"],
  },
  {
    id: "si_002",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Machine-excavated trial pit (GI logging)",
    hazard: "Side collapse; plant/person interface; services strike; falling into pit; uncontrolled spoil",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Trial pit design by competent person; max depth without shoring defined",
      "Banksman for excavator; no persons in pit while machine working",
      "Stepping or battering; trench box/shoring if depth requires",
      "Permit-to-dig; hand dig final exposure near marked services",
      "Secure pit overnight with covers/barriers; backfill same shift where possible",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis Class 3", "Safety footwear", "Gloves"],
    regs: ["HSG185", "HSG47", "CDM 2015"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Excavation supervisor / AP competence", "CAT/Genny competence"],
  },
  {
    id: "si_003",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Dynamic probing — DCP / DPH / DPM / DPL (dynamic cone penetrometer)",
    hazard: "Manual handling of drive rods; overhead entanglement; strike on buried objects; lone working; traffic interface",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Locate utilities before probing; stop if refusal or unexpected material",
      "Two-person lift for heavy drive rods; mechanical aid where provided",
      "Exclusion zone when working near carriageway; Chapter 8 TM if on highway",
      "Record blow counts and refusal depth; cap/protect open probe holes",
      "Decontaminate equipment between contaminated locations",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Eye protection"],
    regs: ["HASAWA 1974", "Manual Handling Regs 1992", "HSG47"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Dynamic probing / DCP operator training"],
  },
  {
    id: "si_004",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Cone penetration test (CPT / piezocone)",
    hazard: "High-pressure hydraulic plant; push frame instability; services strike; noise; pinch points",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Rig setup on stable, level platform; outriggers deployed per manufacturer",
      "Utility clearance and permit interfaces before penetration",
      "Exclusion zone around push frame; no entry during thrust",
      "Hydraulic hose inspection; pressure release before disconnect",
      "Environmental monitoring for fuel/spill kit on rig",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Hearing protection", "Gloves"],
    regs: ["PUWER 1998", "BS EN ISO 22476 (in-situ tests)", "CDM 2015"],
    permitTypes: ["ground_disturbance", "excavation"],
    requiredCerts: ["CPT rig operator competence"],
  },
  {
    id: "si_005",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Cable percussive / shell & auger boring",
    hazard: "Rotating plant; falling tools; spoil ejection; collapse of borehole; contamination; services strike",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Exclusion zone equal to mast height; rig daily checks",
      "Tool catcher and crown block limits; no hands on rotating rods",
      "Borehole support/lining where collapse risk; do not leave uncapped holes",
      "Spoil management and contamination controls; sample sealing on site",
      "Permit-to-dig and utility search before siting rig",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Eye protection"],
    regs: ["BS EN ISO 22475 (GI testing)", "CDM 2015", "COSHH 2002"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Cable percussive drilling competence", "Banksman where required"],
  },
  {
    id: "si_006",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Rotary open-hole drilling & rock coring",
    hazard: "High torque; projectile debris; mud circulation pressure; H₂S/ground gas; rig overturning on slopes",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Rotary rig competency; pre-start mast/rig inspection",
      "Mud tank and circulation pressure controls; spill containment",
      "Ground gas monitoring where desk study indicates; stop work triggers",
      "Core barrel handling with mechanical aids; pinch point awareness",
      "Secure borehole with lockable cap; backfill or grouted abandonment per spec",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Eye protection", "Gas monitor (where required)"],
    regs: ["BS EN ISO 22475", "Confined Spaces Regs 1997 (gas)", "CDM 2015"],
    permitTypes: ["ground_disturbance", "excavation", "confined_space"],
    requiredCerts: ["Rotary drilling operator", "Ground gas awareness"],
  },
  {
    id: "si_007",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Hand auger / handheld sampling (shallow GI)",
    hazard: "Manual handling; sharp auger blades; services strike; biological/contamination exposure",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Utility search before augering; stop at refusal or services",
      "Team lift for extension rods; rotate handles with clear grip",
      "Sample labelling and chain of custody; hand hygiene and gloves",
      "Cap holes and reinstate surface after sampling",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Cut-resistant gloves"],
    regs: ["Manual Handling Regs 1992", "COSHH 2002", "HSG47"],
    permitTypes: ["excavation"],
    requiredCerts: ["GI sampling awareness"],
  },
  {
    id: "si_008",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Undisturbed sampling — U100 / thin-wall / Shelby tube / piston sampler",
    hazard: "Sample disturbance affecting results; manual handling; hole collapse; contamination cross-contact",
    initialRisk: { L: 3, S: 4, RF: 12 },
    controlMeasures: [
      "Sampler type matched to ground conditions and lab specification",
      "Clean equipment between samples; wax/seal tubes immediately",
      "Chain of custody form completed on site; transport upright and cushioned",
      "Competent driller/sampler for push-in tubes; do not over-drive",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves"],
    regs: ["BS EN ISO 22475", "BS 1377 (testing)", "CDM 2015"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["Undisturbed sampling training"],
  },
  {
    id: "si_009",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Piezometer / standpipe / monitoring well installation",
    hazard: "Open borehole fall; ground gas release; contamination; manual handling of casing/gravel pack",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Borehole capped and guarded until completion; barrier and signage",
      "Gas monitoring during install where contaminated or landfill sites",
      "Correct gravel pack/filter and bentonite seal per design",
      "Lockable protective cover at surface; record GPS/level and as-built",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Gas monitor (as required)"],
    regs: ["BS EN ISO 22475", "Ground gas guidance (CIRIA C665)", "CDM 2015"],
    permitTypes: ["ground_disturbance", "excavation"],
    requiredCerts: ["Monitoring well install competence"],
  },
  {
    id: "si_010",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Concrete / asphalt coring for thickness & material verification (structural)",
    hazard: "Silica dust; rotating core drill; services in slab; water slurry; manual handling of cores",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Scan slab for services before coring; permit interface with client",
      "Water suppression or M-class dust extraction; RPE if required",
      "Secure core barrel; exclusion zone below coring position if elevated",
      "Label cores with location/depth; dispose of slurry per environmental plan",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Eye protection", "RPE FFP3 (dust)", "Gloves"],
    regs: ["COSHH 2002", "Silica guidance (HSE)", "PUWER 1998"],
    permitTypes: ["cold_work", "excavation"],
    requiredCerts: ["Core drill operator competence"],
  },
  {
    id: "si_011",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Ground gas & VOC monitoring during intrusive GI",
    hazard: "Asphyxiation; explosion; toxic vapours; confined borehole headspace; hot weather volatilisation",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Desk study for landfill/contamination; monitoring plan with trigger levels",
      "Continuous or periodic gas monitor at borehole/trial pit; ventilate before leaning over holes",
      "Stop work and increase monitoring if LEL/O₂/CO₂/H₂S thresholds exceeded",
      "No smoking/hot work near monitoring points; record weather and ground conditions",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gas monitor", "Gloves"],
    regs: ["Confined Spaces Regs 1997", "CIRIA C665", "COSHH 2002"],
    permitTypes: ["confined_space", "ground_disturbance"],
    requiredCerts: ["Gas monitor competence", "Ground gas awareness"],
  },
  {
    id: "si_012",
    sector: "construction",
    category: "Site Investigation & Geotechnics",
    activity: "Trial pit logging & sample recovery (hand dig finish)",
    hazard: "Collapse; manual handling; sharp tools; biological hazards; lone working in pit",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "No lone working in excavations; ladder access every 25 m max",
      "Hand dig within tolerance of services; shoring if depth > 1.2 m (or per AP assessment)",
      "Log face immediately; photograph strata; bag and label samples on site",
      "Backfill and compact in layers; reinstate surface same shift where practicable",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Hard hat", "Hi-vis", "Safety footwear", "Gloves", "Knee pads"],
    regs: ["HSG185", "HSG47", "CDM 2015"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["GI logging / geology awareness", "CAT/Genny competence"],
  },
];

export default SITE_INVESTIGATION_LIBRARY;
