/**
 * Polska biblioteka zagrożeń do IBWR — treść po polsku, z odwołaniami do polskich przepisów.
 *
 * Do tej pory rynek PL korzystał z bibliotek UK, więc dokument wychodzący na budowę miał
 * angielskie opisy zagrożeń i brytyjskie podstawy prawne. Te wpisy są pisane od zera pod
 * polską praktykę: prace szczególnie niebezpieczne, zezwolenia, UDT/SEP, badania i nadzór.
 *
 * Identyfikatory mają przedrostek `pl_`, dzięki czemu biblioteka pokazuje się wyłącznie
 * w obszarze roboczym ustawionym na rynek PL (patrz ramsHazardLibraryLoader.js).
 */

export const PL_HAZARD_CATEGORIES = [
  "PL — Roboty szczególnie niebezpieczne",
  "PL — Roboty ziemne i wykopy",
  "PL — Praca na wysokości i rusztowania",
  "PL — Instalacje elektryczne",
  "PL — Maszyny i transport",
  "PL — Czynniki szkodliwe",
  "PL — Organizacja placu budowy",
  "PL — Rozbiórki i azbest",
  "PL — Przestrzenie zamknięte",
  "PL — Zakład produkcji żywności",
];

const PL_HAZARD_LIBRARY = [
  // ── ROBOTY SZCZEGÓLNIE NIEBEZPIECZNE ────────────────────────────────────────
  {
    id: "pl_psn_001",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty szczególnie niebezpieczne",
    activity: "Organizacja robót szczególnie niebezpiecznych",
    hazard:
      "Rozpoczęcie prac bez zezwolenia i bezpośredniego nadzoru; brak instruktażu; przypadkowe wejście osób postronnych w strefę prac",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Wykaz prac szczególnie niebezpiecznych ustalony przez pracodawcę i znany kierownictwu budowy",
      "Pisemne zezwolenie wydane przed rozpoczęciem prac; jeden egzemplarz u wykonującego pracę",
      "Bezpośredni nadzór wyznaczonej osoby przez cały czas trwania prac",
      "Instruktaż stanowiskowy z omówieniem IBWR potwierdzony podpisami brygady",
      "Imienny podział pracy, kolejność zadań i wymagane środki ochrony ustalone przed startem",
      "Strefa prac wygrodzona i oznakowana; osoby postronne poza strefą",
      "Środki łączności i sposób wezwania pomocy sprawdzone przed rozpoczęciem",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza", "Rękawice"],
    regs: [
      "Kodeks pracy art. 207 i 2373",
      "Rozporządzenie — ogólne przepisy BHP § 80–88",
      "Rozporządzenie MI z 6.02.2003 (BHP przy robotach budowlanych)",
    ],
    permitTypes: ["general"],
    requiredCerts: ["bhp_okresowe", "badania_profilaktyczne"],
  },
  {
    id: "pl_psn_002",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty szczególnie niebezpieczne",
    activity: "Prace w obiekcie czynnym / przy ruchu zakładu",
    hazard:
      "Uruchomienie instalacji w trakcie prac; kolizja z ruchem zakładu; brak koordynacji między pracodawcami na jednym terenie",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Koordynator BHP wyznaczony na piśmie, gdy na terenie pracuje kilku pracodawców",
      "Zakres, granice i harmonogram prac uzgodnione z użytkownikiem obiektu przed wejściem",
      "Instalacje w strefie prac odcięte i zabezpieczone przed uruchomieniem (LOTO)",
      "Strefa prac oddzielona od ruchu zakładu; drogi ewakuacyjne utrzymane w przejezdności",
      "Codzienna odprawa koordynacyjna ze wszystkimi brygadami na terenie",
      "Zasady alarmowania i sygnał ewakuacyjny obiektu omówione z brygadą",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Kodeks pracy art. 208", "Rozporządzenie — ogólne przepisy BHP", "Prawo budowlane"],
    permitTypes: ["general", "cold_work"],
    requiredCerts: ["bhp_okresowe", "bhp_wstepne"],
  },

  // ── ROBOTY ZIEMNE I WYKOPY ──────────────────────────────────────────────────
  {
    id: "pl_ziem_001",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty ziemne i wykopy",
    activity: "Wykop wąskoprzestrzenny i praca w wykopie",
    hazard:
      "Obsunięcie się ścian wykopu i przysypanie pracownika; upadek do wykopu; brak bezpiecznego zejścia",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Wykop powyżej 1 m z obudową lub skarpowaniem wykonanym zgodnie z dokumentacją",
      "Odkład urobku i sprzęt co najmniej 0,6 m od krawędzi wykopu",
      "Zejścia do wykopu nie rzadziej niż co 20 m; drabina wystaje 0,75 m ponad krawędź",
      "Balustrady przy wykopie w miejscach ruchu pieszych; oznakowanie i oświetlenie po zmroku",
      "Codzienny przegląd stanu obudowy oraz kontrola po opadach i mrozie",
      "Praca w wykopie powyżej 1,5 m wyłącznie pod bezpośrednim nadzorem",
      "Zakaz przebywania pod pracującą łyżką koparki i w strefie niebezpiecznej maszyny",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza", "Rękawice"],
    regs: [
      "Rozporządzenie MI z 6.02.2003 — rozdział o robotach ziemnych",
      "Rozporządzenie — ogólne przepisy BHP",
    ],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["bhp_okresowe", "badania_profilaktyczne"],
  },
  {
    id: "pl_ziem_002",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty ziemne i wykopy",
    activity: "Roboty ziemne w rejonie uzbrojenia podziemnego",
    hazard:
      "Uszkodzenie kabla, gazociągu lub wodociągu; porażenie prądem; wybuch gazu; zalanie wykopu",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Mapa zasadnicza z uzbrojeniem i uzgodnienia z gestorami sieci pozyskane przed wejściem na teren",
      "Trasowanie sieci lokalizatorem, wyniki naniesione na terenie i udokumentowane",
      "Przekopy kontrolne wykonywane ręcznie w strefach kolizji, zgodnie z warunkami gestora",
      "Zakaz pracy sprzętem mechanicznym w odległości mniejszej niż wskazana przez gestora sieci",
      "Odkryte sieci podwieszone i zabezpieczone przed uszkodzeniem",
      "Postępowanie przy uszkodzeniu sieci omówione z brygadą — ewakuacja, numer alarmowy, powiadomienie gestora",
      "Nadzór branżowy gestora wezwany tam, gdzie wymagają tego warunki uzgodnienia",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza", "Rękawice dielektryczne przy kolizji z kablem"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Prawo budowlane", "Prawo geodezyjne i kartograficzne"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["bhp_okresowe", "operator_maszyn"],
  },
  {
    id: "pl_ziem_003",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty ziemne i wykopy",
    activity: "Praca koparki i transport urobku",
    hazard:
      "Najechanie lub przygniecenie przez maszynę; kontakt z obracającym się nadwoziem; wywrócenie maszyny na krawędzi wykopu",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Operator z ważnymi uprawnieniami na daną klasę maszyny (książka operatora)",
      "Strefa niebezpieczna maszyny wyznaczona i oznakowana; zakaz wejścia w zasięg pracy",
      "Sygnalista wyznaczony przy ograniczonej widoczności i przy cofaniu",
      "Podłoże pod maszyną sprawdzone; zachowana odległość bezpieczna od krawędzi wykopu",
      "Kontrola maszyny przed zmianą (OT/DTR) odnotowana w książce maszyny",
      "Ruch pieszych i pojazdów rozdzielony na drogach wewnętrznych budowy",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza", "Ochronniki słuchu"],
    regs: [
      "Rozporządzenie MG z 20.09.2001 (maszyny do robót ziemnych, budowlanych i drogowych)",
      "Rozporządzenie MG z 30.10.2002 (minimalne wymagania — użytkowanie maszyn)",
    ],
    permitTypes: ["excavation"],
    requiredCerts: ["operator_maszyn", "badania_profilaktyczne"],
  },
  {
    id: "pl_ziem_004",
    market: "pl",
    sector: "construction",
    category: "PL — Roboty ziemne i wykopy",
    activity: "Odwodnienie wykopu i praca w wodzie gruntowej",
    hazard:
      "Upłynnienie dna wykopu i utrata stateczności; osiadanie obiektów sąsiednich; poślizgnięcie w błocie; zanieczyszczenie wód",
    initialRisk: { L: 3, S: 5, RF: 15 },
    controlMeasures: [
      "Projekt odwodnienia i zgoda na odprowadzenie wody uzgodnione przed rozpoczęciem",
      "Monitoring poziomu wody i osiadań obiektów sąsiednich z progami alarmowymi",
      "Pompy zabezpieczone, z rezerwą i zasilaniem awaryjnym na czas prac w dnie wykopu",
      "Woda z wykopu podczyszczana z zawiesiny przed zrzutem",
      "Pomosty i trapy w miejscach stałego przejścia; obuwie gumowe dla brygady",
      "Wstrzymanie prac w dnie wykopu przy oznakach napływu lub wypierania gruntu",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Kask", "Obuwie gumowe ochronne", "Odzież przeciwdeszczowa", "Odzież ostrzegawcza"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Prawo wodne", "Prawo budowlane"],
    permitTypes: ["excavation", "ground_disturbance"],
    requiredCerts: ["bhp_okresowe"],
  },

  // ── PRACA NA WYSOKOŚCI I RUSZTOWANIA ────────────────────────────────────────
  {
    id: "pl_wys_001",
    market: "pl",
    sector: "construction",
    category: "PL — Praca na wysokości i rusztowania",
    activity: "Praca na wysokości przy niezabezpieczonych krawędziach",
    hazard: "Upadek z wysokości przez otwór technologiczny lub niezabezpieczoną krawędź stropu",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Balustrady ochronne: poręcz na wysokości 1,1 m, przechwyt w połowie i bortnica 0,15 m",
      "Otwory w stropach zakryte pomostem przenoszącym obciążenie lub wygrodzone",
      "Środki ochrony indywidualnej (szelki, lonża z amortyzatorem) tam, gdzie nie da się zastosować ochron zbiorowych",
      "Punkty kotwiczenia wskazane przez osobę uprawnioną; nośność potwierdzona",
      "Aktualne orzeczenie lekarskie o zdolności do pracy na wysokości powyżej 3 m",
      "Plan ewakuacji z zawieszenia w szelkach ustalony przed rozpoczęciem prac",
      "Wstrzymanie prac przy wietrze powyżej 10 m/s, oblodzeniu, gęstej mgle i burzy",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask z paskiem podbródkowym", "Szelki bezpieczeństwa", "Lonża z amortyzatorem", "Obuwie ochronne"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP § 105–110",
      "Rozporządzenie MI z 6.02.2003",
      "Rozporządzenie MZiOS z 30.05.1996 (badania profilaktyczne)",
    ],
    permitTypes: ["work_at_height"],
    requiredCerts: ["badania_wysokosc", "working_at_height", "bhp_okresowe"],
  },
  {
    id: "pl_wys_002",
    market: "pl",
    sector: "construction",
    category: "PL — Praca na wysokości i rusztowania",
    activity: "Montaż, odbiór i użytkowanie rusztowania",
    hazard:
      "Zawalenie rusztowania; upadek podczas montażu; użytkowanie rusztowania bez odbioru; przeciążenie pomostu",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Montaż i demontaż wyłącznie przez osoby z uprawnieniami do montażu rusztowań",
      "Montaż zgodnie z instrukcją producenta lub projektem dla rusztowania nietypowego",
      "Odbiór rusztowania protokolarny przez kierownika budowy; tabliczka z dopuszczalnym obciążeniem",
      "Zakaz użytkowania rusztowania bez tabliczki odbioru — dostęp fizycznie zablokowany do czasu odbioru",
      "Kotwienie i stężenia zgodne z dokumentacją; sprawdzenie po wietrze i po przerwie w pracy",
      "Pomosty pełne, z balustradami i bortnicą; brak przerw w poszyciu",
      "Zachowana odległość bezpieczna od napowietrznych linii energetycznych",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask z paskiem podbródkowym", "Szelki bezpieczeństwa przy montażu", "Obuwie ochronne", "Rękawice"],
    regs: ["Rozporządzenie MI z 6.02.2003 — rusztowania", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["work_at_height"],
    requiredCerts: ["rusztowania", "badania_wysokosc"],
  },
  {
    id: "pl_wys_003",
    market: "pl",
    sector: "construction",
    category: "PL — Praca na wysokości i rusztowania",
    activity: "Podesty ruchome (PRL) i drabiny",
    hazard:
      "Wywrócenie podestu; wypadnięcie z kosza; upadek z drabiny; praca z drabiny zamiast z podestu",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Podest z ważną decyzją zezwalającą UDT na eksploatację; dziennik konserwacji aktualny",
      "Operator z uprawnieniami UDT właściwej kategorii (I P / II P)",
      "Codzienna kontrola podestu przed pracą; podłoże nośne, podpory na płytach",
      "Szelki z lonżą krótką przypięte do punktu w koszu — bez wychodzenia z kosza na wysokości",
      "Drabina tylko jako dojście lub do prac krótkotrwałych; ustawiona pod kątem 65–75° i zabezpieczona",
      "Strefa pracy podestu wygrodzona; kontrola przeszkód i linii napowietrznych nad stanowiskiem",
      "Procedura awaryjnego opuszczenia kosza omówiona przed rozpoczęciem prac",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask", "Szelki z lonżą krótką", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Ustawa o dozorze technicznym", "Rozporządzenie MI z 6.02.2003", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["work_at_height"],
    requiredCerts: ["udt_podesty", "badania_wysokosc"],
  },
  {
    id: "pl_wys_004",
    market: "pl",
    sector: "construction",
    category: "PL — Praca na wysokości i rusztowania",
    activity: "Prace na dachu i pokryciach kruchych",
    hazard: "Przebicie pokrycia i upadek przez świetlik lub płytę falistą; zsunięcie z połaci; zdmuchnięcie materiału",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Przegląd dachu przed wejściem; świetliki i pokrycia kruche oznakowane lub zakryte",
      "Wyznaczona trasa dojścia — bez chodzenia po pokryciu kruchym; pomosty rozkładające obciążenie",
      "Zabezpieczenie krawędzi: balustrady, siatki lub system asekuracji z liną kotwiczącą",
      "Materiały i narzędzia zabezpieczone przed zsunięciem; strefa pod okapem wygrodzona",
      "Wstrzymanie prac przy oblodzeniu, śniegu, deszczu i wietrze powyżej 10 m/s",
      "Ustalona maksymalna liczba osób na połaci; kontrola dachu po zakończeniu zmiany",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask z paskiem", "Szelki bezpieczeństwa", "Obuwie o podeszwie antypoślizgowej"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["roof_access", "work_at_height"],
    requiredCerts: ["badania_wysokosc", "working_at_height"],
  },
  {
    id: "pl_wys_005",
    market: "pl",
    sector: "construction",
    category: "PL — Praca na wysokości i rusztowania",
    activity: "Spadające przedmioty i strefa niebezpieczna",
    hazard: "Uderzenie spadającym materiałem lub narzędziem; upuszczenie elementu poza strefę wygrodzoną",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Strefa niebezpieczna wyznaczona i wygrodzona — co najmniej 1/10 wysokości, nie mniej niż 6 m",
      "Daszki ochronne nad wejściami i ciągami pieszych utrzymywanymi w ruchu",
      "Narzędzia zabezpieczone linkami przy pracy na wysokości",
      "Materiał podawany dźwigiem lub wciągarką — zakaz zrzucania z wysokości",
      "Bortnice na pomostach i siatki zabezpieczające przy rusztowaniu",
      "Kontrola wygrodzeń na początku każdej zmiany",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask", "Obuwie ochronne z podnoskiem", "Odzież ostrzegawcza"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["work_at_height", "general"],
    requiredCerts: ["bhp_okresowe"],
  },

  // ── INSTALACJE ELEKTRYCZNE ──────────────────────────────────────────────────
  {
    id: "pl_ele_001",
    market: "pl",
    sector: "construction",
    category: "PL — Instalacje elektryczne",
    activity: "Prace przy instalacjach i urządzeniach elektrycznych",
    hazard: "Porażenie prądem elektrycznym; łuk elektryczny; ponowne załączenie zasilania w trakcie prac",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Prace wykonywane przez osoby z ważnym świadectwem kwalifikacyjnym SEP grupy G1 (E), nadzór — D",
      "Wyłączenie, zabezpieczenie przed załączeniem (LOTO) i wywieszenie tablic ostrzegawczych",
      "Sprawdzenie braku napięcia przyrządem sprawdzonym bezpośrednio przed i po pomiarze",
      "Uziemienie robocze tam, gdzie wymagane; oznaczenie miejsca pracy",
      "Polecenie pisemne dla prac w warunkach szczególnego zagrożenia; asekuracja drugiej osoby",
      "Zakaz pracy pod napięciem bez odrębnej technologii i uprawnień PPN",
      "Przywrócenie zasilania wyłącznie przez osobę, która wykonała wyłączenie",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Rękawice dielektryczne", "Osłona twarzy", "Obuwie elektroizolacyjne", "Odzież trudnopalna"],
    regs: [
      "Rozporządzenie MKiŚ z 1.07.2022 (kwalifikacje — eksploatacja urządzeń, instalacji i sieci)",
      "Rozporządzenie — ogólne przepisy BHP",
      "Rozporządzenie MI z 6.02.2003",
    ],
    permitTypes: ["electrical", "cold_work"],
    requiredCerts: ["sep_e", "electrical_loto", "badania_profilaktyczne"],
  },
  {
    id: "pl_ele_002",
    market: "pl",
    sector: "construction",
    category: "PL — Instalacje elektryczne",
    activity: "Zasilanie placu budowy — rozdzielnice i przewody",
    hazard:
      "Porażenie z uszkodzonego przedłużacza; brak wyłącznika różnicowoprądowego; zalanie rozdzielnicy; przeciążenie obwodu",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Rozdzielnice budowlane w wykonaniu przemysłowym, zamykane, z wyłącznikami różnicowoprądowymi",
      "Pomiary ochronne instalacji placu budowy wykonane i udokumentowane; protokoły dostępne",
      "Przewody prowadzone na wysokości lub w osłonach — nie po drogach komunikacyjnych",
      "Codzienne oględziny przewodów i narzędzi; sprzęt uszkodzony natychmiast wycofany i oznakowany",
      "Zakaz stosowania przedłużaczy domowych i rozgałęźników bez ochrony przeciwporażeniowej",
      "Osprzęt o odpowiednim stopniu ochrony IP dla warunków zewnętrznych",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Obuwie ochronne", "Rękawice", "Kask"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Rozporządzenie — ogólne przepisy BHP", "Prawo budowlane"],
    permitTypes: ["electrical", "general"],
    requiredCerts: ["sep_e", "bhp_okresowe"],
  },
  {
    id: "pl_ele_003",
    market: "pl",
    sector: "construction",
    category: "PL — Instalacje elektryczne",
    activity: "Prace w pobliżu napowietrznej linii energetycznej",
    hazard: "Zbliżenie masztu, wysięgnika lub ładunku do przewodów pod napięciem; przeskok łuku bez dotknięcia",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Ustalenie napięcia linii i wymaganej strefy niebezpiecznej z zarządcą sieci przed rozpoczęciem prac",
      "Wyłączenie linii lub zastosowanie osłon izolacyjnych uzgodnionych z zarządcą",
      "Bramki ograniczające wysokość i oznakowanie przejazdów pod linią",
      "Ograniczniki wysięgu i obrotu ustawione w maszynach pracujących w pobliżu linii",
      "Sygnalista obserwujący zbliżenie do linii przy każdej pracy sprzętem",
      "Zakaz składowania materiałów i postoju maszyn pod linią",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["general", "lifting"],
    requiredCerts: ["bhp_okresowe", "operator_maszyn"],
  },

  // ── MASZYNY I TRANSPORT ─────────────────────────────────────────────────────
  {
    id: "pl_masz_001",
    market: "pl",
    sector: "construction",
    category: "PL — Maszyny i transport",
    activity: "Prace dźwigowe żurawiem",
    hazard: "Upadek ładunku; przeciążenie żurawia; kolizja z obiektem; uderzenie ładunkiem osoby w strefie",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Plan pracy żurawia sporządzony przez osobę uprawnioną i omówiony z obsługą",
      "Ważna decyzja UDT zezwalająca na eksploatację; dziennik konserwacji prowadzony na bieżąco",
      "Operator z uprawnieniami UDT właściwej kategorii; hakowy i sygnalista wyznaczeni imiennie",
      "Zawiesia z aktualnym przeglądem, dobrane do masy ładunku i kąta rozwarcia cięgien",
      "Masa ładunku potwierdzona przed podniesieniem; brak przekroczenia DOR",
      "Strefa pod ładunkiem wygrodzona; zakaz przenoszenia ładunku nad ludźmi",
      "Praca wstrzymana przy wietrze przekraczającym limit producenta i przy złej widoczności",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza", "Rękawice"],
    regs: ["Ustawa o dozorze technicznym", "Rozporządzenie MI z 6.02.2003", "Rozporządzenie MG z 30.10.2002"],
    permitTypes: ["lifting"],
    requiredCerts: ["udt_zurawie", "slinger_signaller"],
  },
  {
    id: "pl_masz_002",
    market: "pl",
    sector: "construction",
    category: "PL — Maszyny i transport",
    activity: "Transport wewnętrzny i wózki jezdniowe",
    hazard: "Najechanie na pieszego; przewrócenie wózka; upadek ładunku z wideł; kolizja na drodze wewnętrznej",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Operator z ważnymi uprawnieniami UDT na wózki jezdniowe podnośnikowe",
      "Drogi wewnętrzne wyznaczone i oznakowane; ruch pieszych oddzielony od ruchu pojazdów",
      "Ograniczenie prędkości i pierwszeństwo pieszych ustalone w regulaminie placu budowy",
      "Kontrola wózka przed zmianą; wyposażenie w sygnał dźwiękowy i światło ostrzegawcze",
      "Ładunek zabezpieczony i w granicach udźwigu wskazanego na tabliczce",
      "Zakaz przewożenia osób na widłach i na palecie",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Ustawa o dozorze technicznym", "Rozporządzenie MG z 30.10.2002", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["general"],
    requiredCerts: ["udt_wozki", "badania_profilaktyczne"],
  },
  {
    id: "pl_masz_003",
    market: "pl",
    sector: "construction",
    category: "PL — Maszyny i transport",
    activity: "Narzędzia z napędem i osłony maszyn",
    hazard: "Kontakt z częścią wirującą; odrzucenie odłamka; odbicie tarczy; brak lub demontaż osłony",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Narzędzia wyposażone w komplet osłon; zakaz pracy narzędziem z usuniętą osłoną",
      "Tarcze i osprzęt dobrane do maszyny i materiału; kontrola przed każdym użyciem",
      "Kontrola stanu technicznego narzędzi wpisana do harmonogramu; sprzęt niesprawny oznakowany i wycofany",
      "Wyłącznik samoczynnie powracający i zabezpieczenie przed przypadkowym rozruchem",
      "Ochrona oczu obowiązkowa przy cięciu, szlifowaniu i wbijaniu",
      "Instruktaż stanowiskowy dla każdego nowego narzędzia potwierdzony podpisem",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Okulary ochronne", "Rękawice antyprzecięciowe", "Ochronniki słuchu", "Półmaska przy pyleniu"],
    regs: ["Rozporządzenie MG z 30.10.2002", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["general"],
    requiredCerts: ["bhp_stanowisko", "bhp_okresowe"],
  },

  // ── CZYNNIKI SZKODLIWE ──────────────────────────────────────────────────────
  {
    id: "pl_czyn_001",
    market: "pl",
    sector: "construction",
    category: "PL — Czynniki szkodliwe",
    activity: "Cięcie i szlifowanie materiałów budowlanych — pył",
    hazard: "Narażenie na pył zawierający krystaliczną krzemionkę; pylica i przewlekłe choroby układu oddechowego",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Cięcie na mokro lub z odciągiem miejscowym jako rozwiązanie podstawowe",
      "Odpylacz klasy M lub H sprawny i serwisowany; filtry wymieniane zgodnie z instrukcją",
      "Półmaski filtrujące co najmniej FFP3 przy pracach pylących, z dopasowaniem twarzowym",
      "Pomiary NDS wykonane dla stanowisk narażonych; wyniki w rejestrze czynników szkodliwych",
      "Ograniczenie liczby osób w strefie pylenia; wygrodzenie stanowiska",
      "Badania profilaktyczne z uwzględnieniem narażenia na pyły; rejestr narażenia prowadzony",
      "Sprzątanie na mokro lub odkurzaczem — zakaz zamiatania i przedmuchiwania sprężonym powietrzem",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Półmaska FFP3", "Okulary ochronne", "Ochronniki słuchu", "Odzież robocza"],
    regs: [
      "Rozporządzenie MRPiPS z 12.06.2018 (NDS i NDN)",
      "Rozporządzenie — ogólne przepisy BHP",
      "Rozporządzenie MZiOS z 30.05.1996 (badania profilaktyczne)",
    ],
    permitTypes: ["general"],
    requiredCerts: ["badania_profilaktyczne", "bhp_okresowe"],
  },
  {
    id: "pl_czyn_002",
    market: "pl",
    sector: "construction",
    category: "PL — Czynniki szkodliwe",
    activity: "Narażenie na hałas i drgania mechaniczne",
    hazard: "Trwały ubytek słuchu; zespół wibracyjny przy pracy młotami i zagęszczarkami",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Pomiary hałasu i drgań na stanowiskach; wyniki w rejestrze czynników szkodliwych",
      "Sprzęt o niższej emisji dobierany na etapie zakupu i najmu",
      "Ochronniki słuchu obowiązkowe po przekroczeniu progu działania; strefy oznakowane",
      "Rotacja pracowników i limity czasu pracy narzędziami udarowymi",
      "Rękawice antywibracyjne i przerwy w ekspozycji przy pracy narzędziami udarowymi",
      "Badania profilaktyczne uwzględniające narażenie na hałas i drgania",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Ochronniki słuchu", "Rękawice antywibracyjne", "Okulary ochronne"],
    regs: ["Rozporządzenie MGiP z 5.08.2005 (hałas i drgania)", "Rozporządzenie MRPiPS z 12.06.2018 (NDS i NDN)"],
    permitTypes: ["general"],
    requiredCerts: ["badania_profilaktyczne"],
  },
  {
    id: "pl_czyn_003",
    market: "pl",
    sector: "construction",
    category: "PL — Czynniki szkodliwe",
    activity: "Stosowanie substancji i mieszanin chemicznych",
    hazard: "Poparzenie chemiczne; zatrucie oparami; uczulenie skórne; pożar przy substancjach łatwopalnych",
    initialRisk: { L: 3, S: 5, RF: 15 },
    controlMeasures: [
      "Karty charakterystyki dostępne na budowie dla każdej stosowanej substancji",
      "Spis substancji niebezpiecznych prowadzony i aktualizowany",
      "Instruktaż stanowiskowy obejmujący zagrożenia, ŚOI i postępowanie przy rozlaniu",
      "Wentylacja lub praca na zewnątrz przy substancjach lotnych; zakaz pracy w zamkniętej przestrzeni bez wentylacji",
      "Substancje przechowywane w oryginalnych, oznakowanych opakowaniach, w wydzielonym miejscu",
      "Sorbenty i oczomyjka dostępne w miejscu stosowania",
      "Odpady chemiczne segregowane i przekazywane uprawnionemu odbiorcy",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Rękawice chemoodporne", "Okulary lub gogle ochronne", "Półmaska z pochłaniaczem", "Fartuch ochronny"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP",
      "Ustawa o substancjach chemicznych i ich mieszaninach",
      "Rozporządzenie MRPiPS z 12.06.2018 (NDS i NDN)",
    ],
    permitTypes: ["general", "line_break"],
    requiredCerts: ["bhp_stanowisko", "badania_profilaktyczne"],
  },
  {
    id: "pl_czyn_004",
    market: "pl",
    sector: "construction",
    category: "PL — Czynniki szkodliwe",
    activity: "Ręczne prace transportowe",
    hazard: "Uraz kręgosłupa przy podnoszeniu; przygniecenie palców; poślizgnięcie przy przenoszeniu materiału",
    initialRisk: { L: 4, S: 3, RF: 12 },
    controlMeasures: [
      "Dopuszczalne masy przestrzegane: praca stała 12 kg (kobiety) i 30 kg (mężczyźni), dorywcza odpowiednio 20 i 50 kg",
      "Środki pomocnicze (wózki, podnośniki, uchwyty) dostępne przy powtarzalnym transporcie",
      "Przenoszenie zespołowe przy elementach o dużej masie lub wymiarach",
      "Drogi transportu utrzymane w czystości, oświetlone i bez przeszkód",
      "Instruktaż techniki podnoszenia w ramach instruktażu stanowiskowego",
      "Materiał składowany na wysokości ułatwiającej podjęcie, bez sięgania nad głowę",
    ],
    revisedRisk: { L: 2, S: 3, RF: 6 },
    ppeRequired: ["Rękawice", "Obuwie ochronne z podnoskiem", "Kask"],
    regs: ["Rozporządzenie MPiPS z 14.03.2000 (ręczne prace transportowe)", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["general"],
    requiredCerts: ["manual_handling", "bhp_stanowisko"],
  },
  {
    id: "pl_czyn_005",
    market: "pl",
    sector: "construction",
    category: "PL — Czynniki szkodliwe",
    activity: "Praca w upale i w warunkach zimowych",
    hazard: "Przegrzanie i odwodnienie latem; wychłodzenie i odmrożenia zimą; poślizgnięcia na oblodzeniu",
    initialRisk: { L: 3, S: 4, RF: 12 },
    controlMeasures: [
      "Napoje profilaktyczne zapewnione przy pracy w wysokich i niskich temperaturach",
      "Zacienione lub ogrzewane miejsce odpoczynku dostępne na terenie budowy",
      "Przerwy regeneracyjne planowane w najcieplejszych i najzimniejszych godzinach",
      "Odzież dostosowana do warunków; odzież ciepłochronna zapewniona przy pracy na zewnątrz zimą",
      "Powierzchnie komunikacyjne odśnieżane i posypywane; usuwanie sopli z krawędzi",
      "Objawy przegrzania i wychłodzenia omówione na odprawie; zasada wzajemnej obserwacji w brygadzie",
    ],
    revisedRisk: { L: 2, S: 3, RF: 6 },
    ppeRequired: ["Odzież dostosowana do pory roku", "Nakrycie głowy pod kask", "Obuwie antypoślizgowe"],
    regs: ["Rozporządzenie — ogólne przepisy BHP", "Rozporządzenie RM w sprawie posiłków i napojów profilaktycznych"],
    permitTypes: ["general"],
    requiredCerts: ["bhp_okresowe"],
  },

  // ── ORGANIZACJA PLACU BUDOWY ────────────────────────────────────────────────
  {
    id: "pl_org_001",
    market: "pl",
    sector: "construction",
    category: "PL — Organizacja placu budowy",
    activity: "Zagospodarowanie placu budowy i drogi komunikacyjne",
    hazard:
      "Potknięcia i upadki na poziomie; wejście osób postronnych na teren; brak zaplecza i punktu pierwszej pomocy",
    initialRisk: { L: 4, S: 3, RF: 12 },
    controlMeasures: [
      "Teren budowy ogrodzony i oznakowany tablicą informacyjną zgodnie z Prawem budowlanym",
      "Drogi komunikacyjne i ciągi piesze wyznaczone, utwardzone i oświetlone",
      "Zaplecze higienicznosanitarne (szatnie, umywalnie, toalety, jadalnia) zapewnione przed rozpoczęciem robót",
      "Punkt pierwszej pomocy oznakowany; apteczki wyposażone i osoby wyznaczone przeszkolone",
      "Porządek na stanowiskach utrzymywany na bieżąco; odpady segregowane i usuwane",
      "Plan zagospodarowania placu budowy aktualizowany przy zmianie etapu robót",
      "Tablice informacyjne z numerami alarmowymi i adresem budowy w widocznym miejscu",
    ],
    revisedRisk: { L: 2, S: 3, RF: 6 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Rozporządzenie MI z 6.02.2003", "Prawo budowlane", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["general", "visitor_access"],
    requiredCerts: ["bhp_wstepne", "first_aid"],
  },
  {
    id: "pl_org_002",
    market: "pl",
    sector: "construction",
    category: "PL — Organizacja placu budowy",
    activity: "Prace niebezpieczne pożarowo i ewakuacja",
    hazard: "Pożar od iskier ze spawania lub cięcia; zadymienie dróg ewakuacyjnych; brak sprzętu gaśniczego",
    initialRisk: { L: 3, S: 6, RF: 18 },
    controlMeasures: [
      "Pisemne zezwolenie na prace niebezpieczne pożarowo wydane przed rozpoczęciem",
      "Materiały palne usunięte lub zabezpieczone w promieniu 10 m od miejsca prac",
      "Sprzęt gaśniczy na stanowisku; osoba do zabezpieczenia prac wyznaczona i przeszkolona",
      "Kontrola miejsca prac po 1 h i ponownie po 8 h od zakończenia",
      "Drogi ewakuacyjne i wyjścia utrzymane w przejezdności przez cały czas robót",
      "Punkt zbiórki wyznaczony i znany brygadzie; próbna ewakuacja przy dłuższych inwestycjach",
      "Zakaz pracy z otwartym ogniem w strefach oznaczonych bez odrębnego uzgodnienia",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Odzież trudnopalna przy spawaniu", "Przyłbica spawalnicza", "Rękawice spawalnicze", "Obuwie ochronne"],
    regs: [
      "Rozporządzenie MSWiA z 7.06.2010 (ochrona przeciwpożarowa budynków)",
      "Ustawa o ochronie przeciwpożarowej",
      "Rozporządzenie MI z 6.02.2003",
    ],
    permitTypes: ["hot_work"],
    requiredCerts: ["hot_work_fire_watch", "spawanie", "ppoz"],
  },
  {
    id: "pl_org_003",
    market: "pl",
    sector: "construction",
    category: "PL — Organizacja placu budowy",
    activity: "Praca jednoosobowa i łączność na budowie",
    hazard: "Brak pomocy po wypadku przy pracy w pojedynkę; utrata łączności; opóźnione wezwanie służb",
    initialRisk: { L: 3, S: 5, RF: 15 },
    controlMeasures: [
      "Zakaz pracy jednoosobowej przy pracach szczególnie niebezpiecznych",
      "System meldowania: godziny kontaktu ustalone, brak meldunku uruchamia procedurę poszukiwania",
      "Telefon z naładowanym akumulatorem i zasięgiem sprawdzonym w miejscu pracy",
      "Adres budowy i dojazd dla służb ratunkowych zapisane i dostępne dla pracownika",
      "Osoba kontaktowa wyznaczona na każdą zmianę i znana pracownikowi",
      "Ocena ryzyka pracy jednoosobowej wykonana i omówiona przed rozpoczęciem",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Odzież ostrzegawcza", "Kask", "Obuwie ochronne"],
    regs: ["Kodeks pracy art. 207", "Rozporządzenie — ogólne przepisy BHP"],
    permitTypes: ["night_works", "general"],
    requiredCerts: ["bhp_okresowe", "first_aid"],
  },
  {
    id: "pl_org_004",
    market: "pl",
    sector: "construction",
    category: "PL — Organizacja placu budowy",
    activity: "Koordynacja podwykonawców na jednym terenie",
    hazard:
      "Prace kolidujące prowadzone jednocześnie; brak wymiany informacji o zagrożeniach; różne zasady na jednym terenie",
    initialRisk: { L: 4, S: 4, RF: 16 },
    controlMeasures: [
      "Koordynator sprawujący nadzór nad BHP wyznaczony na piśmie przez pracodawców",
      "Wymiana IBWR i ocen ryzyka między wykonawcami przed rozpoczęciem robót kolidujących",
      "Cotygodniowa narada koordynacyjna z zapisem ustaleń i listą obecności",
      "Harmonogram robót rozdzielający prace kolidujące w czasie lub w przestrzeni",
      "Jednolity regulamin placu budowy obowiązujący wszystkich wykonawców",
      "Weryfikacja kwalifikacji, badań i szkoleń pracowników podwykonawców przed wejściem na teren",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Kask", "Obuwie ochronne", "Odzież ostrzegawcza"],
    regs: ["Kodeks pracy art. 208", "Rozporządzenie MI z 23.06.2003 (plan BIOZ)", "Prawo budowlane"],
    permitTypes: ["general"],
    requiredCerts: ["bhp_okresowe", "sluzba_bhp"],
  },

  // ── ROZBIÓRKI I AZBEST ──────────────────────────────────────────────────────
  {
    id: "pl_roz_001",
    market: "pl",
    sector: "construction",
    category: "PL — Rozbiórki i azbest",
    activity: "Roboty rozbiórkowe",
    hazard: "Niekontrolowane zawalenie elementu; upadek gruzu; utrata stateczności konstrukcji sąsiedniej",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Projekt rozbiórki i kolejność demontażu opracowane przez osobę z uprawnieniami",
      "Instalacje odcięte i potwierdzone jako bezpieczne przed rozpoczęciem rozbiórki",
      "Strefa niebezpieczna wygrodzona; obiekty sąsiednie zabezpieczone i monitorowane",
      "Zakaz przebywania ludzi w rozbieranym obiekcie podczas pracy sprzętu",
      "Gruz usuwany rynnami zsypowymi lub transportem mechanicznym — zakaz zrzucania z wysokości",
      "Zraszanie w celu ograniczenia pylenia; ochrona wpustów kanalizacyjnych",
      "Codzienna ocena stateczności przez kierownika robót przed dopuszczeniem brygady",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Kask", "Okulary ochronne", "Półmaska FFP3", "Obuwie ochronne", "Rękawice"],
    regs: ["Rozporządzenie MI z 6.02.2003 — roboty rozbiórkowe", "Prawo budowlane"],
    permitTypes: ["general", "excavation"],
    requiredCerts: ["bhp_okresowe", "budowlane", "operator_maszyn"],
  },
  {
    id: "pl_roz_002",
    market: "pl",
    sector: "construction",
    category: "PL — Rozbiórki i azbest",
    activity: "Prace przy wyrobach zawierających azbest",
    hazard: "Uwolnienie włókien azbestu; narażenie pracowników i osób postronnych; nieprawidłowe składowanie odpadu",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Prace wykonywane przez wykonawcę posiadającego wymagane przeszkolenie i wyposażenie",
      "Zgłoszenie zamiaru prac właściwemu organowi z wyprzedzeniem wymaganym przepisami",
      "Strefa prac wygrodzona i oznakowana; ograniczenie liczby osób w strefie",
      "Zwilżanie wyrobów przed demontażem; demontaż bez łamania i kruszenia płyt",
      "Odpad pakowany szczelnie i oznakowany; przekazanie uprawnionemu odbiorcy z kartą przekazania odpadu",
      "Dekontaminacja pracowników i sprzętu przed opuszczeniem strefy",
      "Rejestr prac w kontakcie z azbestem i rejestr narażenia prowadzony dla pracowników",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Półmaska FFP3 lub aparat filtrowentylacyjny", "Kombinezon jednorazowy typ 5", "Rękawice", "Obuwie ochronne"],
    regs: [
      "Rozporządzenie MGPiPS z 2.04.2004 (bezpieczne użytkowanie i usuwanie azbestu)",
      "Rozporządzenie MGiP z 14.10.2005 (BHP przy usuwaniu azbestu)",
      "Ustawa o zakazie stosowania wyrobów zawierających azbest",
    ],
    permitTypes: ["general"],
    requiredCerts: ["asbestos_awareness", "badania_profilaktyczne"],
  },

  // ── PRZESTRZENIE ZAMKNIĘTE ──────────────────────────────────────────────────
  {
    id: "pl_pz_001",
    market: "pl",
    sector: "construction",
    category: "PL — Przestrzenie zamknięte",
    activity: "Wejście do studni, zbiornika lub komory",
    hazard:
      "Niedobór tlenu; obecność gazów toksycznych lub wybuchowych; zalanie; brak możliwości szybkiej ewakuacji poszkodowanego",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pisemne zezwolenie na wejście wydane po ocenie ryzyka dla konkretnej przestrzeni",
      "Pomiar atmosfery przed wejściem i pomiar ciągły w trakcie przebywania (tlen, gazy toksyczne, wybuchowość)",
      "Wentylacja mechaniczna uruchomiona przed wejściem i utrzymywana przez cały czas prac",
      "Asekurujący pozostaje na zewnątrz przez cały czas i nie wchodzi do środka w razie zdarzenia",
      "Sprzęt ratowniczy (trójnóg, wciągarka, szelki) rozstawiony przed wejściem",
      "Media odcięte i zabezpieczone przed uruchomieniem (LOTO); zaślepienie dopływów",
      "Łączność między wchodzącym a asekurującym sprawdzona; sposób wezwania służb ustalony",
      "Liczba osób i czas przebywania ograniczone i zapisane w zezwoleniu",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Szelki bezpieczeństwa z linką", "Detektor wielogazowy", "Kask", "Ubranie ochronne", "Sprzęt ucieczkowy"],
    regs: ["Rozporządzenie — ogólne przepisy BHP § 85–90", "Rozporządzenie MI z 6.02.2003"],
    permitTypes: ["confined_space"],
    requiredCerts: ["confined_space", "gas_tester", "badania_profilaktyczne"],
  },
  // ── ZAKŁAD PRODUKCJI ŻYWNOŚCI ───────────────────────────────────────────────
  {
    id: "pl_zyw_001",
    market: "pl",
    sector: "construction",
    category: "PL — Zakład produkcji żywności",
    activity: "Prace serwisowe i montażowe w czynnej strefie produkcyjnej",
    hazard:
      "Zanieczyszczenie produktu ciałem obcym lub smarem; przeniesienie alergenu między strefami; poślizgnięcie na mokrej posadzce; kontakt z ruchomymi elementami linii",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Zezwolenie na wejście do strefy produkcyjnej wydane przez produkcję lub dział jakości przed rozpoczęciem prac",
      "Aktualne orzeczenia do celów sanitarno-epidemiologicznych i szkolenie GHP/GMP dla całej ekipy",
      "Odzież ochronna zakładu, nakrycie głowy i obuwie strefowe; biżuteria i rzeczy osobiste zdeponowane",
      "Lista narzędzi spisana przed wejściem i rozliczona przy wyjściu — brak narzędzia zatrzymuje linię",
      "Namiot serwisowy lub osłony nad strefą prac; produkt i taśmy zabezpieczone przed opiłkami i smarem",
      "Smary dopuszczone do kontaktu z żywnością (klasa H1) tam, gdzie istnieje ryzyko kontaktu z produktem",
      "Linia zatrzymana i zabezpieczona przed uruchomieniem (LOTO) przed pracami przy elementach ruchomych",
      "Zwolnienie linii do produkcji dopiero po kontroli ciał obcych, myciu i podpisie produkcji oraz QA",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Odzież strefowa zakładu", "Nakrycie głowy", "Obuwie antypoślizgowe", "Rękawice", "Okulary ochronne"],
    regs: [
      "Rozporządzenie (WE) nr 852/2004 w sprawie higieny środków spożywczych",
      "Ustawa o bezpieczeństwie żywności i żywienia",
      "Zasady GHP/GMP i system HACCP zakładu",
      "Rozporządzenie — ogólne przepisy BHP",
    ],
    permitTypes: ["line_clearance", "cold_work", "general"],
    requiredCerts: ["orzeczenie_sanepid", "ghp_gmp", "bhp_okresowe"],
  },
  {
    id: "pl_zyw_002",
    market: "pl",
    sector: "construction",
    category: "PL — Zakład produkcji żywności",
    activity: "Mycie i dezynfekcja instalacji po pracach",
    hazard:
      "Poparzenie ługiem lub kwasem; uwolnienie oparów przy mieszaniu środków; poślizgnięcie na mokrej posadzce; pozostałość środka na powierzchni kontaktującej się z żywnością",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Karty charakterystyki wszystkich środków dostępne na stanowisku i omówione z brygadą",
      "Zakaz mieszania środków; stężenia i czas kontaktu według instrukcji zakładu",
      "Środki ochrony chemicznej: gogle, rękawice odporne chemicznie, fartuch i obuwie gumowe",
      "Oczomyjka i natrysk bezpieczeństwa sprawne i dostępne w strefie mycia",
      "Wygrodzenie i oznakowanie mokrej strefy; ograniczenie ruchu osób postronnych",
      "Spłukanie wodą zdatną do spożycia i potwierdzenie usunięcia pozostałości przed zwolnieniem strefy",
      "Protokół mycia i dezynfekcji podpisany przez wykonawcę oraz dział jakości",
    ],
    revisedRisk: { L: 2, S: 4, RF: 8 },
    ppeRequired: ["Gogle ochronne", "Rękawice chemoodporne", "Fartuch kwasoodporny", "Obuwie gumowe antypoślizgowe"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP",
      "Rozporządzenie MRPiPS z 12.06.2018 (NDS i NDN)",
      "Zasady GHP zakładu; karty charakterystyki środków",
    ],
    permitTypes: ["line_clearance", "general"],
    requiredCerts: ["ghp_gmp", "bhp_stanowisko", "badania_profilaktyczne"],
  },
  {
    id: "pl_zyw_003",
    market: "pl",
    sector: "construction",
    category: "PL — Zakład produkcji żywności",
    activity: "Prace na wysokości nad linią produkcyjną i w przestrzeni sufitowej",
    hazard:
      "Upadek z podestu na linię; upadek narzędzia lub elementu do produktu; zanieczyszczenie z przestrzeni sufitowej; kontakt z instalacją amoniakalną lub parową nad linią",
    initialRisk: { L: 4, S: 5, RF: 20 },
    controlMeasures: [
      "Podest ruchomy z ważną decyzją UDT i operatorem z uprawnieniami; zakaz pracy z drabiny nad linią",
      "Linia zatrzymana i przykryta albo produkt wycofany ze strefy pod pracami",
      "Narzędzia zabezpieczone linkami; kieszenie nad pasem opróżnione przed wejściem na podest",
      "Aktualne orzeczenie o zdolności do pracy na wysokości powyżej 3 m",
      "Przestrzeń sufitowa odkurzona przed pracami; osłony pod miejscem prac na czas robót",
      "Instalacje amoniakalne, parowe i sprężonego powietrza nad linią zidentyfikowane i odcięte, gdy są w zasięgu",
      "Kontrola ciał obcych nad linią i pod nią po zakończeniu prac, przed zwolnieniem linii",
    ],
    revisedRisk: { L: 2, S: 5, RF: 10 },
    ppeRequired: ["Kask z paskiem podbródkowym", "Szelki z lonżą krótką", "Odzież strefowa", "Obuwie antypoślizgowe"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP § 105–110",
      "Ustawa o dozorze technicznym",
      "Zasady GHP/GMP i system HACCP zakładu",
    ],
    permitTypes: ["work_at_height", "line_clearance"],
    requiredCerts: ["badania_wysokosc", "udt_podesty", "orzeczenie_sanepid"],
  },
  {
    id: "pl_zyw_004",
    market: "pl",
    sector: "construction",
    category: "PL — Zakład produkcji żywności",
    activity: "Prace w chłodni, mroźni i przy instalacji amoniakalnej",
    hazard:
      "Wychłodzenie i odmrożenia; uwolnienie amoniaku z instalacji chłodniczej; poślizgnięcie na oblodzonej posadzce; uwięzienie w komorze chłodniczej",
    initialRisk: { L: 3, S: 6, RF: 18 },
    controlMeasures: [
      "Instalacja amoniakalna odcięta i opróżniona przez służby utrzymania ruchu przed pracami mechanicznymi",
      "Detekcja amoniaku sprawna w strefie; procedura alarmowa i drogi ewakuacji omówione przed wejściem",
      "Maski ucieczkowe dostępne dla ekipy pracującej przy instalacji amoniakalnej",
      "Odzież ciepłochronna i limity czasu przebywania w mroźni z przerwami na ogrzanie",
      "Zabezpieczenie drzwi komory przed zatrzaśnięciem; sprawdzenie otwierania od wewnątrz przed wejściem",
      "Praca co najmniej we dwie osoby; łączność ze służbami zakładu utrzymywana przez cały czas",
      "Oblodzone posadzki oznakowane i posypane; sprzątanie po zakończeniu prac",
    ],
    revisedRisk: { L: 1, S: 6, RF: 6 },
    ppeRequired: ["Odzież ciepłochronna", "Rękawice ocieplane", "Obuwie antypoślizgowe", "Maska ucieczkowa przy amoniaku"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP",
      "Rozporządzenie MG z 30.10.2002 (minimalne wymagania — użytkowanie maszyn)",
      "Instrukcja bezpieczeństwa instalacji amoniakalnej zakładu",
    ],
    permitTypes: ["cold_work", "line_clearance", "confined_space"],
    requiredCerts: ["bhp_okresowe", "badania_profilaktyczne", "gas_tester"],
  },
  {
    id: "pl_zyw_005",
    market: "pl",
    sector: "construction",
    category: "PL — Zakład produkcji żywności",
    activity: "Wejście do zbiornika procesowego i prace przy instalacji CIP",
    hazard:
      "Uruchomienie mycia CIP w trakcie prac wewnątrz zbiornika; niedobór tlenu; pozostałość ługu lub kwasu na ściankach; brak możliwości szybkiej ewakuacji",
    initialRisk: { L: 4, S: 6, RF: 24 },
    controlMeasures: [
      "Pisemne zezwolenie na wejście do przestrzeni zamkniętej wydane po ocenie ryzyka dla tego zbiornika",
      "Obieg CIP odcięty fizycznie (zaślepka lub demontaż odcinka), nie tylko zamknięty zaworem",
      "Sterowanie CIP zablokowane i oznakowane (LOTO); klucz u wystawiającego zezwolenie",
      "Zbiornik przepłukany i przewietrzony; pomiar atmosfery przed wejściem i pomiar ciągły w trakcie",
      "Asekurujący na zewnątrz przez cały czas, ze sprzętem ratowniczym gotowym do użycia",
      "Kontrola pozostałości środków myjących i potwierdzenie pH przed wejściem",
      "Rozliczenie narzędzi i kontrola wnętrza zbiornika przed zamknięciem włazu",
    ],
    revisedRisk: { L: 2, S: 6, RF: 12 },
    ppeRequired: ["Szelki z linką", "Detektor wielogazowy", "Odzież chemoodporna", "Kask", "Sprzęt ucieczkowy"],
    regs: [
      "Rozporządzenie — ogólne przepisy BHP § 85–90",
      "Zasady GHP/GMP zakładu",
      "Karty charakterystyki środków CIP",
    ],
    permitTypes: ["confined_space", "line_clearance"],
    requiredCerts: ["confined_space", "gas_tester", "orzeczenie_sanepid"],
  },
];

export default PL_HAZARD_LIBRARY;
