/** @typedef {import("./markets").MarketId} MarketId */

/**
 * @typedef {{
 *   ramsShort: string;
 *   ramsLong: string;
 *   ramsBuilderTitle: string;
 *   emergencyServices: string;
 *   emergencyNumber: string;
 *   hospitalHeading: string;
 *   competencyHint: string;
 *   legislationSeedLabel: string;
 *   legislationSeedHint: string;
 *   cdmStepLabel: string;
 *   cdmStepHint: string;
 *   firstRamsStepLabel: string;
 *   firstRamsStepHint: string;
 *   hazardPacksStepLabel: string;
 *   permitStepLabel: string;
 *   permitStepHint: string;
 *   briefingStepLabel: string;
 *   briefingStepHint: string;
 *   postcodeHint: string;
 *   postcodeExample: string;
 *   geoLookupSuccess: string;
 *   registersLabel: string;
 *   moduleLabels?: Record<string, string>;
 * }} MarketLabelPack
 */

/** @type {Record<MarketId, MarketLabelPack>} */
export const MARKET_LABEL_PACKS = {
  uk: {
    ramsShort: "RAMS",
    ramsLong: "Risk Assessment & Method Statement (RAMS)",
    ramsBuilderTitle: "RAMS builder",
    emergencyServices: "nearest A&E",
    emergencyNumber: "999",
    hospitalHeading: "Nearest A&E / hospital",
    competencyHint: "e.g. CSCS, IPAF",
    legislationSeedLabel: "Load UK legislation register",
    legislationSeedHint: "CDM 2015, HASAWA, PUWER, COSHH — review applicability.",
    cdmStepLabel: "CDM compliance pack started",
    cdmStepHint: "CDM module → create CPP / pre-construction pack for your project.",
    firstRamsStepLabel: "First site RAMS issued",
    firstRamsStepHint: "RAMS Builder → apply construction quick pack and issue to site.",
    hazardPacksStepLabel: "Seed construction RAMS quick packs",
    permitStepLabel: "First permit to work issued",
    permitStepHint: "Permits → hot work, height or excavation — link to project RAMS.",
    briefingStepLabel: "Daily briefing recorded",
    briefingStepHint: "Capture weather, scope and signed attendance before work starts.",
    postcodeHint: "Enter a UK postcode, then use Lookup coordinates.",
    postcodeExample: "KT22 7SH",
    geoLookupSuccess: "Coordinates from UK postcode lookup.",
    registersLabel: "HSE",
  },
  au: {
    ramsShort: "SWMS",
    ramsLong: "Safe Work Method Statement (SWMS)",
    ramsBuilderTitle: "SWMS builder",
    emergencyServices: "nearest ED",
    emergencyNumber: "000",
    hospitalHeading: "Nearest ED / hospital",
    competencyHint: "e.g. White Card, EWPA, HRWL",
    legislationSeedLabel: "Load WHS legislation register",
    legislationSeedHint: "WHS Act, model codes, construction work — review applicability by state.",
    cdmStepLabel: "WHS management plan started",
    cdmStepHint: "WHS / CDM module → create site WHS management plan for your project.",
    firstRamsStepLabel: "First site SWMS issued",
    firstRamsStepHint: "SWMS Builder → apply construction quick pack and issue to site.",
    hazardPacksStepLabel: "Seed construction SWMS quick packs",
    permitStepLabel: "First permit to work issued",
    permitStepHint: "Permits → hot work, height or excavation — link to project SWMS.",
    briefingStepLabel: "Daily briefing recorded",
    briefingStepHint: "Capture weather, scope and signed attendance before work starts.",
    postcodeHint: "Enter an Australian postcode (e.g. 2000), then use Lookup coordinates.",
    postcodeExample: "2000",
    geoLookupSuccess: "Coordinates from Australian postcode lookup.",
    registersLabel: "WHS",
    moduleLabels: {
      rams: "SWMS",
      "whs-plan": "WHS management plan",
      "notifiable-incidents": "Notifiable incidents",
      coshh: "Hazardous substances",
      legislation: "WHS legislation",
      "construction-setup": "Construction setup (AU)",
    },
  },
  pl: {
    ramsShort: "IBWR",
    ramsLong: "Instrukcja bezpiecznego wykonywania robót (IBWR)",
    ramsBuilderTitle: "Kreator IBWR",
    emergencyServices: "najbliższy SOR",
    emergencyNumber: "112",
    hospitalHeading: "Najbliższy SOR / szpital",
    competencyHint: "np. UDT, SEP, uprawnienia budowlane, BHP",
    legislationSeedLabel: "Załaduj rejestr przepisów BHP",
    legislationSeedHint: "Kodeks pracy, rozporządzenia BHP, PIP — zweryfikuj zakres na budowie.",
    cdmStepLabel: "Plan BIOZ rozpoczęty",
    cdmStepHint: "Moduł Plan BIOZ → utwórz plan BIOZ dla inwestycji.",
    firstRamsStepLabel: "Pierwsza IBWR na budowie",
    firstRamsStepHint: "Kreator IBWR → zastosuj pakiet szybki i wydaj na plac budowy.",
    hazardPacksStepLabel: "Załaduj pakiety IBWR budowlane",
    permitStepLabel: "Pierwsze pozwolenie na pracę",
    permitStepHint: "Pozwolenia → prace gorące, wysokość lub wykopy — powiąż z IBWR projektu.",
    briefingStepLabel: "Zapis odprawy dziennej",
    briefingStepHint: "Pogoda, zakres i obecność przed rozpoczęciem pracy.",
    postcodeHint: "Wpisz kod pocztowy (np. 00-001), potem wyszukaj współrzędne.",
    postcodeExample: "00-001",
    geoLookupSuccess: "Współrzędne z wyszukiwania kodu pocztowego (PL).",
    registersLabel: "BHP",
    moduleLabels: {
      rams: "IBWR",
      "bhp-plan": "Plan BIOZ",
      orz: "Ocena ryzyka zawodowego",
      "pl-druki": "Druki BHP",
      "pl-instrukcje": "Instrukcje stanowiskowe",
      "pl-czynniki": "Czynniki szkodliwe",
      "notifiable-incidents": "Zdarzenia wymagające zgłoszenia",
      coshh: "Substancje niebezpieczne",
      legislation: "Przepisy BHP",
      "construction-setup": "Konfiguracja budowy",
      permits: "Pozwolenia",
      dashboard: "Panel",
      projects: "Projekty",
      people: "Pracownicy",
      more: "Więcej",
      bin: "Kosz",
      "daily-briefing": "Odprawa dzienna",
      incidents: "Zdarzenia",
      "incident-actions": "Działania po zdarzeniu",
      "incident-map": "Mapa zdarzeń",
      inspections: "Kontrole",
      "project-drawings": "Rysunki",
      "method-statement": "Instrukcja techniczna",
      induction: "Indukcja QR",
      signatures: "Podpisy",
      timesheets: "Karty pracy",
      snags: "Usterki",
      "geo-photos": "Zdjęcia geo",
      documents: "Dokumenty",
      "client-portal": "Portal klienta",
      subcontractor: "Podwykonawcy",
      emergency: "Ratunkowe",
      ppe: "OOP",
      plant: "Urządzenia",
      fire: "Pożar",
      "hot-work": "Prace gorące",
      training: "Szkolenia",
      visitors: "Goście",
      "toolbox-reg": "Odprawy",
      "first-aid": "Pierwsza pomoc",
      "lone-working": "Praca samotna",
      environmental: "Środowisko",
      observations: "Obserwacje",
      ladders: "Drabiny",
      mewp: "Podesty ruchome",
      gate: "Księga bramy",
      asbestos: "Azbest",
      "confined-space": "Przestrzeń zamknięta",
      loto: "LOTO",
      "electrical-pat": "Elektryczne",
      lifting: "Podnoszenie",
      noise: "Hałas i wibracje",
      scaffold: "Rusztowania",
      excavation: "Wykopy",
      "temp-works": "Roboty tymczasowe",
      welfare: "Sanitariaty",
      "water-hygiene": "Woda",
      waste: "Odpady",
      analytics: "Analityka",
      "monthly-report": "Raport miesięczny",
      templates: "Szablony",
      backup: "Kopia zapasowa",
      audit: "Dziennik audytu",
      help: "Pomoc",
      settings: "Ustawienia",
      "dynamic-ra": "Ocena ryzyka",
    },
  },
  de: {
    ramsShort: "GBU",
    ramsLong: "Gefährdungsbeurteilung und Betriebsanweisung",
    ramsBuilderTitle: "GBU-Generator",
    emergencyServices: "nächstes Krankenhaus",
    emergencyNumber: "112",
    hospitalHeading: "Nächstes Krankenhaus / Notaufnahme",
    competencyHint: "z. B. SCC, SiGeKo, Sifa, Ersthelfer, Hubarbeitsbühne",
    legislationSeedLabel: "Arbeitsschutz-Vorschriften laden",
    legislationSeedHint: "ArbSchG, BaustellV, BetrSichV, GefStoffV, DGUV — Geltung auf der Baustelle prüfen.",
    cdmStepLabel: "SiGe-Plan begonnen",
    cdmStepHint: "Modul SiGe-Plan → Sicherheits- und Gesundheitsschutzplan für das Vorhaben anlegen.",
    firstRamsStepLabel: "Erste GBU auf der Baustelle",
    firstRamsStepHint: "GBU-Generator → Schnellpaket anwenden und an die Baustelle ausgeben.",
    hazardPacksStepLabel: "Baustellen-GBU-Pakete laden",
    permitStepLabel: "Erster Erlaubnisschein",
    permitStepHint: "Erlaubnisscheine → Heißarbeiten, Absturz oder Aushub — mit der GBU des Projekts verknüpfen.",
    briefingStepLabel: "Unterweisung erfasst",
    briefingStepHint: "Wetter, Arbeitsumfang und Anwesenheit vor Arbeitsbeginn dokumentieren.",
    postcodeHint: "Deutsche PLZ eingeben (z. B. 10115), dann Koordinaten suchen.",
    postcodeExample: "10115",
    geoLookupSuccess: "Koordinaten aus deutscher Postleitzahlensuche.",
    registersLabel: "Arbeitsschutz",
    moduleLabels: {
      rams: "GBU",
      "sige-plan": "SiGe-Plan",
      "notifiable-incidents": "Meldepflichtige Ereignisse",
      coshh: "Gefahrstoffe",
      legislation: "Arbeitsschutzvorschriften",
      "construction-setup": "Baustellen-Einrichtung",
      permits: "Erlaubnisscheine",
      dashboard: "Übersicht",
      projects: "Projekte",
      people: "Beschäftigte",
      more: "Mehr",
      bin: "Papierkorb",
      "daily-briefing": "Unterweisung",
      incidents: "Ereignisse",
      "incident-actions": "Maßnahmen",
      "incident-map": "Ereigniskarte",
      inspections: "Prüfungen",
      "project-drawings": "Pläne",
      "method-statement": "Betriebsanweisung",
      induction: "QR-Einweisung",
      signatures: "Unterschriften",
      timesheets: "Stundenzettel",
      snags: "Mängel",
      "geo-photos": "Geo-Fotos",
      documents: "Dokumente",
      "client-portal": "Auftraggeber-Portal",
      subcontractor: "Nachunternehmer",
      emergency: "Notfall",
      ppe: "PSA",
      plant: "Geräte",
      fire: "Brandschutz",
      "hot-work": "Heißarbeiten",
      training: "Unterweisungen",
      visitors: "Besucher",
      "toolbox-reg": "Kurzunterweisungen",
      "first-aid": "Erste Hilfe",
      "lone-working": "Alleinarbeit",
      environmental: "Umwelt",
      observations: "Beobachtungen",
      ladders: "Leitern",
      mewp: "Hubarbeitsbühnen",
      gate: "Pfortenbuch",
      asbestos: "Asbest",
      "confined-space": "Enge Räume",
      loto: "LOTO",
      "electrical-pat": "Elektrik",
      lifting: "Heben",
      noise: "Lärm und Vibration",
      scaffold: "Gerüste",
      excavation: "Aushub",
      "temp-works": "Temporäre Bauwerke",
      welfare: "Sozialräume",
      "water-hygiene": "Wasser",
      waste: "Abfall",
      analytics: "Auswertung",
      "monthly-report": "Monatsbericht",
      templates: "Vorlagen",
      backup: "Sicherung",
      audit: "Auditprotokoll",
      help: "Hilfe",
      settings: "Einstellungen",
      "dynamic-ra": "Gefährdungsbeurteilung",
    },
  },
  at: {
    ramsShort: "Evaluierung",
    ramsLong: "Evaluierung von Gefahren und Betriebsanweisung",
    ramsBuilderTitle: "Evaluierungs-Generator",
    emergencyServices: "nächstes Krankenhaus",
    emergencyNumber: "112",
    hospitalHeading: "Nächstes Krankenhaus / Notaufnahme",
    competencyHint: "z. B. BauKG-Koordinator, Sicherheitsfachkraft, Ersthelfer, Hubarbeitsbühne",
    legislationSeedLabel: "Arbeitsschutz-Vorschriften laden",
    legislationSeedHint: "ASchG, BauKG, AM-VO, AUVA — Geltung auf der Baustelle prüfen.",
    cdmStepLabel: "SiGe-Plan begonnen",
    cdmStepHint: "Modul SiGe-Plan → Sicherheits- und Gesundheitsschutzplan (BauKG) anlegen.",
    firstRamsStepLabel: "Erste Evaluierung auf der Baustelle",
    firstRamsStepHint: "Evaluierungs-Generator → Schnellpaket anwenden und an die Baustelle ausgeben.",
    hazardPacksStepLabel: "Baustellen-Evaluierungspakete laden",
    permitStepLabel: "Erster Erlaubnisschein",
    permitStepHint: "Erlaubnisscheine → Heißarbeiten, Absturz oder Aushub — mit der Evaluierung des Projekts verknüpfen.",
    briefingStepLabel: "Unterweisung erfasst",
    briefingStepHint: "Wetter, Arbeitsumfang und Anwesenheit vor Arbeitsbeginn dokumentieren.",
    postcodeHint: "Österreichische PLZ eingeben (z. B. 1010), dann Koordinaten suchen.",
    postcodeExample: "1010",
    geoLookupSuccess: "Koordinaten aus österreichischer Postleitzahlensuche.",
    registersLabel: "Arbeitsschutz",
    moduleLabels: {
      rams: "Evaluierung",
      "sige-plan": "SiGe-Plan",
      "notifiable-incidents": "Meldepflichtige Ereignisse",
      coshh: "Gefahrstoffe",
      legislation: "Arbeitsschutzvorschriften",
      "construction-setup": "Baustellen-Einrichtung",
      permits: "Erlaubnisscheine",
      dashboard: "Übersicht",
      projects: "Projekte",
      people: "Beschäftigte",
      more: "Mehr",
      bin: "Papierkorb",
      "daily-briefing": "Unterweisung",
      incidents: "Ereignisse",
      "incident-actions": "Maßnahmen",
      "incident-map": "Ereigniskarte",
      inspections: "Prüfungen",
      "project-drawings": "Pläne",
      "method-statement": "Betriebsanweisung",
      induction: "QR-Einweisung",
      signatures: "Unterschriften",
      timesheets: "Stundenzettel",
      snags: "Mängel",
      "geo-photos": "Geo-Fotos",
      documents: "Dokumente",
      "client-portal": "Auftraggeber-Portal",
      subcontractor: "Nachunternehmer",
      emergency: "Notfall",
      ppe: "PSA",
      plant: "Geräte",
      fire: "Brandschutz",
      "hot-work": "Heißarbeiten",
      training: "Unterweisungen",
      visitors: "Besucher",
      "toolbox-reg": "Kurzunterweisungen",
      "first-aid": "Erste Hilfe",
      "lone-working": "Alleinarbeit",
      environmental: "Umwelt",
      observations: "Beobachtungen",
      ladders: "Leitern",
      mewp: "Hubarbeitsbühnen",
      gate: "Pfortenbuch",
      asbestos: "Asbest",
      "confined-space": "Enge Räume",
      loto: "LOTO",
      "electrical-pat": "Elektrik",
      lifting: "Heben",
      noise: "Lärm und Vibration",
      scaffold: "Gerüste",
      excavation: "Aushub",
      "temp-works": "Temporäre Bauwerke",
      welfare: "Sozialräume",
      "water-hygiene": "Wasser",
      waste: "Abfall",
      analytics: "Auswertung",
      "monthly-report": "Monatsbericht",
      templates: "Vorlagen",
      backup: "Sicherung",
      audit: "Auditprotokoll",
      help: "Hilfe",
      settings: "Einstellungen",
      "dynamic-ra": "Evaluierung",
    },
  },
  ch: {
    ramsShort: "Gefährdungsermittlung",
    ramsLong: "Gefährdungsermittlung und Arbeitsanweisung",
    ramsBuilderTitle: "Gefährdungsermittlungs-Generator",
    emergencyServices: "nächstes Spital",
    emergencyNumber: "112 / 144",
    hospitalHeading: "Nächstes Spital / Notfallstation",
    competencyHint: "z. B. Sicherheitsbeauftragter, Suva-anerkannte Fachperson, Ersthelfer, Hubarbeitsbühne",
    legislationSeedLabel: "Arbeitssicherheitsvorschriften laden",
    legislationSeedHint: "BauAV, ASV, EKAS-Richtlinien, Suva — Geltung auf der Baustelle prüfen.",
    cdmStepLabel: "SiKo begonnen",
    cdmStepHint: "Modul SiKo → Sicherheits- und Gesundheitsschutzkonzept (BauAV Art. 4) anlegen.",
    firstRamsStepLabel: "Erste Gefährdungsermittlung auf der Baustelle",
    firstRamsStepHint: "Gefährdungsermittlungs-Generator → Schnellpaket anwenden und an die Baustelle ausgeben.",
    hazardPacksStepLabel: "Baustellen-Gefährdungspakete laden",
    permitStepLabel: "Erste Freigabe",
    permitStepHint: "Freigaben → Heissarbeiten, Absturz oder Aushub — mit der Gefährdungsermittlung des Projekts verknüpfen.",
    briefingStepLabel: "Instruktion erfasst",
    briefingStepHint: "Wetter, Arbeitsumfang und Anwesenheit vor Arbeitsbeginn dokumentieren.",
    postcodeHint: "Schweizer PLZ eingeben (z. B. 8001), dann Koordinaten suchen.",
    postcodeExample: "8001",
    geoLookupSuccess: "Koordinaten aus Schweizer Postleitzahlensuche.",
    registersLabel: "Arbeitssicherheit",
    moduleLabels: {
      rams: "Gefährdungsermittlung",
      "sige-plan": "SiKo",
      "notifiable-incidents": "Meldepflichtige Ereignisse",
      coshh: "Gefahrstoffe",
      legislation: "Arbeitssicherheitsvorschriften",
      "construction-setup": "Baustellen-Einrichtung",
      permits: "Freigaben",
      dashboard: "Übersicht",
      projects: "Projekte",
      people: "Beschäftigte",
      more: "Mehr",
      bin: "Papierkorb",
      "daily-briefing": "Instruktion",
      incidents: "Ereignisse",
      "incident-actions": "Massnahmen",
      "incident-map": "Ereigniskarte",
      inspections: "Prüfungen",
      "project-drawings": "Pläne",
      "method-statement": "Arbeitsanweisung",
      induction: "QR-Einweisung",
      signatures: "Unterschriften",
      timesheets: "Stundenzettel",
      snags: "Mängel",
      "geo-photos": "Geo-Fotos",
      documents: "Dokumente",
      "client-portal": "Auftraggeber-Portal",
      subcontractor: "Nachunternehmer",
      emergency: "Notfall",
      ppe: "PSA",
      plant: "Geräte",
      fire: "Brandschutz",
      "hot-work": "Heissarbeiten",
      training: "Instruktionen",
      visitors: "Besucher",
      "toolbox-reg": "Kurzinstruktionen",
      "first-aid": "Erste Hilfe",
      "lone-working": "Alleinarbeit",
      environmental: "Umwelt",
      observations: "Beobachtungen",
      ladders: "Leitern",
      mewp: "Hubarbeitsbühnen",
      gate: "Pfortenbuch",
      asbestos: "Asbest",
      "confined-space": "Enge Räume",
      loto: "LOTO",
      "electrical-pat": "Elektrik",
      lifting: "Heben",
      noise: "Lärm und Vibration",
      scaffold: "Gerüste",
      excavation: "Aushub",
      "temp-works": "Temporäre Bauwerke",
      welfare: "Sozialräume",
      "water-hygiene": "Wasser",
      waste: "Abfall",
      analytics: "Auswertung",
      "monthly-report": "Monatsbericht",
      templates: "Vorlagen",
      backup: "Sicherung",
      audit: "Auditprotokoll",
      help: "Hilfe",
      settings: "Einstellungen",
      "dynamic-ra": "Gefährdungsermittlung",
    },
  },
};

/** @param {MarketId} [marketId] */
export function getMarketLabelPack(marketId = "uk") {
  return MARKET_LABEL_PACKS[marketId] ?? MARKET_LABEL_PACKS.uk;
}
