import { useState, useEffect, useRef } from "react";
import { useApp } from "../context/AppContext";
import { pushAudit } from "../utils/auditLog";

const ORG_KEY = "mysafeops_org_settings";
const loadOrg = () => { try { return JSON.parse(localStorage.getItem(ORG_KEY) || "{}"); } catch { return {}; } };
const saveOrg = (v) => localStorage.setItem(ORG_KEY, JSON.stringify(v));

export const getOrgSettings = () => {
  const s = loadOrg();
  return {
    name: s.name || "My Organisation",
    logo: s.logo || null,
    address: s.address || "",
    phone: s.phone || "",
    email: s.email || "",
    website: s.website || "",
    primaryColor: s.primaryColor || "#0d9488",
    accentColor: s.accentColor || "#f97316",
    pdfFooter: s.pdfFooter || "Generated by MySafeOps — mysafeops.com",
    pdfHeader: s.pdfHeader || "",
    registrationNo: s.registrationNo || "",
    vatNo: s.vatNo || "",
    defaultLeadEngineer: s.defaultLeadEngineer || "",
    safetyPolicy: s.safetyPolicy || "",
    emergencyContact: s.emergencyContact || "",
    customFields: s.customFields || [],
  };
};

const ss = {
  btn:  { padding:"7px 14px", borderRadius:6, border:"0.5px solid var(--color-border-secondary,#ccc)", background:"var(--color-background-primary,#fff)", color:"var(--color-text-primary)", fontSize:13, cursor:"pointer", fontFamily:"DM Sans,sans-serif", display:"inline-flex", alignItems:"center", gap:6 },
  btnP: { padding:"7px 14px", borderRadius:6, border:"0.5px solid #085041", background:"#0d9488", color:"#E1F5EE", fontSize:13, cursor:"pointer", fontFamily:"DM Sans,sans-serif", display:"inline-flex", alignItems:"center", gap:6 },
  btnO: { padding:"7px 14px", borderRadius:6, border:"0.5px solid #c2410c", background:"#f97316", color:"#fff", fontSize:13, cursor:"pointer", fontFamily:"DM Sans,sans-serif", display:"inline-flex", alignItems:"center", gap:6 },
  inp:  { width:"100%", padding:"7px 10px", border:"0.5px solid var(--color-border-secondary,#ccc)", borderRadius:6, fontSize:13, background:"var(--color-background-primary,#fff)", color:"var(--color-text-primary)", fontFamily:"DM Sans,sans-serif", boxSizing:"border-box" },
  lbl:  { display:"block", fontSize:12, fontWeight:500, color:"var(--color-text-secondary)", marginBottom:4 },
  card: { background:"var(--color-background-primary,#fff)", border:"0.5px solid var(--color-border-tertiary,#e5e5e5)", borderRadius:12, padding:"1.25rem", marginBottom:16 },
  ta:   { width:"100%", padding:"7px 10px", border:"0.5px solid var(--color-border-secondary,#ccc)", borderRadius:6, fontSize:13, background:"var(--color-background-primary,#fff)", color:"var(--color-text-primary)", fontFamily:"DM Sans,sans-serif", boxSizing:"border-box", resize:"vertical", minHeight:60 },
  sec:  { fontSize:11, fontWeight:500, color:"var(--color-text-secondary)", textTransform:"uppercase", letterSpacing:"0.05em", marginBottom:10 },
};

function Section({ title, children }) {
  return (
    <div style={ss.card}>
      <div style={ss.sec}>{title}</div>
      {children}
    </div>
  );
}

function Field({ label, hint, children }) {
  return (
    <div style={{ marginBottom:12 }}>
      <label style={ss.lbl}>{label}</label>
      {hint && <div style={{ fontSize:11, color:"var(--color-text-tertiary,#aaa)", marginBottom:4 }}>{hint}</div>}
      {children}
    </div>
  );
}

export default function OrgSettings() {
  const { role, setRole, caps } = useApp();
  const [form, setForm] = useState(loadOrg());
  const [saved, setSaved] = useState(false);
  const [tab, setTab] = useState("brand");
  const logoRef = useRef();
  const set = (k,v) => setForm(f=>({...f,[k]:v}));

  const handleLogoUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;
    if (file.size > 500000) { alert("Logo must be under 500KB"); return; }
    const reader = new FileReader();
    reader.onload = ev => set("logo", ev.target.result);
    reader.readAsDataURL(file);
  };

  const handleSave = () => {
    if (!caps.orgSettings) {
      alert("Only administrators can change organisation settings.");
      return;
    }
    saveOrg(form);
    pushAudit({ action: "org_settings_save", entity: "mysafeops_org_settings", detail: form.name || "" });
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  const addCustomField = () => {
    set("customFields", [...(form.customFields||[]), { id: Date.now(), label:"", value:"" }]);
  };

  const updateCustomField = (id, k, v) => {
    set("customFields", (form.customFields||[]).map(f=>f.id===id?{...f,[k]:v}:f));
  };

  const removeCustomField = (id) => {
    set("customFields", (form.customFields||[]).filter(f=>f.id!==id));
  };

  const TABS = [["brand","Branding & logo"],["company","Company info"],["pdf","PDF defaults"],["custom","Custom fields"],["access","Access"],["preview","Preview"]];

  return (
    <div style={{ fontFamily:"DM Sans,system-ui,sans-serif", padding:"1.25rem 0", fontSize:14, color:"var(--color-text-primary)" }}>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:20, flexWrap:"wrap", gap:8 }}>
        <div>
          <h2 style={{ fontWeight:500, fontSize:20, margin:0 }}>Organisation settings</h2>
          <p style={{ fontSize:12, color:"var(--color-text-secondary)", margin:"2px 0 0" }}>Your logo and details appear on all printed documents</p>
        </div>
        <button
          onClick={handleSave}
          disabled={!caps.orgSettings}
          style={{ ...(saved ? { ...ss.btnP, background: "#27500A", borderColor: "#1D6B33" } : ss.btnP), opacity: caps.orgSettings ? 1 : 0.45 }}
        >
          {saved ? "Saved" : "Save settings"}
        </button>
      </div>

      {/* tabs */}
      <div style={{ display:"flex", gap:2, marginBottom:20, flexWrap:"wrap" }}>
        {TABS.map(([t,l])=>(
          <button key={t} onClick={()=>setTab(t)} style={{
            ...ss.btn, borderRadius:"6px 6px 0 0", padding:"6px 14px", fontSize:13,
            borderBottom:tab===t?"2px solid #0d9488":"2px solid transparent",
            background:tab===t?"var(--color-background-secondary,#f7f7f5)":"transparent",
            borderLeft:"none", borderRight:"none", borderTop:"none",
            color:tab===t?"#0d9488":"var(--color-text-secondary)", fontWeight:tab===t?500:400,
          }}>{l}</button>
        ))}
      </div>

      {tab==="brand" && (
        <>
          <Section title="Logo">
            <div style={{ display:"flex", gap:20, alignItems:"flex-start", flexWrap:"wrap" }}>
              {/* logo preview */}
              <div style={{
                width:140, height:80, borderRadius:8, flexShrink:0,
                border:"0.5px dashed var(--color-border-secondary,#ccc)",
                background:"var(--color-background-secondary,#f7f7f5)",
                display:"flex", alignItems:"center", justifyContent:"center", overflow:"hidden",
              }}>
                {form.logo
                  ? <img src={form.logo} alt="logo" style={{ maxWidth:132, maxHeight:72, objectFit:"contain" }} />
                  : <span style={{ fontSize:11, color:"var(--color-text-secondary)" }}>No logo</span>
                }
              </div>
              <div style={{ flex:1 }}>
                <Field label="Upload logo" hint="PNG, JPG or SVG — max 500KB. Will appear on all PDFs and the client portal.">
                  <div style={{ display:"flex", gap:8 }}>
                    <button onClick={()=>logoRef.current.click()} style={ss.btn}>Choose file</button>
                    {form.logo && <button onClick={()=>set("logo",null)} style={{ ...ss.btn, color:"#A32D2D", borderColor:"#F09595" }}>Remove logo</button>}
                  </div>
                  <input ref={logoRef} type="file" accept="image/*" style={{ display:"none" }} onChange={handleLogoUpload} />
                </Field>
              </div>
            </div>
          </Section>

          <Section title="Brand colours">
            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>
              <Field label="Primary colour" hint="Used for headers, key elements">
                <div style={{ display:"flex", gap:8, alignItems:"center" }}>
                  <input type="color" value={form.primaryColor||"#0d9488"} onChange={e=>set("primaryColor",e.target.value)}
                    style={{ width:44, height:36, borderRadius:6, border:"0.5px solid var(--color-border-secondary,#ccc)", cursor:"pointer", padding:2 }} />
                  <input value={form.primaryColor||"#0d9488"} onChange={e=>set("primaryColor",e.target.value)} style={{ ...ss.inp, width:"auto", flex:1 }} />
                </div>
              </Field>
              <Field label="Accent colour" hint="Used for buttons and highlights">
                <div style={{ display:"flex", gap:8, alignItems:"center" }}>
                  <input type="color" value={form.accentColor||"#f97316"} onChange={e=>set("accentColor",e.target.value)}
                    style={{ width:44, height:36, borderRadius:6, border:"0.5px solid var(--color-border-secondary,#ccc)", cursor:"pointer", padding:2 }} />
                  <input value={form.accentColor||"#f97316"} onChange={e=>set("accentColor",e.target.value)} style={{ ...ss.inp, width:"auto", flex:1 }} />
                </div>
              </Field>
            </div>
            {/* colour preview */}
            <div style={{ display:"flex", gap:8, marginTop:8 }}>
              <div style={{ padding:"6px 16px", borderRadius:6, background:form.primaryColor||"#0d9488", color:"#fff", fontSize:12 }}>Primary button</div>
              <div style={{ padding:"6px 16px", borderRadius:6, background:form.accentColor||"#f97316", color:"#fff", fontSize:12 }}>Accent button</div>
            </div>
          </Section>
        </>
      )}

      {tab==="company" && (
        <Section title="Company information">
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 }}>
            <div style={{ gridColumn:"1/-1" }}>
              <Field label="Company / organisation name">
                <input value={form.name||""} onChange={e=>set("name",e.target.value)} placeholder="e.g. FESS Food Engineering Services Ltd" style={ss.inp} />
              </Field>
            </div>
            <div style={{ gridColumn:"1/-1" }}>
              <Field label="Registered address">
                <textarea value={form.address||""} onChange={e=>set("address",e.target.value)} rows={2} placeholder="Full company address" style={ss.ta} />
              </Field>
            </div>
            <Field label="Phone">
              <input value={form.phone||""} onChange={e=>set("phone",e.target.value)} placeholder="+44 ..." style={ss.inp} />
            </Field>
            <Field label="Email">
              <input value={form.email||""} onChange={e=>set("email",e.target.value)} placeholder="info@company.com" style={ss.inp} />
            </Field>
            <Field label="Website">
              <input value={form.website||""} onChange={e=>set("website",e.target.value)} placeholder="www.company.com" style={ss.inp} />
            </Field>
            <Field label="Default lead engineer">
              <input value={form.defaultLeadEngineer||""} onChange={e=>set("defaultLeadEngineer",e.target.value)} placeholder="Pre-fills lead engineer field on new documents" style={ss.inp} />
            </Field>
            <Field label="Company / registration number">
              <input value={form.registrationNo||""} onChange={e=>set("registrationNo",e.target.value)} placeholder="Companies House No." style={ss.inp} />
            </Field>
            <Field label="VAT number">
              <input value={form.vatNo||""} onChange={e=>set("vatNo",e.target.value)} placeholder="GB ..." style={ss.inp} />
            </Field>
            <div style={{ gridColumn:"1/-1" }}>
              <Field label="Emergency contact" hint="Printed on all documents">
                <input value={form.emergencyContact||""} onChange={e=>set("emergencyContact",e.target.value)} placeholder="Name, phone, role" style={ss.inp} />
              </Field>
            </div>
          </div>
        </Section>
      )}

      {tab==="pdf" && (
        <Section title="PDF document defaults">
          <Field label="Document header text" hint="Appears below your logo on all printed documents">
            <input value={form.pdfHeader||""} onChange={e=>set("pdfHeader",e.target.value)}
              placeholder="e.g. FESS Food Engineering Services Ltd — Health & Safety Documentation" style={ss.inp} />
          </Field>
          <Field label="Document footer text" hint="Appears at the bottom of every printed page">
            <input value={form.pdfFooter||""} onChange={e=>set("pdfFooter",e.target.value)}
              placeholder="e.g. Generated by MySafeOps — mysafeops.com" style={ss.inp} />
          </Field>
          <Field label="Health & safety policy statement" hint="Optional — included in RAMS cover pages">
            <textarea value={form.safetyPolicy||""} onChange={e=>set("safetyPolicy",e.target.value)} rows={4}
              placeholder="It is the policy of [company] to ensure, so far as is reasonably practicable, the health, safety and welfare of all employees…" style={ss.ta} />
          </Field>
          {/* PDF preview box */}
          <div style={{ marginTop:16, border:"0.5px solid var(--color-border-tertiary,#e5e5e5)", borderRadius:8, overflow:"hidden" }}>
            <div style={{ background:"#f5f5f5", padding:"6px 12px", fontSize:11, color:"var(--color-text-secondary)" }}>PDF preview</div>
            <div style={{ padding:"16px", background:"#fff" }}>
              <div style={{ display:"flex", alignItems:"center", gap:16, paddingBottom:12, borderBottom:"2px solid "+(form.primaryColor||"#0d9488"), marginBottom:10 }}>
                {form.logo
                  ? <img src={form.logo} alt="logo" style={{ height:44, maxWidth:120, objectFit:"contain" }} />
                  : <div style={{ width:80, height:44, background:"#f0f0f0", borderRadius:4, display:"flex", alignItems:"center", justifyContent:"center", fontSize:10, color:"#999" }}>LOGO</div>
                }
                <div>
                  <div style={{ fontWeight:500, fontSize:13 }}>{form.name||"Your Company Name"}</div>
                  {form.pdfHeader && <div style={{ fontSize:11, color:"#666" }}>{form.pdfHeader}</div>}
                </div>
              </div>
              <div style={{ fontSize:11, color:"#666", borderTop:"0.5px solid #e5e5e5", paddingTop:8, marginTop:8 }}>
                {form.pdfFooter||"Generated by MySafeOps — mysafeops.com"}
              </div>
            </div>
          </div>
        </Section>
      )}

      {tab==="custom" && (
        <Section title="Custom fields">
          <div style={{ fontSize:12, color:"var(--color-text-secondary)", marginBottom:14 }}>
            Add custom fields that appear on all your documents — e.g. "Principal Contractor", "Contract number", "Client contact".
          </div>
          {(form.customFields||[]).map(f=>(
            <div key={f.id} style={{ display:"flex", gap:8, marginBottom:8, alignItems:"center" }}>
              <input value={f.label} onChange={e=>updateCustomField(f.id,"label",e.target.value)}
                placeholder="Field label (e.g. Contract No.)" style={{ ...ss.inp, flex:1 }} />
              <input value={f.value} onChange={e=>updateCustomField(f.id,"value",e.target.value)}
                placeholder="Default value (optional)" style={{ ...ss.inp, flex:1 }} />
              <button onClick={()=>removeCustomField(f.id)} style={{ ...ss.btn, padding:"7px 10px", color:"#A32D2D", borderColor:"#F09595", flexShrink:0 }}>×</button>
            </div>
          ))}
          <button onClick={addCustomField} style={{ ...ss.btn, marginTop:4 }}>+ Add custom field</button>
        </Section>
      )}

      {tab==="access" && (
        <Section title="App role (this browser)">
          <Field label="Your role" hint="Admin: full access. Supervisor: no org settings / backup import. Operative: no deletes or bulk actions.">
            <select
              value={role}
              onChange={(e) => {
                const v = e.target.value;
                setRole(v);
                pushAudit({ action: "role_change", entity: "session", detail: v });
              }}
              style={ss.inp}
            >
              <option value="admin">Admin</option>
              <option value="supervisor">Supervisor</option>
              <option value="operative">Operative</option>
            </select>
          </Field>
          <p style={{ fontSize: 12, color: "var(--color-text-secondary)" }}>Tip: if you lock yourself down as Operative, switch back to Admin here to restore full access.</p>
        </Section>
      )}

      {tab==="preview" && (
        <div style={{ ...ss.card }}>
          <div style={{ display:"flex", alignItems:"center", gap:16, paddingBottom:14, borderBottom:"2.5px solid "+(form.primaryColor||"#0d9488"), marginBottom:14 }}>
            {form.logo
              ? <img src={form.logo} alt="logo" style={{ height:56, maxWidth:160, objectFit:"contain" }} />
              : <div style={{ width:100, height:56, background:"var(--color-background-secondary,#f7f7f5)", borderRadius:6, display:"flex", alignItems:"center", justifyContent:"center", fontSize:11, color:"var(--color-text-secondary)" }}>No logo</div>
            }
            <div>
              <div style={{ fontWeight:500, fontSize:16 }}>{form.name||"Your Company Name"}</div>
              {form.address && <div style={{ fontSize:12, color:"var(--color-text-secondary)", marginTop:2 }}>{form.address.split("\n")[0]}</div>}
              {form.phone && <div style={{ fontSize:12, color:"var(--color-text-secondary)" }}>{form.phone} · {form.email}</div>}
            </div>
          </div>
          <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:8, marginBottom:14 }}>
            {[["Primary",form.primaryColor||"#0d9488"],["Accent",form.accentColor||"#f97316"]].map(([l,c])=>(
              <div key={l} style={{ padding:"8px 12px", background:c, borderRadius:6, color:"#fff", fontSize:12 }}>{l}</div>
            ))}
          </div>
          {(form.customFields||[]).filter(f=>f.label).map(f=>(
            <div key={f.id} style={{ display:"flex", gap:8, fontSize:12, padding:"6px 0", borderBottom:"0.5px solid var(--color-border-tertiary,#e5e5e5)" }}>
              <span style={{ color:"var(--color-text-secondary)", minWidth:140 }}>{f.label}</span>
              <span>{f.value||"—"}</span>
            </div>
          ))}
        </div>
      )}

      <div style={{ display:"flex", justifyContent:"flex-end", marginTop:8 }}>
        <button
          onClick={handleSave}
          disabled={!caps.orgSettings}
          style={{ ...(saved ? { ...ss.btnP, background: "#27500A", borderColor: "#1D6B33" } : ss.btnP), opacity: caps.orgSettings ? 1 : 0.45 }}
        >
          {saved ? "Saved" : "Save settings"}
        </button>
      </div>
    </div>
  );
}
