import { getOrgMarketId } from "./orgMarket";

const COMMON = {
  uk: {
    language: "en-GB",
    jurisdiction: "United Kingdom",
    safetyAuthority: "HSE",
    emergencyNumber: "999",
    controlledDocument: "Controlled document. Ensure the latest approved revision is in use.",
    legalReferencesHeading: "Legal and regulatory references (UK)",
    ramsLegalReferences: [
      "Health and Safety at Work etc. Act 1974",
      "Management of Health and Safety at Work Regulations 1999",
      "Construction (Design and Management) Regulations 2015",
      "Provision and Use of Work Equipment Regulations 1998",
      "Personal Protective Equipment at Work Regulations 2022",
    ],
  },
  pl: {
    language: "pl-PL",
    jurisdiction: "Polska",
    safetyAuthority: "PIP",
    emergencyNumber: "112",
    controlledDocument: "Dokument nadzorowany. Przed użyciem sprawdź, czy jest to najnowsza zatwierdzona wersja.",
    legalReferencesHeading: "Podstawy prawne i wymagania (Polska)",
    ramsLegalReferences: [
      "Ustawa z dnia 26 czerwca 1974 r. – Kodeks pracy, dział X Bezpieczeństwo i higiena pracy",
      "Rozporządzenie Ministra Infrastruktury z dnia 6 lutego 2003 r. w sprawie BHP podczas wykonywania robót budowlanych",
      "Rozporządzenie Ministra Pracy i Polityki Socjalnej z dnia 26 września 1997 r. w sprawie ogólnych przepisów BHP",
      "Rozporządzenie Ministra Gospodarki z dnia 30 października 2002 r. w sprawie minimalnych wymagań dotyczących użytkowania maszyn przez pracowników podczas pracy",
      "Wymagania planu BIOZ, instrukcji bezpiecznego wykonywania robót i dokumentacji budowy – zgodnie z zakresem robót",
    ],
  },
  au: {
    language: "en-AU",
    jurisdiction: "Australia",
    safetyAuthority: "WHS regulator",
    emergencyNumber: "000",
    controlledDocument: "Controlled document. Confirm the current approved revision before use.",
    legalReferencesHeading: "Legal and regulatory references (Australia)",
    ramsLegalReferences: [
      "Applicable Work Health and Safety Act and Regulations for the state or territory",
      "Model Code of Practice: Construction Work",
      "Model Code of Practice: How to Manage Work Health and Safety Risks",
      "Model Code of Practice: Managing the Risk of Falls at Workplaces",
      "Applicable high risk construction work and SWMS requirements",
    ],
  },
  de: {
    language: "de-DE",
    jurisdiction: "Deutschland",
    safetyAuthority: "BG BAU",
    emergencyNumber: "112",
    controlledDocument: "Gelenktes Dokument. Vor Gebrauch die aktuell freigegebene Fassung prüfen.",
    legalReferencesHeading: "Rechts- und Vorschriftengrundlagen (Deutschland)",
    ramsLegalReferences: [
      "Arbeitsschutzgesetz (ArbSchG), insbesondere § 5 Gefährdungsbeurteilung",
      "Baustellenverordnung (BaustellV) — SiGe-Plan, Koordinator, Vorankündigung",
      "Betriebssicherheitsverordnung (BetrSichV)",
      "Gefahrstoffverordnung (GefStoffV)",
      "DGUV Vorschrift 1 — Grundsätze der Prävention",
    ],
  },
  at: {
    language: "de-AT",
    jurisdiction: "Österreich",
    safetyAuthority: "AUVA",
    emergencyNumber: "112",
    controlledDocument: "Gelenktes Dokument. Vor Gebrauch die aktuell freigegebene Fassung prüfen.",
    legalReferencesHeading: "Rechts- und Vorschriftengrundlagen (Österreich)",
    ramsLegalReferences: [
      "ArbeitnehmerInnenschutzgesetz (ASchG) — Evaluierung von Gefahren",
      "Bauarbeitenkoordinationsgesetz (BauKG) — SiGe-Plan, Koordinator, Vorankündigung",
      "Arbeitsmittelverordnung (AM-VO)",
      "Arbeitsstättenverordnung (AStV)",
      "AUVA — Unfallversicherung und Prävention",
    ],
  },
  ch: {
    language: "de-CH",
    jurisdiction: "Schweiz",
    safetyAuthority: "Suva",
    emergencyNumber: "112 / 144",
    controlledDocument: "Gelenktes Dokument. Vor Gebrauch die aktuell freigegebene Fassung prüfen.",
    legalReferencesHeading: "Rechts- und Vorschriftengrundlagen (Schweiz)",
    ramsLegalReferences: [
      "Arbeitsgesetz (ArG) und Verordnungen (ArGV 1–4)",
      "Bauarbeitenverordnung (BauAV) — SiKo vor Baubeginn, Notfallorganisation (Art. 4)",
      "Verordnung über die Unfallverhütung (VUV)",
      "EKAS-Richtlinien",
      "Suva — Unfallversicherung und Prävention",
    ],
  },
};

const PL_TEXT = {
  "Permit to work": "Pozwolenie na pracę",
  "Permit to work · controlled site document": "Pozwolenie na pracę · nadzorowany dokument budowy",
  "Work description": "Opis pracy",
  Location: "Lokalizacja",
  "Issued to": "Wydano dla",
  "Valid from": "Ważne od",
  Expires: "Ważne do",
  Start: "Rozpoczęcie",
  Expiry: "Termin ważności",
  "Issued by": "Wydał(a)",
  "Permit No.": "Nr pozwolenia",
  Status: "Status",
  Issued: "Wydano",
  "Pre-work checklist": "Lista kontrolna przed rozpoczęciem pracy",
  confirmed: "potwierdzono",
  "Checklist readiness": "Gotowość listy kontrolnej",
  "Conditions / restrictions": "Warunki i ograniczenia",
  Signatures: "Podpisy",
  Role: "Rola",
  Name: "Imię i nazwisko",
  Signature: "Podpis",
  "Date/Time": "Data i godzina",
  "Contractor acknowledgements (read & sign)": "Potwierdzenia wykonawców (przeczytaj i podpisz)",
  Note: "Uwagi",
  "Permit closure": "Zamknięcie pozwolenia",
  Closed: "Zamknięto",
  "Lessons learned": "Wnioski po zakończeniu",
  "Authorising role / competency": "Rola zatwierdzająca / kompetencje",
  "Briefing confirmed": "Potwierdzono odprawę",
  "Evidence notes": "Uwagi do materiału dowodowego",
  "Evidence photo": "Zdjęcie dokumentacyjne",
  "Stored in workspace (open app for signed access)": "Zapisano w obszarze roboczym (otwórz aplikację, aby uzyskać dostęp)",
  "Scan for live status": "Zeskanuj, aby sprawdzić aktualny status",
  "Gate check · site office · supervisor verification": "Kontrola wejścia · biuro budowy · weryfikacja nadzoru",
  Draft: "Wersja robocza",
  Active: "Aktywne",
  Approved: "Zatwierdzone",
  "Pending review": "Oczekuje na weryfikację",
  ClosedStatus: "Zamknięte",
  Expired: "Wygasło",
  Suspended: "Wstrzymane",
  IssuedStatus: "Wydane",
  "Internal review": "W weryfikacji wewnętrznej",
  Page: "Strona",
  "Survey Report": "Raport z badania",
  "Document control": "Nadzór nad dokumentem",
  "Prepared by": "Opracował(a)",
  "Checked by": "Sprawdził(a)",
  "Approved by": "Zatwierdził(a)",
  "Issue date": "Data wydania",
  Revision: "Rewizja",
  Client: "Klient",
  Project: "Projekt",
  "Project reference": "Numer projektu",
  "Survey date": "Data badania",
  Surveyor: "Geodeta / wykonawca badania",
  "Not recorded.": "Nie zarejestrowano.",
  Contents: "Spis treści",
  "Final report": "Raport końcowy",
  Final: "Końcowy",
  "Report completeness": "Kompletność raportu",
  "Report ref": "Numer raportu",
  Issue: "Wydanie",
  "Issue no.": "Nr wydania",
  Site: "Teren / adres",
  "Survey type": "Rodzaj badania",
  Completeness: "Kompletność",
  Field: "Pole",
  Value: "Wartość",
  Finalised: "Sfinalizowano",
  "Revision history": "Historia rewizji",
  Date: "Data",
  Rev: "Rew.",
  Author: "Autor",
  Description: "Opis",
  "Changes since previous issue": "Zmiany od poprzedniego wydania",
  "Records revision compare": "Porównanie rewizji materiałów źródłowych",
  "Report information": "Informacje o raporcie",
  "Surveyor / author": "Geodeta / autor",
  "Linked RAMS": "Powiązana IBWR",
  "Survey at a glance": "Podsumowanie badania",
  "Executive summary": "Podsumowanie wykonawcze",
  Foreword: "Wprowadzenie",
  "Survey programme": "Program badania",
  "Scope of works": "Zakres prac",
  Methodology: "Metodyka",
  "Survey workflow": "Przebieg badania",
  "Equipment used": "Użyty sprzęt",
  "Equipment calibration": "Kalibracja sprzętu",
  "Equipment datasheets": "Karty techniczne sprzętu",
  "Geological context": "Warunki geologiczne",
  "Survey extent": "Zakres przestrzenny badania",
  "Control & accuracy": "Osnowa i dokładność",
  "Weather at site": "Warunki pogodowe na terenie",
  "Utility records & drawings review": "Analiza materiałów i rysunków sieci",
  "Records references": "Wykaz materiałów źródłowych",
  "LSBUD / DBYD enquiry log": "Rejestr zapytań o sieci i uzbrojenie terenu",
  "Site overview": "Widok terenu",
  "Site location": "Lokalizacja terenu",
  Generated: "Wygenerowano",
  Hazard: "Zagrożenie",
  Activity: "Czynność",
  "Control measures": "Środki kontroli ryzyka",
  "Initial risk": "Ryzyko początkowe",
  "Residual risk": "Ryzyko resztkowe",
  "Emergency response": "Postępowanie awaryjne",
  "PPE and legal references pack": "Środki ochrony indywidualnej i podstawy prawne",
  "PPE roll-up": "Wymagane środki ochrony indywidualnej",
  "Signature evidence trail": "Rejestr potwierdzeń i podpisów",
  "Review due": "Termin przeglądu",
  "Site weather": "Warunki pogodowe na budowie",
  "Site map / location": "Mapa i lokalizacja budowy",
  Coordinates: "Współrzędne",
  Directions: "Trasa dojazdu",
  "Competence matrix": "Macierz kompetencji",
  "Certificates / notes": "Uprawnienia / uwagi",
  "Risk assessment and controls": "Ocena ryzyka i środki kontroli",
  "Additional hazard": "Dodatkowe zagrożenie",
  "Risk factor": "Współczynnik ryzyka",
  "Revised RF": "Ryzyko po zastosowaniu środków",
  High: "Wysokie",
  Medium: "Średnie",
  Low: "Niskie",
  "Average reduction": "Średnia redukcja",
  "Method statement (risk reduction steps)": "Instrukcja wykonania robót (etapy ograniczania ryzyka)",
  Step: "Etap",
  "Control method to reduce risk": "Sposób ograniczenia ryzyka",
  "Sign-off list": "Lista zapoznania i podpisów",
  "Operative signatures": "Podpisy pracowników",
  "Document integrity": "Integralność dokumentu",
  "Document no.": "Nr dokumentu",
  "Job reference": "Numer zlecenia",
  "Lead engineer": "Osoba prowadząca",
  "Regulatory references": "Podstawy prawne",
  "Controlled site safety document": "Nadzorowany dokument bezpieczeństwa robót",
  Organisation: "Organizacja",
  Document: "Dokument",
  Reference: "Numer referencyjny",
  "Controlled register export": "Nadzorowany eksport rejestru",
  "Controlled site document": "Nadzorowany dokument budowy",
  "Powered export": "Eksport MySafeOps",
  Notes: "Uwagi",
  Authorisation: "Zatwierdzenie",
  "Assessed / completed by": "Ocenił(a) / wykonał(a)",
  "Reviewed / authorised by": "Sprawdził(a) / zatwierdził(a)",
};

const DE_TEXT = {
  "Permit to work": "Erlaubnisschein",
  "Permit to work · controlled site document": "Erlaubnisschein · gelenktes Baustellendokument",
  "Work description": "Arbeitsbeschreibung",
  Location: "Ort",
  "Issued to": "Ausgestellt für",
  "Valid from": "Gültig ab",
  Expires: "Gültig bis",
  Start: "Beginn",
  Expiry: "Ablauf",
  "Issued by": "Ausgestellt von",
  "Permit No.": "Schein-Nr.",
  Status: "Status",
  Issued: "Ausgestellt",
  "Pre-work checklist": "Checkliste vor Arbeitsbeginn",
  confirmed: "bestätigt",
  "Checklist readiness": "Checklistenbereitschaft",
  "Conditions / restrictions": "Auflagen / Einschränkungen",
  Signatures: "Unterschriften",
  Role: "Rolle",
  Name: "Name",
  Signature: "Unterschrift",
  "Date/Time": "Datum/Uhrzeit",
  "Contractor acknowledgements (read & sign)": "Bestätigungen der Unternehmen (lesen und unterschreiben)",
  Note: "Hinweis",
  "Permit closure": "Abschluss des Scheins",
  Closed: "Abgeschlossen",
  "Lessons learned": "Erkenntnisse",
  "Authorising role / competency": "Freigabeberechtigung / Qualifikation",
  "Briefing confirmed": "Unterweisung bestätigt",
  "Evidence notes": "Nachweisnotizen",
  "Evidence photo": "Nachweisfoto",
  "Stored in workspace (open app for signed access)": "Im Arbeitsbereich gespeichert (App für Zugriff öffnen)",
  "Scan for live status": "Für den aktuellen Status scannen",
  "Gate check · site office · supervisor verification": "Pforte · Bauleitung · Prüfung durch Aufsicht",
  Draft: "Entwurf",
  Active: "Aktiv",
  Approved: "Freigegeben",
  "Pending review": "In Prüfung",
  ClosedStatus: "Abgeschlossen",
  Expired: "Abgelaufen",
  Suspended: "Ausgesetzt",
  IssuedStatus: "Ausgestellt",
  "Internal review": "Interne Prüfung",
  Page: "Seite",
  "Survey Report": "Untersuchungsbericht",
  "Document control": "Dokumentenlenkung",
  "Prepared by": "Erstellt von",
  "Checked by": "Geprüft von",
  "Approved by": "Freigegeben von",
  "Issue date": "Ausgabedatum",
  Revision: "Revision",
  Client: "Auftraggeber",
  Project: "Projekt",
  "Project reference": "Projektnummer",
  "Survey date": "Untersuchungsdatum",
  Surveyor: "Vermesser / Gutachter",
  "Not recorded.": "Nicht erfasst.",
  Contents: "Inhalt",
  "Final report": "Abschlussbericht",
  Final: "Endgültig",
  "Report completeness": "Vollständigkeit des Berichts",
  "Report ref": "Berichtsnummer",
  Issue: "Ausgabe",
  "Issue no.": "Ausg.-Nr.",
  Site: "Baustelle / Adresse",
  "Survey type": "Untersuchungsart",
  Completeness: "Vollständigkeit",
  Field: "Feld",
  Value: "Wert",
  Finalised: "Abgeschlossen",
  "Revision history": "Revisionshistorie",
  Date: "Datum",
  Rev: "Rev.",
  Author: "Verfasser",
  Description: "Beschreibung",
  "Changes since previous issue": "Änderungen seit der letzten Ausgabe",
  "Records revision compare": "Vergleich der Quellunterlagen",
  "Report information": "Berichtsinformationen",
  "Surveyor / author": "Vermesser / Verfasser",
  "Linked RAMS": "Verknüpfte GBU",
  "Survey at a glance": "Untersuchung im Überblick",
  "Executive summary": "Kurzfassung",
  Foreword: "Vorwort",
  "Survey programme": "Untersuchungsprogramm",
  "Scope of works": "Leistungsumfang",
  Methodology: "Methodik",
  "Survey workflow": "Untersuchungsablauf",
  "Equipment used": "Verwendete Geräte",
  "Equipment calibration": "Kalibrierung",
  "Equipment datasheets": "Geräte-Datenblätter",
  "Geological context": "Geologischer Kontext",
  "Survey extent": "Räumlicher Umfang",
  "Control & accuracy": "Lagebezug und Genauigkeit",
  "Weather at site": "Wetter auf der Baustelle",
  "Utility records & drawings review": "Prüfung von Leitungsunterlagen",
  "Records references": "Quellenverzeichnis",
  "LSBUD / DBYD enquiry log": "Anfragenprotokoll Leitungsauskunft",
  "Site overview": "Baustellenübersicht",
  "Site location": "Lage der Baustelle",
  Generated: "Erstellt",
  Hazard: "Gefährdung",
  Activity: "Tätigkeit",
  "Control measures": "Schutzmaßnahmen",
  "Initial risk": "Ausgangsrisiko",
  "Residual risk": "Restrisiko",
  "Emergency response": "Notfallmaßnahmen",
  "PPE and legal references pack": "PSA und Rechtsgrundlagen",
  "PPE roll-up": "Erforderliche PSA",
  "Signature evidence trail": "Unterschriftennachweis",
  "Review due": "Prüftermin",
  "Site weather": "Baustellenwetter",
  "Site map / location": "Lageplan / Standort",
  Coordinates: "Koordinaten",
  Directions: "Anfahrt",
  "Competence matrix": "Qualifikationsmatrix",
  "Certificates / notes": "Nachweise / Hinweise",
  "Risk assessment and controls": "Gefährdungsbeurteilung und Maßnahmen",
  "Additional hazard": "Zusätzliche Gefährdung",
  "Risk factor": "Risikofaktor",
  "Revised RF": "Risiko nach Maßnahmen",
  High: "Hoch",
  Medium: "Mittel",
  Low: "Niedrig",
  "Average reduction": "Mittlere Reduktion",
  "Method statement (risk reduction steps)": "Betriebsanweisung (Maßnahmen zur Risikominderung)",
  Step: "Schritt",
  "Control method to reduce risk": "Maßnahme zur Risikominderung",
  "Sign-off list": "Unterweisungs- und Unterschriftenliste",
  "Operative signatures": "Unterschriften der Beschäftigten",
  "Document integrity": "Dokumentintegrität",
  "Document no.": "Dokument-Nr.",
  "Job reference": "Auftragsnummer",
  "Lead engineer": "Verantwortliche Person",
  "Regulatory references": "Rechtsgrundlagen",
  "Controlled site safety document": "Gelenktes Arbeitsschutzdokument der Baustelle",
  Organisation: "Organisation",
  Document: "Dokument",
  Reference: "Referenz",
  "Controlled register export": "Gelenkter Registerexport",
  "Controlled site document": "Gelenktes Baustellendokument",
  "Powered export": "MySafeOps-Export",
  Notes: "Hinweise",
  Authorisation: "Freigabe",
  "Assessed / completed by": "Bewertet / ausgeführt von",
  "Reviewed / authorised by": "Geprüft / freigegeben von",
};

export function getDocumentCountryPack(marketId = getOrgMarketId()) {
  const id =
    marketId === "pl" || marketId === "au" || marketId === "de" || marketId === "at" || marketId === "ch"
      ? marketId
      : "uk";
  return { marketId: id, ...COMMON[id] };
}

export function documentText(key, fallback = key, marketId = getOrgMarketId()) {
  if (marketId === "pl") return PL_TEXT[key] || fallback;
  if (marketId === "de" || marketId === "at" || marketId === "ch") return DE_TEXT[key] || fallback;
  return fallback;
}

export function documentStatusLabel(status, marketId = getOrgMarketId()) {
  const normalized = String(status || "draft").toLowerCase();
  const keys = {
    draft: "Draft",
    active: "Active",
    approved: "Approved",
    pending_review: "Pending review",
    closed: "ClosedStatus",
    expired: "Expired",
    suspended: "Suspended",
    issued: "IssuedStatus",
    internal_review: "Internal review",
  };
  return documentText(keys[normalized] || "Draft", normalized.replace(/_/g, " "), marketId).toUpperCase();
}
