export const ms = {
  btn: {
    padding: "11px 16px",
    borderRadius: "var(--radius-sm, 10px)",
    border: "1px solid var(--color-border-secondary,#cbd5e1)",
    background: "var(--color-background-primary,#fff)",
    color: "var(--color-text-primary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "DM Sans,sans-serif",
    minHeight: 44,
    lineHeight: 1.3,
    boxShadow: "var(--shadow-sm, 0 1px 2px rgba(15,23,42,0.04))",
    transition: "background 0.18s ease, border-color 0.18s ease, box-shadow 0.18s ease, transform 0.12s ease",
  },
  btnP: {
    padding: "11px 16px",
    borderRadius: "var(--radius-sm, 10px)",
    border: "1px solid #0f766e",
    background: "linear-gradient(180deg, #14b8a6 0%, #0d9488 55%, #0f766e 100%)",
    color: "#f0fdfa",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "DM Sans,sans-serif",
    minHeight: 44,
    lineHeight: 1.3,
    boxShadow: "0 2px 8px rgba(13, 148, 136, 0.32)",
    transition: "filter 0.18s ease, box-shadow 0.18s ease, transform 0.12s ease",
  },
  btnDanger: {
    padding: "11px 16px",
    borderRadius: "var(--radius-sm, 10px)",
    border: "1px solid #fecaca",
    background: "var(--color-background-primary,#fff)",
    color: "#A32D2D",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "DM Sans,sans-serif",
    minHeight: 44,
    lineHeight: 1.3,
    boxShadow: "var(--shadow-sm, 0 1px 2px rgba(15,23,42,0.05))",
    transition: "background 0.15s ease, border-color 0.15s ease",
  },
  inp: {
    width: "100%",
    padding: "11px 14px",
    border: "1px solid var(--color-border-secondary,#cbd5e1)",
    borderRadius: "var(--radius-sm, 10px)",
    fontSize: 14,
    fontFamily: "DM Sans,sans-serif",
    boxSizing: "border-box",
    minHeight: 44,
    background: "var(--color-background-primary,#fff)",
    color: "var(--color-text-primary)",
    transition: "border-color 0.18s ease, box-shadow 0.18s ease",
  },
  lbl: {
    display: "block",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--color-text-secondary)",
    marginBottom: 6,
    letterSpacing: "0.01em",
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: "999px",
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 1.2,
    letterSpacing: "0.01em",
    border: "1px solid var(--color-border-tertiary,#e2e8f0)",
    background: "var(--color-background-secondary,#f8fafc)",
    color: "var(--color-text-secondary)",
    textTransform: "capitalize",
  },
  card: {
    background: "var(--color-background-primary,#fff)",
    border: "1px solid rgba(226, 232, 240, 0.95)",
    borderRadius: "var(--radius-md, 14px)",
    padding: "1.25rem",
    overflow: "hidden",
    boxShadow: "var(--shadow-card, 0 1px 2px rgba(15,23,42,0.04), 0 6px 20px rgba(15,23,42,0.05))",
  },
  pageTitle: {
    fontWeight: 600,
    fontSize: 23,
    margin: 0,
    letterSpacing: "-0.025em",
    color: "var(--color-text-primary)",
    lineHeight: 1.2,
  },
  pageLead: {
    fontSize: 14,
    color: "var(--color-text-secondary)",
    margin: "10px 0 0",
    lineHeight: 1.6,
    maxWidth: 640,
  },
  overlay: {
    minHeight: "100vh",
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "1.5rem 1rem calc(1.5rem + env(safe-area-inset-bottom, 0px))",
    position: "fixed",
    inset: 0,
    zIndex: 50,
    overflow: "auto",
    WebkitOverflowScrolling: "touch",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  toolbarActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  formFooter: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
    flexWrap: "wrap",
    marginTop: 16,
  },
  cardRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  cardActions: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    flexShrink: 0,
  },
  cardText: {
    minWidth: 0,
    flex: 1,
    overflow: "hidden",
  },
  twoCol: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(160px, 100%), 1fr))",
    gap: 10,
    marginTop: 10,
  },
  pageRoot: {
    fontFamily: "DM Sans,system-ui,sans-serif",
    padding: "1.25rem 0",
    fontSize: 14,
  },
};
