import { getOrgId, loadOrgScoped, orgScopedKey, saveOrgScoped } from "./orgStorage";

export const ORG_SETTINGS_BASE_KEY = "mysafeops_org_settings";
export const ORG_SETTINGS_UPDATED_EVENT = "mysafeops-org-settings-updated";
const ORG_SETTINGS_UPDATED_AT_KEY = "mysafeops_org_settings_updated_at";

/** @returns {Record<string, unknown>} */
export function loadOrgSettingsRaw(orgId = getOrgId()) {
  const scoped = loadOrgScoped(ORG_SETTINGS_BASE_KEY, null);
  if (scoped && typeof scoped === "object" && Object.keys(scoped).length > 0) {
    return scoped;
  }
  try {
    const legacy = JSON.parse(localStorage.getItem(ORG_SETTINGS_BASE_KEY) || "{}");
    if (legacy && typeof legacy === "object" && Object.keys(legacy).length > 0 && orgId && orgId !== "default") {
      saveOrgScoped(ORG_SETTINGS_BASE_KEY, legacy);
      return legacy;
    }
    return legacy && typeof legacy === "object" ? legacy : {};
  } catch {
    return {};
  }
}

/** @param {Record<string, unknown>} value @param {string} [orgId] @param {string} [updatedAtIso] */
export function saveOrgSettingsRaw(value, orgId = getOrgId(), updatedAtIso) {
  saveOrgScoped(ORG_SETTINGS_BASE_KEY, value);
  if (updatedAtIso) {
    localStorage.setItem(`${ORG_SETTINGS_UPDATED_AT_KEY}_${orgId}`, updatedAtIso);
  }
  window.dispatchEvent(new CustomEvent(ORG_SETTINGS_UPDATED_EVENT, { detail: { orgId } }));
}

export function getLocalOrgBrandingUpdatedAt(orgId = getOrgId()) {
  return localStorage.getItem(`${ORG_SETTINGS_UPDATED_AT_KEY}_${orgId}`) || "";
}

export function getOrgSettings(orgId = getOrgId()) {
  const s = loadOrgSettingsRaw(orgId);
  return {
    name: s.name || "My Organisation",
    logo: s.logo || null,
    address: s.address || "",
    phone: s.phone || "",
    email: s.email || "",
    website: s.website || "",
    primaryColor: s.primaryColor || "#0d9488",
    accentColor: s.accentColor || "#f97316",
    pdfFooter: s.pdfFooter || "Generated by MySafeOps — mysafeops.com",
    pdfHeader: s.pdfHeader || "",
    pdfWatermarkText: s.pdfWatermarkText || "",
    pdfTheme: s.pdfTheme || "executive",
    pdfVersionPrefix: s.pdfVersionPrefix || "MSO",
    pdfComplianceLine: s.pdfComplianceLine || "Controlled document. Ensure latest approved revision is in use.",
    registrationNo: s.registrationNo || "",
    vatNo: s.vatNo || "",
    defaultLeadEngineer: s.defaultLeadEngineer || "",
    locale: s.locale || "",
    safetyPolicy: s.safetyPolicy || "",
    emergencyContact: s.emergencyContact || "",
    customFields: s.customFields || [],
    industrySectors:
      Array.isArray(s.industrySectors) && s.industrySectors.length ? s.industrySectors : ["construction"],
  };
}

/** Keys included in cloud branding sync (excludes device-only customFields unless present). */
export function pickCloudBrandingPayload(raw) {
  const s = raw && typeof raw === "object" ? raw : {};
  const out = {
    name: s.name,
    logo: s.logo,
    logoUrl: s.logoUrl,
    address: s.address,
    phone: s.phone,
    email: s.email,
    website: s.website,
    primaryColor: s.primaryColor,
    accentColor: s.accentColor,
    pdfFooter: s.pdfFooter,
    pdfHeader: s.pdfHeader,
    pdfWatermarkText: s.pdfWatermarkText,
    pdfTheme: s.pdfTheme,
    pdfVersionPrefix: s.pdfVersionPrefix,
    pdfComplianceLine: s.pdfComplianceLine,
    registrationNo: s.registrationNo,
    vatNo: s.vatNo,
    defaultLeadEngineer: s.defaultLeadEngineer,
    locale: s.locale,
    safetyPolicy: s.safetyPolicy,
    emergencyContact: s.emergencyContact,
    industrySectors: s.industrySectors,
  };
  if (Array.isArray(s.customFields) && s.customFields.length) {
    out.customFields = s.customFields;
  }
  if (Array.isArray(s.hiddenModules) && s.hiddenModules.length) {
    out.hiddenModules = s.hiddenModules;
  }
  if (Array.isArray(s.hiddenFeatures) && s.hiddenFeatures.length) {
    out.hiddenFeatures = s.hiddenFeatures;
  }
  if (typeof s.bottomNavModuleId === "string" && s.bottomNavModuleId) {
    out.bottomNavModuleId = s.bottomNavModuleId;
  }
  if (typeof s.industryPackId === "string" && s.industryPackId) {
    out.industryPackId = s.industryPackId;
  }
  if (s.onboardingWizardCompleted) {
    out.onboardingWizardCompleted = true;
  }
  return out;
}

export function orgSettingsStorageKey(orgId = getOrgId()) {
  return orgScopedKey(ORG_SETTINGS_BASE_KEY);
}
