import { getOrgId, orgScopedKey } from "./orgId";
import { loadOrgScoped, saveOrgScoped } from "./orgStorage";
import { resolveMarketId, isValidMarketId } from "../config/markets";

export const ORG_SETTINGS_BASE_KEY = "mysafeops_org_settings";
export const ORG_SETTINGS_UPDATED_EVENT = "mysafeops-org-settings-updated";
const ORG_SETTINGS_UPDATED_AT_KEY = "mysafeops_org_settings_updated_at";

/** @returns {Record<string, unknown>} */
export function loadOrgSettingsRaw(orgId = getOrgId()) {
  const scoped = loadOrgScoped(ORG_SETTINGS_BASE_KEY, null);
  if (scoped && typeof scoped === "object" && Object.keys(scoped).length > 0) {
    return scoped;
  }
  try {
    const legacyRaw = localStorage.getItem(ORG_SETTINGS_BASE_KEY);
    const legacy = legacyRaw ? JSON.parse(legacyRaw) : {};
    if (legacy && typeof legacy === "object" && Object.keys(legacy).length > 0 && orgId && orgId !== "default") {
      // One-shot migrate into this org, then delete the unscoped key so a *new*
      // workspace never inherits another org's branding (e.g. Landorahub → Patryk).
      saveOrgScoped(ORG_SETTINGS_BASE_KEY, legacy);
      try {
        localStorage.removeItem(ORG_SETTINGS_BASE_KEY);
      } catch {
        /* ignore */
      }
      return legacy;
    }
    return legacy && typeof legacy === "object" ? legacy : {};
  } catch {
    return {};
  }
}

/** @param {Record<string, unknown>} value @param {string} [orgId] @param {string} [updatedAtIso] */
export function saveOrgSettingsRaw(value, orgId = getOrgId(), updatedAtIso) {
  // Org configuration (branding, sectors, automation, modules) — always writable so admins
  // can prepare workspace before/after subscribe; HSE records stay read-only when trial ended.
  saveOrgScoped(ORG_SETTINGS_BASE_KEY, value, { bypassBillingGuard: true });
  if (updatedAtIso) {
    localStorage.setItem(`${ORG_SETTINGS_UPDATED_AT_KEY}_${orgId}`, updatedAtIso);
  }
  window.dispatchEvent(new CustomEvent(ORG_SETTINGS_UPDATED_EVENT, { detail: { orgId } }));
}

export function getLocalOrgBrandingUpdatedAt(orgId = getOrgId()) {
  return localStorage.getItem(`${ORG_SETTINGS_UPDATED_AT_KEY}_${orgId}`) || "";
}

export function getOrgSettings(orgId = getOrgId()) {
  const s = loadOrgSettingsRaw(orgId);
  const logo = s.logo || s.logoUrl || null;
  return {
    name: s.name || "My Organisation",
    logo,
    logoUrl: s.logoUrl || (typeof logo === "string" && logo.startsWith("/") ? logo : "") || "",
    address: s.address || "",
    phone: s.phone || "",
    email: s.email || "",
    website: s.website || "",
    primaryColor: s.primaryColor || "#0d9488",
    accentColor: s.accentColor || "#f97316",
    pdfFooter: s.pdfFooter || "Generated by MySafeOps — mysafeops.com",
    pdfHeader: s.pdfHeader || "",
    pdfWatermarkText: s.pdfWatermarkText || "",
    pdfTheme: s.pdfTheme || "executive",
    pdfVersionPrefix: s.pdfVersionPrefix || "MSO",
    pdfComplianceLine: s.pdfComplianceLine || "Controlled document. Ensure latest approved revision is in use.",
    registrationNo: s.registrationNo || "",
    vatNo: s.vatNo || "",
    defaultLeadEngineer: s.defaultLeadEngineer || "",
    locale: s.locale || "",
    safetyPolicy: s.safetyPolicy || "",
    emergencyContact: s.emergencyContact || "",
    customFields: s.customFields || [],
    industrySectors:
      Array.isArray(s.industrySectors) && s.industrySectors.length ? s.industrySectors : ["construction"],
    market: resolveMarketId(s.market),
  };
}

/** Keys included in cloud branding sync (excludes device-only customFields unless present). */
export function pickCloudBrandingPayload(raw) {
  const s = raw && typeof raw === "object" ? raw : {};
  const out = {
    name: s.name,
    logo: s.logo,
    logoUrl: s.logoUrl,
    address: s.address,
    phone: s.phone,
    email: s.email,
    website: s.website,
    primaryColor: s.primaryColor,
    accentColor: s.accentColor,
    pdfFooter: s.pdfFooter,
    pdfHeader: s.pdfHeader,
    pdfWatermarkText: s.pdfWatermarkText,
    pdfTheme: s.pdfTheme,
    pdfVersionPrefix: s.pdfVersionPrefix,
    pdfComplianceLine: s.pdfComplianceLine,
    registrationNo: s.registrationNo,
    vatNo: s.vatNo,
    defaultLeadEngineer: s.defaultLeadEngineer,
    locale: s.locale,
    safetyPolicy: s.safetyPolicy,
    emergencyContact: s.emergencyContact,
    industrySectors: s.industrySectors,
  };
  if (Array.isArray(s.customFields) && s.customFields.length) {
    out.customFields = s.customFields;
  }
  if (Array.isArray(s.hiddenModules) && s.hiddenModules.length) {
    out.hiddenModules = s.hiddenModules;
  }
  if (Array.isArray(s.hiddenFeatures) && s.hiddenFeatures.length) {
    out.hiddenFeatures = s.hiddenFeatures;
  }
  if (typeof s.bottomNavModuleId === "string" && s.bottomNavModuleId) {
    out.bottomNavModuleId = s.bottomNavModuleId;
  }
  if (typeof s.industryPackId === "string" && s.industryPackId) {
    out.industryPackId = s.industryPackId;
  }
  if (isValidMarketId(s.market)) {
    out.market = s.market;
  }
  if (s.onboardingWizardCompleted) {
    out.onboardingWizardCompleted = true;
  }
  if (s.automationRules && typeof s.automationRules === "object") {
    out.automationRules = s.automationRules;
  }
  if (s.surveyTypeTemplates && typeof s.surveyTypeTemplates === "object") {
    out.surveyTypeTemplates = s.surveyTypeTemplates;
  }
  if (s.msStepTemplates && typeof s.msStepTemplates === "object") {
    out.msStepTemplates = s.msStepTemplates;
  }
  if (Array.isArray(s.customWorkspaceProfiles) && s.customWorkspaceProfiles.length) {
    out.customWorkspaceProfiles = s.customWorkspaceProfiles;
  }
  return out;
}

export function orgSettingsStorageKey(_orgId = getOrgId()) {
  return orgScopedKey(ORG_SETTINGS_BASE_KEY);
}
