/**
 * Starter records for empty HSE registers (one template row per module).
 */
import { MODULE_PDF_REGISTRY } from "../navigation/moduleCatalogMeta";
import { loadOrgScoped, saveOrgScoped } from "./orgStorage";

const genId = (prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
const now = () => new Date().toISOString();
const today = () => now().slice(0, 10);

/** @type {Record<string, () => object>} */
const SEED_FACTORIES = {
  fire: () => ({
    id: genId("fire"),
    checkType: "Fire extinguisher",
    location: "Site entrance / welfare",
    checkDate: today(),
    satisfactory: true,
    checkedBy: "",
    notes: "Template row — complete after first weekly check",
    createdAt: now(),
  }),
  emergency: () => ({
    id: genId("ec"),
    label: "Site supervisor / manager",
    phone: "",
    notes: "Add out-of-hours contact",
    createdAt: now(),
  }),
  ppe: () => ({
    id: genId("ppe"),
    itemType: "Hi-vis vest",
    workerName: "",
    issuedDate: today(),
    status: "issued",
    notes: "Template — issue PPE to workers on site",
    createdAt: now(),
  }),
  "first-aid": () => ({
    id: genId("fa"),
    name: "",
    role: "First aider",
    certExpiry: "",
    notes: "Add qualified first aider(s) for this site",
    createdAt: now(),
  }),
  "toolbox-reg": () => ({
    id: genId("tt"),
    topic: "Site induction / key hazards",
    talkDate: today(),
    presenter: "",
    attendeeCount: "",
    summary: "Template toolbox talk — update topic and attendees",
    createdAt: now(),
  }),
  "daily-briefing": () => ({
    id: genId("brief"),
    date: today(),
    time: new Date().toTimeString().slice(0, 5),
    location: "Site / project name",
    conductedBy: "",
    weatherConditions: "",
    temperature: "",
    topics: ["PPE requirements for today's tasks", "Emergency evacuation procedure and muster point reminder"],
    customTopics: "",
    scopeToday: "Template — describe today's scope of work",
    attendees: [],
    notes: "Template briefing — replace with real attendance and signatures on site",
    createdAt: now(),
  }),
  inspections: () => ({
    id: genId("insp"),
    type: "general",
    name: "Weekly site inspection",
    serialNo: "",
    location: "Site wide",
    inspectedAt: today(),
    status: "scheduled",
    inspector: "",
    notes: "Template — schedule LOLER/PSSR inspections as required",
    createdAt: now(),
  }),
  snags: () => ({
    id: genId("snag"),
    ref: "SN-001",
    title: "Template snag — replace with real item",
    status: "open",
    priority: "medium",
    location: "Site area",
    notes: "Log defects during walk-round or client handover",
    createdAt: now(),
  }),
  "gmp-deviations": () => ({
    id: genId("gmp"),
    ref: "GMP-001",
    title: "Template deviation record",
    status: "open",
    openedAt: today(),
    notes: "Document process deviations and corrective actions",
    createdAt: now(),
  }),
  "allergen-changeovers": () => ({
    id: genId("acw"),
    label: "Template changeover window",
    siteLabel: "Production line",
    fromAllergen: "Example allergen A",
    toAllergen: "Example allergen B",
    startAt: `${today()}T06:00`,
    endAt: `${today()}T14:00`,
    extraPpeHint: "Full gowning and line clearance before start",
    createdAt: now(),
  }),
  visitors: () => ({
    id: genId("vis"),
    name: "",
    company: "",
    signedInAt: now(),
    signedOutAt: "",
    purpose: "Site visit",
    notes: "Template visitor line",
    createdAt: now(),
  }),
  environmental: () => ({
    id: genId("env"),
    type: "Dust / noise observation",
    reading: "",
    recordedAt: today(),
    notes: "Template environmental log entry",
    createdAt: now(),
  }),
  observations: () => ({
    id: genId("obs"),
    type: "positive",
    description: "Template — record safe/unsafe observations on site",
    status: "open",
    reportedAt: today(),
    createdAt: now(),
  }),
  ladders: () => ({
    id: genId("lad"),
    tagId: "LAD-001",
    result: "pass",
    inspectedAt: today(),
    notes: "Template ladder inspection — tag all ladders on site",
    createdAt: now(),
  }),
  welfare: () => ({
    id: genId("wel"),
    location: "Welfare unit",
    checkedAt: today(),
    notes: "Template welfare check — water, heating, cleanliness",
    createdAt: now(),
  }),
  waste: () => ({
    id: genId("wst"),
    wasteType: "Mixed construction waste",
    quantity: "",
    disposedAt: today(),
    notes: "Template waste transfer note reference",
    createdAt: now(),
  }),
  plant: () => ({
    id: genId("plt"),
    name: "Excavator / MEWP (example)",
    assetTag: "",
    status: "on_site",
    nextInspection: "",
    notes: "Template plant item — add all hired/plant on site",
    createdAt: now(),
  }),
  training: () => ({
    id: genId("trn"),
    workerName: "",
    course: "CSCS / induction",
    expiryDate: "",
    status: "valid",
    notes: "Template training matrix row",
    createdAt: now(),
  }),
  "hot-work": () => ({
    id: genId("hw"),
    ref: `HW-${today().replace(/-/g, "")}`,
    location: "",
    status: "draft",
    startDate: today(),
    notes: "Template hot work permit register line",
    createdAt: now(),
  }),
  riddor: () => ({
    id: genId("riddor"),
    riddorType: "specified",
    projectId: "",
    incidentDate: today(),
    incidentTime: "",
    location: "Site / welfare area (template)",
    siteAddress: "",
    injuredName: "",
    incidentDescription: "Template RIDDOR worksheet — replace with actual incident details before reporting to HSE",
    workBeingDone: "",
    causeOfIncident: "",
    status: "draft",
    reportedToHSE: false,
    hseReportRef: "",
    hseReportDate: "",
    createdAt: now(),
  }),
  coshh: () => ({
    id: genId("coshh"),
    name: "Example — cement / silica-containing product",
    manufacturer: "",
    productCode: "",
    projectId: "",
    hazardTypes: ["dust"],
    exposureRoutes: ["inhalation"],
    riskLevel: "medium",
    quantity: "",
    unit: "litres",
    storageLocation: "On-site store / COSHH cupboard",
    storageNotes: "Template row — add SDS and complete COSHH assessment",
    ppeRequired: ["gloves", "eye_protection"],
    sdsUrl: "",
    sdsReviewDate: "",
    assessedBy: "",
    assessedDate: today(),
    notes: "Replace with substances actually used on site",
    createdAt: now(),
  }),
  scaffold: () => ({
    id: genId("scf"),
    tagRef: "SCF-001",
    supplierOrErector: "",
    maxLiftHeight: "",
    location: "Main elevation / grid A1 (template)",
    projectId: "",
    inspectionDate: today(),
    nextInspectionDue: "",
    result: "pass",
    inspector: "",
    handoverCertRef: "",
    notes: "Template scaffold inspection — tag all scaffolds on site (TG20:21)",
    createdAt: now(),
  }),
  incidents: () => ({
    id: genId("inc"),
    type: "near_miss",
    occurredAt: `${today()}T12:00`,
    location: "Site wide",
    projectId: "",
    description: "Template near-miss — record slips, trips, plant movements and unsafe acts",
    severity: "medium",
    injuryInvolved: false,
    immediateActions: "",
    status: "open",
    reportedBy: "",
    quickFlags: [],
    quickSummary: "",
    photos: [],
    gpsLat: null,
    gpsLng: null,
    createdAt: now(),
  }),
  "incident-actions": () => ({
    id: genId("ia"),
    title: "Template corrective action — assign owner and due date",
    owner: "",
    dueDate: "",
    priority: "medium",
    status: "open",
    sourceType: "incident",
    sourceId: "",
    sourceLabel: "Template",
    sourceProjectName: "",
    correctiveAction: "Describe action to prevent recurrence",
    verificationNote: "",
    createdAt: now(),
  }),
  asbestos: () => ({
    id: genId("asb"),
    location: "Plant room / ceiling void (example)",
    buildingArea: "",
    projectId: "",
    surveyRef: "",
    materialDescription: "Presumed ACM — verify with survey",
    asbestosType: "Presumed",
    riskAssessmentRef: "",
    lastReviewDate: today(),
    nextReviewDate: "",
    notes: "Template asbestos register line — update from refurbishment survey",
    createdAt: now(),
  }),
  "confined-space": () => ({
    id: genId("cs"),
    permitRef: "",
    spaceDescription: "Manhole / chamber (template)",
    projectId: "",
    entryDate: today(),
    timeStart: "08:00",
    timeEnd: "",
    entrants: "",
    topMan: "",
    gasTestOk: false,
    rescuePlanRef: "",
    notes: "Template confined space entry log — link to PTW",
    createdAt: now(),
  }),
  loto: () => ({
    id: genId("loto"),
    equipmentName: "Main isolator / panel (example)",
    equipmentTag: "",
    projectId: "",
    projectName: "",
    phase: "draft",
    isolationPoints: [
      {
        id: genId("iso"),
        type: "electrical",
        description: "Template isolation point — describe breaker / valve",
        lockNumber: "",
        tagNumber: "",
        lockedBy: "",
        lockedAt: null,
        verifiedBy: "",
        verifiedAt: null,
        unlockedBy: "",
        unlockedAt: null,
      },
    ],
    zeroEnergyVerified: false,
    zeroEnergyMethod: "",
    zeroEnergyVerifiedBy: "",
    linkedHotWorkIds: [],
    notes: "Template LOTO record — complete isolation workflow before live work",
    createdAt: now(),
    updatedAt: now(),
  }),
  "electrical-pat": () => ({
    id: genId("pat"),
    assetTag: "PAT-001",
    description: "110V transformer / extension lead (example)",
    location: "Welfare / site office",
    projectId: "",
    testDate: today(),
    nextTestDue: "",
    result: "pass",
    testedBy: "",
    notes: "Template PAT record — test all portable electrical equipment on site",
    createdAt: now(),
  }),
  lifting: () => ({
    id: genId("lift"),
    liftRef: "LIFT-001",
    loadDescription: "Template lift — describe load and rigging",
    weightEstimate: "",
    craneOrLift: "",
    projectId: "",
    liftDate: today(),
    appointedPerson: "",
    slingerSignaller: "",
    liftSupervisor: "",
    methodStatementRef: "",
    briefingDone: false,
    notes: "Template lifting plan register row (BS 7121 / LOLER)",
    createdAt: now(),
  }),
  excavation: () => ({
    id: genId("exc"),
    permitRef: "",
    workDescription: "Trial pit / service trench (template)",
    maxDepth: "",
    shoringSystem: "",
    location: "",
    projectId: "",
    workDate: today(),
    utilitiesConfirmed: false,
    utilitySearchRef: "",
    banksmanName: "",
    status: "open",
    closedDate: "",
    notes: "Template excavation log — confirm utility searches before dig",
    createdAt: now(),
  }),
  "temp-works": () => ({
    id: genId("tw"),
    twRef: "TW-001",
    description: "Propping / needling (template)",
    category: "Propping / needling",
    designBriefRef: "",
    checkerCatRef: "",
    location: "",
    projectId: "",
    inspectionDate: today(),
    nextCheckDue: "",
    inspector: "",
    status: "in_use",
    notes: "Template temporary works register — assign TW coordinator",
    createdAt: now(),
  }),
  mewp: () => ({
    id: genId("mewp"),
    equipmentRef: "MEWP-001",
    mewpType: "Scissor lift",
    operatorName: "",
    licenceRef: "",
    checkDate: today(),
    projectId: "",
    preUseOk: true,
    groundConditionsOk: true,
    notes: "Template MEWP daily check — operator card and pre-use inspection",
    createdAt: now(),
  }),
  gate: () => ({
    id: genId("gate"),
    visitDate: today(),
    timeIn: "08:00",
    timeOut: "",
    vehicleReg: "",
    company: "",
    driverName: "",
    deliveryRef: "",
    purpose: "Delivery",
    projectId: "",
    notes: "Template gate book entry",
    createdAt: now(),
  }),
  "lone-working": () => ({
    id: genId("lone"),
    workerName: "",
    task: "Template lone working task — specify location and check-in times",
    location: "",
    projectId: "",
    workDate: today(),
    startTime: "08:00",
    expectedEnd: "17:00",
    contactNumber: "",
    signedOff: false,
    signedOffAt: "",
    notes: "Template lone working log row",
    createdAt: now(),
  }),
  noise: () => ({
    id: genId("noise"),
    recordType: "noise",
    activityOrTool: "Breakers / plant (example)",
    location: "Site wide",
    projectId: "",
    logDate: today(),
    durationMinutes: "",
    laeqOrReading: "",
    hearingProtection: true,
    havTriggerTime: "",
    assessedBy: "",
    notes: "Template noise & vibration log — record exposure assessments",
    createdAt: now(),
  }),
  dsear: () => ({
    id: genId("dsear"),
    substanceOrArea: "Fuel store / flammable liquids (template)",
    hazardClass: "Flammable liquid",
    projectId: "",
    zoneClassification: "",
    assessmentRef: "",
    controlMeasures: "",
    reviewDate: today(),
    nextReviewDate: "",
    competentPerson: "",
    notes: "Template DSEAR assessment register row",
    createdAt: now(),
  }),
  "water-hygiene": () => ({
    id: genId("wh"),
    outletId: "WHB-01",
    outletType: "Sentinel tap / WHB",
    location: "Welfare unit",
    projectId: "",
    checkDate: today(),
    temperatureC: "",
    flushCompleted: true,
    responsible: "",
    riskAssessmentRef: "",
    notes: "Template water hygiene check — sentinel outlets and flushing regime",
    createdAt: now(),
  }),
};

export function modulesWithSeedTemplates(moduleIds) {
  return (moduleIds || []).filter((id) => Boolean(SEED_FACTORIES[id] && MODULE_PDF_REGISTRY[id]));
}

/** Add one starter row if register is empty. */
export function seedModuleRegisterIfEmpty(moduleId) {
  const cfg = MODULE_PDF_REGISTRY[moduleId];
  const factory = SEED_FACTORIES[moduleId];
  if (!cfg || !factory) return { ok: false, reason: "no_template" };

  const existing = loadOrgScoped(cfg.key, []);
  if (Array.isArray(existing) && existing.length > 0) return { ok: false, reason: "not_empty" };

  const item = factory();
  saveOrgScoped(cfg.key, [item]);
  return { ok: true, moduleId, item };
}

/** Seed all empty modules that have templates. */
export function seedEmptyRegisters(moduleIds) {
  const seeded = [];
  const skipped = [];

  (moduleIds || []).forEach((moduleId) => {
    const result = seedModuleRegisterIfEmpty(moduleId);
    if (result.ok) seeded.push(moduleId);
    else skipped.push({ moduleId, reason: result.reason });
  });

  return { seeded, skipped };
}

export function seedTemplateCount() {
  return Object.keys(SEED_FACTORIES).length;
}
