/**
 * Utility Mapping project playbooks — PAS128 M-series job starters (org-exclusive).
 */
import {
  canUseUtilityMappingExclusiveFeatures,
  isUtilityMappingExclusivePlaybookId,
} from "./utilityMappingExclusive";

export { isUtilityMappingExclusivePlaybookId };

/** @type {Array<{
 *   id: string,
 *   label: string,
 *   description: string,
 *   industryStarter?: string,
 *   surveyType?: string,
 *   pas128Ql?: string,
 *   pas128Method?: string,
 *   permitTypes: string[],
 *   msTemplate?: string,
 *   ramsSurveyKey?: string,
 *   gprPlaybook?: boolean,
 *   orgExclusive: boolean,
 *   checklistExtras?: string[],
 *   umQuickPackId?: string,
 * }>} */
export const UM_PROJECT_PLAYBOOKS = [
  {
    id: "um_pas128_m2",
    label: "PAS128 M2 — EML + GPR (real-time)",
    description: "Utility Mapping M2 workflow — EML then GPR on site, topo capture, CAD QC against records.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Confirm statutory undertaker records received (QL-D desktop)",
      "Brief team on M2 workflow: EML → GPR → topo mark-up capture",
      "UV paint mark-up with depth / material / diameter where known",
      "Upgrade to QL-B1 where EML and GPR agree within PAS128 tolerance",
      "Capture geo-photos: entrance, buried-services warning, mark-ups, MH/IC",
      "CAD QC against utility records before issue",
    ],
  },
  {
    id: "um_pas128_m2p",
    label: "PAS128 M2P — GPR post-processed",
    description: "M2 with post-processed GPR interpretation — corridor and complex sites.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2P",
    ramsSurveyKey: "utility_mapping_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_gpr_day",
    checklistExtras: [
      "Confirm post-process GPR deliverable required by client",
      "Archive raw GPR data and calibration plate check",
      "EML mark-up complete before GPR acquisition",
      "Post-process QC hold point before CAD issue",
    ],
  },
  {
    id: "um_pas128_m4p",
    label: "PAS128 M4P — desktop / limited detect",
    description: "Records-led / limited detection survey — TFR alignments where not located.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B4",
    pas128Method: "M4P",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Desktop records search complete and logged",
      "Walkover / limited detect scope agreed with client",
      "Mark TFR (taken from records) clearly on drawing",
      "State detection limitations in report section 5",
    ],
  },
  {
    id: "um_gpr_corridor",
    label: "GPR corridor / array day",
    description: "Dedicated GPR acquisition and interpretation deliverable.",
    industryStarter: "infrastructure",
    surveyType: "gpr_survey",
    ramsSurveyKey: "gpr_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_gpr_day",
    checklistExtras: [
      "Calibration plate check before first transect",
      "Traffic management / banksman for vehicle array",
      "Draft GPR report with BGS geology and weather enrichment",
      "Link anomalies to PAS128 survey where combined job",
    ],
  },
  {
    id: "um_topo_plus_utility",
    label: "Topo + PAS128 utility (combined)",
    description: "Combined topographical base and PAS128 utility detection — control network + EML/GPR.",
    industryStarter: "infrastructure",
    surveyType: "topo_plus_utility_survey",
    pas128Ql: "B1",
    pas128Method: "M2P",
    ramsSurveyKey: "topo_plus_utility_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Control network plan agreed for combined deliverable",
      "Utility records reviewed against topo base",
      "EML + GPR mark-up captured on topo control",
      "Combined CAD QC hold point before issue",
    ],
  },
  {
    id: "um_eml_cat",
    label: "EML / CAT & Genny only",
    description: "Electromagnetic location day — induction, connection, sonde and UV mark-up.",
    industryStarter: "infrastructure",
    surveyType: "eml_cat_survey",
    pas128Ql: "B2",
    pas128Method: "M3",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_eml_cat",
    checklistExtras: [
      "CAT & Genny calibration / battery check",
      "Records walkover before induction",
      "UV paint mark-up with depth notes",
      "Geo-photos of locate points and chambers",
    ],
  },
  {
    id: "um_service_clearance",
    label: "Service clearance for GI",
    description: "Clearance mark-up ahead of trial pits / boreholes — permit-to-dig interface.",
    industryStarter: "infrastructure",
    surveyType: "service_clearance_survey",
    ramsSurveyKey: "service_clearance_survey",
    permitTypes: ["excavation", "ground_disturbance", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_service_clearance",
    checklistExtras: [
      "GI contractor scope and dig locations received",
      "Records review and walkover complete",
      "Clearance marks on ground photographed",
      "Brief GI contractor on mark-up and exclusion zones",
    ],
  },
  {
    id: "um_survey_findings",
    label: "Survey findings report",
    description: "Findings-focused deliverable — site constraints, undetectable services, TFR notes.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B2",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Document site constraints and undetectable services",
      "List EML and GPR limitations in report",
      "Attach extent drawings / AOC photos",
      "Client acceptance block ready on page 2",
    ],
  },
];

/** @param {string} playbookId */
export function getUtilityMappingPlaybook(playbookId) {
  if (!canUseUtilityMappingExclusiveFeatures()) return null;
  return UM_PROJECT_PLAYBOOKS.find((p) => p.id === playbookId) || null;
}
