/**
 * Utility Mapping project playbooks — PAS128 M-series job starters (org-exclusive).
 */
import {
  canUseUtilityMappingExclusiveFeatures,
  isUtilityMappingExclusivePlaybookId,
} from "./utilityMappingExclusive";

export { isUtilityMappingExclusivePlaybookId };

/** @type {Array<{
 *   id: string,
 *   label: string,
 *   description: string,
 *   industryStarter?: string,
 *   surveyType?: string,
 *   pas128Ql?: string,
 *   pas128Method?: string,
 *   permitTypes: string[],
 *   msTemplate?: string,
 *   ramsSurveyKey?: string,
 *   gprPlaybook?: boolean,
 *   orgExclusive: boolean,
 *   checklistExtras?: string[],
 *   umQuickPackId?: string,
 * }>} */
export const UM_PROJECT_PLAYBOOKS = [
  {
    id: "um_pas128_m2",
    label: "PAS128 M2 — EML + GPR (real-time)",
    description: "Utility Mapping M2 workflow — EML then GPR on site, topo capture, CAD QC against records.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Confirm statutory undertaker records received (QL-D desktop)",
      "Brief team on M2 workflow: EML → GPR → topo mark-up capture",
      "UV paint mark-up with depth / material / diameter where known",
      "Upgrade to QL-B1 where EML and GPR agree within PAS128 tolerance",
      "Capture geo-photos: entrance, buried-services warning, mark-ups, MH/IC",
      "CAD QC against utility records before issue",
    ],
  },
  {
    id: "um_pas128_m2p",
    label: "PAS128 M2P — GPR post-processed",
    description: "M2 with post-processed GPR interpretation — corridor and complex sites.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2P",
    ramsSurveyKey: "utility_mapping_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_gpr_day",
    checklistExtras: [
      "Confirm post-process GPR deliverable required by client",
      "Archive raw GPR data and calibration plate check",
      "EML mark-up complete before GPR acquisition",
      "Post-process QC hold point before CAD issue",
    ],
  },
  {
    id: "um_pas128_m4p",
    label: "PAS128 M4P — desktop / limited detect",
    description: "Records-led / limited detection survey — TFR alignments where not located.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B4",
    pas128Method: "M4P",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Desktop records search complete and logged",
      "Walkover / limited detect scope agreed with client",
      "Mark TFR (taken from records) clearly on drawing",
      "State detection limitations in report section 5",
    ],
  },
  {
    id: "um_gpr_corridor",
    label: "GPR corridor / array day",
    description: "Dedicated GPR acquisition and interpretation deliverable.",
    industryStarter: "infrastructure",
    surveyType: "gpr_survey",
    ramsSurveyKey: "gpr_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_gpr_day",
    checklistExtras: [
      "Calibration plate check before first transect",
      "Traffic management / banksman for vehicle array",
      "Draft GPR report with BGS geology and weather enrichment",
      "Link anomalies to PAS128 survey where combined job",
    ],
  },
  {
    id: "um_topo_plus_utility",
    label: "Topo + PAS128 utility (combined)",
    description: "Combined topographical base and PAS128 utility detection — control network + EML/GPR.",
    industryStarter: "infrastructure",
    surveyType: "topo_plus_utility_survey",
    pas128Ql: "B1",
    pas128Method: "M2P",
    ramsSurveyKey: "topo_plus_utility_survey",
    gprPlaybook: true,
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Control network plan agreed for combined deliverable",
      "Utility records reviewed against topo base",
      "EML + GPR mark-up captured on topo control",
      "Combined CAD QC hold point before issue",
    ],
  },
  {
    id: "um_eml_cat",
    label: "EML / CAT & Genny only",
    description: "Electromagnetic location day — induction, connection, sonde and UV mark-up.",
    industryStarter: "infrastructure",
    surveyType: "eml_cat_survey",
    pas128Ql: "B2",
    pas128Method: "M3",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_eml_cat",
    checklistExtras: [
      "CAT & Genny calibration / battery check",
      "Records walkover before induction",
      "UV paint mark-up with depth notes",
      "Geo-photos of locate points and chambers",
    ],
  },
  {
    id: "um_service_clearance",
    label: "Service clearance for GI",
    description: "Clearance mark-up ahead of trial pits / boreholes — permit-to-dig interface.",
    industryStarter: "infrastructure",
    surveyType: "service_clearance_survey",
    ramsSurveyKey: "service_clearance_survey",
    permitTypes: ["excavation", "ground_disturbance", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_service_clearance",
    checklistExtras: [
      "GI contractor scope and dig locations received",
      "Records review and walkover complete",
      "Clearance marks on ground photographed",
      "Brief GI contractor on mark-up and exclusion zones",
    ],
  },
  {
    id: "um_survey_findings",
    label: "Survey findings report",
    description: "Findings-focused deliverable — site constraints, undetectable services, TFR notes.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B2",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    permitTypes: ["excavation", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Document site constraints and undetectable services",
      "List EML and GPR limitations in report",
      "Attach extent drawings / AOC photos",
      "Client acceptance block ready on page 2",
    ],
  },
  {
    id: "um_topo_ts_gnss",
    label: "Topographical — total station & GNSS",
    description: "Land survey day — robotic total station and/or GNSS control, feature capture and checked CAD.",
    industryStarter: "infrastructure",
    surveyType: "topographical_survey",
    ramsSurveyKey: "topographical_survey",
    permitTypes: ["general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Control network / OSGB36 tie-in agreed",
      "Total station and GNSS calibration / pre-use checks",
      "Closure checks and independent check shots logged",
      "Issue topo CAD/PDF with accuracy statement",
    ],
  },
  {
    id: "um_laser_scanning",
    label: "Laser scanning / reality capture",
    description: "TLS point-cloud day — laser safety, control registration and digital twin deliverable.",
    industryStarter: "infrastructure",
    surveyType: "laser_scanning",
    ramsSurveyKey: "laser_scanning",
    permitTypes: ["general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Laser exclusion zone and eye-safety briefing",
      "Control / targets verified before scan epoch",
      "Scan overlap and registration RMS checked",
      "Issue point cloud / mesh with coordinate metadata",
    ],
  },
  {
    id: "um_site_treatment",
    label: "Site context — treatment works",
    description: "PAS128 / utility day on WWTW or pumping station — H₂S, escort and wet-well controls.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    siteContextKey: "treatment_works",
    permitTypes: ["excavation", "confined_space", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Client escort / process-area induction",
      "Gas monitor bump test before entry",
      "Apply RAMS site context: Treatment works",
      "No wet-well entry without CS permit",
    ],
  },
  {
    id: "um_site_substation",
    label: "Site context — substation / HV",
    description: "Utility or topo survey in DNO/IDNO compound — escort, EMI and safe walking routes.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2",
    ramsSurveyKey: "utility_mapping_survey",
    siteContextKey: "substation_hv",
    permitTypes: ["general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "Authorised person / electrical escort briefing",
      "GNSS/UAV EMI contingency agreed",
      "Apply RAMS site context: Substation / HV",
      "Stay on marked safe routes only",
    ],
  },
  {
    id: "um_site_rail",
    label: "Site context — rail / NR",
    description: "Trackside survey under PTS / possession — COSS briefing and handback.",
    industryStarter: "infrastructure",
    surveyType: "utility_mapping_survey",
    pas128Ql: "B1",
    pas128Method: "M2",
    ramsSurveyKey: "rail_public_infrastructure_survey",
    siteContextKey: "rail_nr",
    permitTypes: ["rail_corridor_access", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_pas128_baseline",
    checklistExtras: [
      "PTS cards and COSS / SWL briefing",
      "Possession / SSOW window confirmed",
      "Apply RAMS site context: Rail / NR",
      "Handback before trains resume",
    ],
  },
  {
    id: "um_site_highway",
    label: "Site context — highway / TM",
    description: "Live carriageway survey — Chapter 8 TM, banksman and pedestrian segregation.",
    industryStarter: "infrastructure",
    surveyType: "gpr_survey",
    ramsSurveyKey: "highway_live_corridor_survey",
    siteContextKey: "highway_tm",
    gprPlaybook: true,
    permitTypes: ["general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_gpr_day",
    checklistExtras: [
      "TM layout approved before mobilisation",
      "Banksman briefed for scan vehicle / verge work",
      "Apply RAMS site context: Highway / TM",
      "TM demobilised and carriageway reopened",
    ],
  },
  {
    id: "um_site_brownfield",
    label: "Site context — brownfield",
    description: "Survey on contaminated / made ground — hygiene, RPE and unexpected-finds stop-work.",
    industryStarter: "infrastructure",
    surveyType: "service_clearance_survey",
    ramsSurveyKey: "service_clearance_survey",
    siteContextKey: "brownfield",
    permitTypes: ["excavation", "ground_disturbance", "general"],
    msTemplate: "pas128Mobilisation",
    orgExclusive: true,
    umQuickPackId: "orgexclusive_um_service_clearance",
    checklistExtras: [
      "Contamination desk study briefed",
      "Apply RAMS site context: Brownfield",
      "Unexpected finds stop-work understood",
      "Decontaminate kit before demob",
    ],
  },
];

/** @param {string} playbookId */
export function getUtilityMappingPlaybook(playbookId) {
  if (!canUseUtilityMappingExclusiveFeatures()) return null;
  return UM_PROJECT_PLAYBOOKS.find((p) => p.id === playbookId) || null;
}
