import {
  MapPin,
  PenTool,
  FileText,
  HardHat,
  Sun,
  QrCode,
  PenLine,
  Clock,
  AlertTriangle,
  FlaskConical,
  ClipboardCheck,
  Siren,
  ListChecks,
  Flame,
  Shield,
  Wrench,
  GraduationCap,
  Users,
  MessageSquare,
  HeartPulse,
  UserX,
  Leaf,
  Eye,
  GalleryVertical,
  Truck,
  DoorOpen,
  Biohazard,
  Box,
  Lock,
  Zap,
  ArrowUpFromLine,
  Sparkles,
  Volume2,
  Construction,
  Shovel,
  Building2,
  Droplets,
  Trash2,
  ShieldCheck,
  ClipboardList,
  Wheat,
  Microscope,
  BarChart3,
  Calendar,
  LayoutTemplate,
  Bot,
  Camera,
  Globe,
  TrendingUp,
  Building,
  FolderOpen,
  Database,
  ScrollText,
  Crown,
  CircleHelp,
  Settings,
} from "lucide-react";

export const DEFAULT_MODULE_ICON = FileText;

/** @type {Record<string, import("lucide-react").LucideIcon>} */
export const MODULE_ICONS = {
  "site-map": MapPin,
  "project-drawings": PenTool,
  "method-statement": FileText,
  cdm: HardHat,
  "daily-briefing": Sun,
  induction: QrCode,
  signatures: PenLine,
  timesheets: Clock,
  snags: AlertTriangle,
  coshh: FlaskConical,
  inspections: ClipboardCheck,
  incidents: Siren,
  "incident-actions": ListChecks,
  "incident-map": MapPin,
  riddor: FileText,
  emergency: HeartPulse,
  ppe: Shield,
  plant: Wrench,
  fire: Flame,
  "hot-work": Flame,
  training: GraduationCap,
  visitors: Users,
  "toolbox-reg": MessageSquare,
  "first-aid": HeartPulse,
  "lone-working": UserX,
  environmental: Leaf,
  observations: Eye,
  ladders: GalleryVertical,
  mewp: Truck,
  gate: DoorOpen,
  asbestos: Biohazard,
  "confined-space": Box,
  loto: Lock,
  "electrical-pat": Zap,
  lifting: ArrowUpFromLine,
  dsear: Sparkles,
  noise: Volume2,
  scaffold: Construction,
  excavation: Shovel,
  "temp-works": Building2,
  welfare: ShieldCheck,
  "water-hygiene": Droplets,
  waste: Trash2,
  "high-care-access": ShieldCheck,
  "cip-signoff": ClipboardList,
  "allergen-changeovers": Wheat,
  "gmp-deviations": Microscope,
  analytics: BarChart3,
  "monthly-report": Calendar,
  templates: LayoutTemplate,
  "ai-rams": Bot,
  "ai-toolbox": Bot,
  "ai-photo": Camera,
  "client-portal": Globe,
  "client-acquisition": TrendingUp,
  "sales-enablement": TrendingUp,
  "enterprise-readiness": Building,
  subcontractor: Users,
  documents: FolderOpen,
  backup: Database,
  audit: ScrollText,
  superadmin: Crown,
  help: CircleHelp,
  settings: Settings,
};
