/**
 * Workspace route ids only — no view loaders.
 * Kept as a leaf module so `workspaceNavContext` can validate ids without
 * importing `workspaceViews` (which lazy-loads every module and created
 * circular TDZ errors in Vite chunks such as project-drawing / rams-builder).
 *
 * Keep in sync with keys of `workspaceViewLoaders` in `workspaceViews.js`
 * (enforced by workspaceViewIds.test.js).
 */
export const WORKSPACE_VIEW_IDS = [
  "dashboard",
  "management-overview",
  "projects",
  "people",
  "permits",
  "rams",
  "workers",
  "bin",
  "site-map",
  "project-drawings",
  "method-statement",
  "cdm",
  "whs-plan",
  "bhp-plan",
  "daily-briefing",
  "induction",
  "signatures",
  "timesheets",
  "snags",
  "geo-photos",
  "coshh",
  "inspections",
  "incidents",
  "incident-actions",
  "incident-map",
  "riddor",
  "notifiable-incidents",
  "emergency",
  "ppe",
  "plant",
  "vehicles",
  "fire",
  "hot-work",
  "training",
  "visitors",
  "toolbox-reg",
  "first-aid",
  "lone-working",
  "environmental",
  "observations",
  "ladders",
  "mewp",
  "gate",
  "asbestos",
  "confined-space",
  "loto",
  "electrical-pat",
  "lifting",
  "dsear",
  "high-care-access",
  "cip-signoff",
  "allergen-changeovers",
  "gmp-deviations",
  "ghp-register",
  "dynamic-ra",
  "legislation",
  "hygiene-setup",
  "fess-setup",
  "fess-sites",
  "construction-setup",
  "noise",
  "scaffold",
  "excavation",
  "temp-works",
  "welfare",
  "water-hygiene",
  "analytics",
  "monthly-report",
  "survey-report",
  "gpr-report",
  "waste",
  "templates",
  "ai-rams",
  "ai-toolbox",
  "ai-photo",
  "client-portal",
  "client-acquisition",
  "sales-enablement",
  "enterprise-readiness",
  "subcontractor",
  "documents",
  "backup",
  "audit",
  "superadmin",
  "help",
];

export const WORKSPACE_VIEW_ID_SET = new Set(WORKSPACE_VIEW_IDS);
