-- Web Push subscriptions per user/org for permit and ops notifications.
create table if not exists public.org_push_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_slug text not null,
  endpoint text not null,
  subscription jsonb not null,
  user_agent text
);

create unique index if not exists org_push_subscriptions_user_org_endpoint_uidx
  on public.org_push_subscriptions (user_id, org_slug, endpoint);

create index if not exists org_push_subscriptions_user_org_idx
  on public.org_push_subscriptions (user_id, org_slug);

create index if not exists org_push_subscriptions_last_seen_idx
  on public.org_push_subscriptions (last_seen_at desc);

create or replace function public.touch_org_push_subscriptions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_org_push_subscriptions_updated_at on public.org_push_subscriptions;
create trigger trg_org_push_subscriptions_updated_at
before update on public.org_push_subscriptions
for each row execute function public.touch_org_push_subscriptions_updated_at();

alter table public.org_push_subscriptions enable row level security;

drop policy if exists "org_push_subscriptions_select_own" on public.org_push_subscriptions;
create policy "org_push_subscriptions_select_own"
  on public.org_push_subscriptions for select
  using (auth.uid() = user_id);

drop policy if exists "org_push_subscriptions_insert_own" on public.org_push_subscriptions;
create policy "org_push_subscriptions_insert_own"
  on public.org_push_subscriptions for insert
  with check (auth.uid() = user_id);

drop policy if exists "org_push_subscriptions_update_own" on public.org_push_subscriptions;
create policy "org_push_subscriptions_update_own"
  on public.org_push_subscriptions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "org_push_subscriptions_delete_own" on public.org_push_subscriptions;
create policy "org_push_subscriptions_delete_own"
  on public.org_push_subscriptions for delete
  using (auth.uid() = user_id);

comment on table public.org_push_subscriptions is 'Web Push subscriptions scoped per Supabase user + org slug.';
