-- Per-user module onboarding progress (syncs across devices).
create table if not exists public.user_module_guides (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  org_slug text not null,
  module text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  prefs jsonb not null default '{}'::jsonb
);

create unique index if not exists user_module_guides_user_org_module_uidx
  on public.user_module_guides (user_id, org_slug, module);

create index if not exists user_module_guides_user_org_idx
  on public.user_module_guides (user_id, org_slug);

create or replace function public.touch_user_module_guides_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_module_guides_updated_at on public.user_module_guides;
create trigger trg_user_module_guides_updated_at
before update on public.user_module_guides
for each row execute function public.touch_user_module_guides_updated_at();

alter table public.user_module_guides enable row level security;

drop policy if exists "user_module_guides_select_own" on public.user_module_guides;
create policy "user_module_guides_select_own"
  on public.user_module_guides for select
  using (auth.uid() = user_id);

drop policy if exists "user_module_guides_insert_own" on public.user_module_guides;
create policy "user_module_guides_insert_own"
  on public.user_module_guides for insert
  with check (auth.uid() = user_id);

drop policy if exists "user_module_guides_update_own" on public.user_module_guides;
create policy "user_module_guides_update_own"
  on public.user_module_guides for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "user_module_guides_delete_own" on public.user_module_guides;
create policy "user_module_guides_delete_own"
  on public.user_module_guides for delete
  using (auth.uid() = user_id);

comment on table public.user_module_guides is 'Module onboarding/guide completion per Supabase user and org';
